// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

#[allow(dead_code)]
struct Counter(::std::rc::Rc<::std::cell::RefCell<CounterInner>>);
#[derive(Debug, Default)]
#[allow(dead_code)]
struct CounterInner {
    value: f64,
}
impl Clone for Counter {
    fn clone(&self) -> Self {
        Counter(::std::rc::Rc::clone(&self.0))
    }
}
impl PartialEq for Counter {
    fn eq(&self, other: &Self) -> bool {
        ::std::rc::Rc::ptr_eq(&self.0, &other.0)
    }
}
impl Default for Counter {
    fn default() -> Self {
        Counter(::std::rc::Rc::new(::std::cell::RefCell::new(CounterInner::default())))
    }
}
impl ::std::fmt::Debug for Counter {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::std::fmt::Debug::fmt(&*self.0.borrow(), formatter)
    }
}

// @smelt:prelude-end — generated program below

fn main() {
    let counter: Counter;
    let _smelt_tmp_1: Counter = Counter::new(4.0);
    counter = _smelt_tmp_1;
    let _smelt_tmp_2: f64 = counter.inc(3.0);
    let _ = { println!("{}", _smelt_tmp_2); };
    return;
}

impl Counter {
    fn new(value: f64) -> Self {
    let mut this: Self = Counter(::std::rc::Rc::new(::std::cell::RefCell::new(CounterInner { value: 0.0 })));
    this.0.borrow_mut().value = value;
    return this;
    }
    fn inc(&self, delta: f64) -> f64 {
    let _smelt_tmp_2: f64 = self.0.borrow().value.clone() + delta;
    self.0.borrow_mut().value = _smelt_tmp_2;
    return self.0.borrow().value.clone();
    }
}
