//! Declaration stub emission for TypeScript and Python LSPs.

use smelt_hir::{Crate, Function, Item, ModuleId, Type};
use std::{fmt::Write as _, fs, path::Path};

/// Emit `.d.ts` and `.pyi` files next to each lowered source module.
///
/// # Errors
///
/// Returns an error if any declaration file cannot be written.
pub(super) fn emit_type_declarations(
    krate: &Crate,
    modules: &[(String, ModuleId)],
) -> Result<(), Box<dyn std::error::Error>> {
    for (path, module_id) in modules {
        let source_path = Path::new(path);
        let mut typescript_path = source_path.to_path_buf();
        typescript_path.set_extension("d.ts");
        fs::write(typescript_path, typescript_declaration(krate, *module_id))?;

        let mut python_path = source_path.to_path_buf();
        python_path.set_extension("pyi");
        fs::write(python_path, python_declaration(krate, *module_id))?;
    }
    Ok(())
}

/// Format a TypeScript declaration file for one HIR module.
#[must_use]
#[expect(
    clippy::too_many_lines,
    reason = "declaration formatting keeps the TypeScript item cases together"
)]
fn typescript_declaration(krate: &Crate, module_id: ModuleId) -> String {
    let module = &krate.modules[module_id.0 as usize];
    let mut out = String::new();
    out.push_str("// Generated by smelt. Do not edit.\n\n");
    for item_id in &module.items {
        match &krate.items[item_id.0 as usize] {
            Item::Function(function)
                if matches!(function.owner, smelt_hir::FunctionOwner::Module) =>
            {
                let params = function
                    .params
                    .iter()
                    .map(|param| {
                        format!(
                            "{}: {}",
                            symbol_name(krate, param.name),
                            ts_type(krate, param.ty)
                        )
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                writeln!(
                    out,
                    "export declare function {}({params}): {};",
                    symbol_name(krate, function.name),
                    ts_type(krate, function.return_ty)
                )
                .expect("writing to String cannot fail");
            }
            Item::Class(class) => {
                writeln!(
                    out,
                    "export declare class {} {{",
                    symbol_name(krate, class.name)
                )
                .expect("writing to String cannot fail");
                for field in &class.fields {
                    writeln!(
                        out,
                        "  {}: {};",
                        symbol_name(krate, field.name),
                        ts_type(krate, field.ty)
                    )
                    .expect("writing to String cannot fail");
                }
                out.push_str("}\n");
            }
            Item::Interface(interface) => {
                writeln!(
                    out,
                    "export interface {} {{",
                    symbol_name(krate, interface.name)
                )
                .expect("writing to String cannot fail");
                for field in &interface.fields {
                    writeln!(
                        out,
                        "  {}: {};",
                        symbol_name(krate, field.name),
                        ts_type(krate, field.ty)
                    )
                    .expect("writing to String cannot fail");
                }
                for method in &interface.methods {
                    let params = method
                        .params
                        .iter()
                        .map(|param| {
                            format!(
                                "{}: {}",
                                symbol_name(krate, param.name),
                                ts_type(krate, param.ty)
                            )
                        })
                        .collect::<Vec<_>>()
                        .join(", ");
                    writeln!(
                        out,
                        "  {}({params}): {};",
                        symbol_name(krate, method.name),
                        ts_type(krate, method.return_ty)
                    )
                    .expect("writing to String cannot fail");
                }
                out.push_str("}\n");
            }
            Item::TypeAlias(alias) => {
                writeln!(
                    out,
                    "export type {} = {};",
                    symbol_name(krate, alias.name),
                    ts_type(krate, alias.ty)
                )
                .expect("writing to String cannot fail");
            }
            Item::Function(_) | Item::Const(_) => {}
        }
    }
    out
}

/// Format a Python stub file for one HIR module.
#[must_use]
fn python_declaration(krate: &Crate, module_id: ModuleId) -> String {
    let module = &krate.modules[module_id.0 as usize];
    let mut out = String::new();
    out.push_str("# Generated by smelt. Do not edit.\n\n");
    for item_id in &module.items {
        match &krate.items[item_id.0 as usize] {
            Item::Function(function)
                if matches!(function.owner, smelt_hir::FunctionOwner::Module) =>
            {
                write_python_function(krate, function, &mut out);
            }
            Item::Class(class) => {
                writeln!(out, "class {}:", symbol_name(krate, class.name))
                    .expect("writing to String cannot fail");
                if class.fields.is_empty() && class.methods.is_empty() {
                    out.push_str("    ...\n");
                } else {
                    for field in &class.fields {
                        writeln!(
                            out,
                            "    {}: {}",
                            symbol_name(krate, field.name),
                            py_type(krate, field.ty)
                        )
                        .expect("writing to String cannot fail");
                    }
                }
            }
            Item::Function(_) | Item::Interface(_) | Item::TypeAlias(_) | Item::Const(_) => {}
        }
    }
    out
}

/// Append a Python function signature to a stub file.
fn write_python_function(krate: &Crate, function: &Function, out: &mut String) {
    let params = function
        .params
        .iter()
        .map(|param| {
            format!(
                "{}: {}",
                symbol_name(krate, param.name),
                py_type(krate, param.ty)
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        out,
        "def {}({params}) -> {}: ...",
        symbol_name(krate, function.name),
        py_type(krate, function.return_ty)
    )
    .expect("writing to String cannot fail");
}

/// Resolve a symbol to display text.
fn symbol_name(krate: &Crate, symbol: smelt_hir::Symbol) -> &str {
    krate
        .names
        .get(symbol)
        .or_else(|| krate.symbols.get(symbol))
        .unwrap_or("_")
}

/// Render a HIR type as TypeScript.
fn ts_type(krate: &Crate, ty: smelt_hir::TypeId) -> String {
    match krate.types.get(ty) {
        Some(Type::Bool) => "boolean".to_owned(),
        Some(Type::Int | Type::Float) => "number".to_owned(),
        Some(Type::String) => "string".to_owned(),
        Some(Type::None) => "void".to_owned(),
        Some(Type::List(item) | Type::Set(item)) => {
            format!("Array<{}>", ts_type(krate, *item))
        }
        Some(Type::Dict(key, value)) => {
            format!(
                "Record<{}, {}>",
                ts_type(krate, *key),
                ts_type(krate, *value)
            )
        }
        Some(Type::Tuple(items)) => {
            let items = items
                .iter()
                .map(|item| ts_type(krate, *item))
                .collect::<Vec<_>>()
                .join(", ");
            format!("[{items}]")
        }
        Some(Type::Optional(item)) => format!("{} | null", ts_type(krate, *item)),
        Some(Type::Union(items)) => items
            .iter()
            .map(|item| ts_type(krate, *item))
            .collect::<Vec<_>>()
            .join(" | "),
        Some(Type::Class { name, .. }) => symbol_name(krate, *name).to_owned(),
        Some(Type::Function(function)) => {
            let params = function
                .params
                .iter()
                .map(|param| ts_type(krate, *param))
                .collect::<Vec<_>>()
                .join(", ");
            format!("({params}) => {}", ts_type(krate, function.return_ty))
        }
        Some(Type::Future(item)) => format!("Promise<{}>", ts_type(krate, *item)),
        None => "unknown".to_owned(),
    }
}

/// Render a HIR type as Python.
fn py_type(krate: &Crate, ty: smelt_hir::TypeId) -> String {
    match krate.types.get(ty) {
        Some(Type::Bool) => "bool".to_owned(),
        Some(Type::Int) => "int".to_owned(),
        Some(Type::Float) => "float".to_owned(),
        Some(Type::String) => "str".to_owned(),
        Some(Type::None) => "None".to_owned(),
        Some(Type::List(item)) => format!("list[{}]", py_type(krate, *item)),
        Some(Type::Set(item)) => format!("set[{}]", py_type(krate, *item)),
        Some(Type::Dict(key, value)) => {
            format!("dict[{}, {}]", py_type(krate, *key), py_type(krate, *value))
        }
        Some(Type::Tuple(items)) => {
            let items = items
                .iter()
                .map(|item| py_type(krate, *item))
                .collect::<Vec<_>>()
                .join(", ");
            format!("tuple[{items}]")
        }
        Some(Type::Optional(item)) => format!("{} | None", py_type(krate, *item)),
        Some(Type::Union(items)) => items
            .iter()
            .map(|item| py_type(krate, *item))
            .collect::<Vec<_>>()
            .join(" | "),
        Some(Type::Class { name, .. }) => symbol_name(krate, *name).to_owned(),
        Some(Type::Function(_)) => "typing.Callable".to_owned(),
        Some(Type::Future(item)) => format!("typing.Awaitable[{}]", py_type(krate, *item)),
        None => "typing.Any".to_owned(),
    }
}
