// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

#[path = "source_main.rs"]
mod __smelt_module_source_main;
pub(crate) use __smelt_module_source_main::*;


thread_local! {
    static SMELT_NEXT_OBJECT_ID: ::std::cell::Cell<usize> = const { ::std::cell::Cell::new(1) };
}

#[allow(dead_code)]
fn smelt_next_object_id() -> usize {
    SMELT_NEXT_OBJECT_ID.with(|next| { let id = next.get(); next.set(id.saturating_add(1)); id })
}

/// A JavaScript array: a reference identity plus a shared backing buffer.
pub struct SmeltList<T> {
    id: usize,
    values: ::std::rc::Rc<::std::cell::RefCell<Vec<T>>>,
}
impl<T: ::std::fmt::Debug> ::std::fmt::Debug for SmeltList<T> { fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result { self.values.borrow().fmt(formatter) } }
impl<T> Clone for SmeltList<T> { fn clone(&self) -> Self { Self { id: self.id, values: ::std::rc::Rc::clone(&self.values) } } }
#[allow(dead_code)]
impl<T> SmeltList<T> {
    /// Create an identity-bearing typed list with a fresh JS reference identity.
    fn new(values: Vec<T>) -> Self { Self { id: smelt_next_object_id(), values: ::std::rc::Rc::new(::std::cell::RefCell::new(values)) } }
    /// Reuse a caller-supplied identity so an erase/extract round-trip stays `===` equal.
    fn with_id(id: usize, values: Vec<T>) -> Self { Self { id, values: ::std::rc::Rc::new(::std::cell::RefCell::new(values)) } }
    /// Reuse an existing shared buffer, so a re-wrap keeps aliasing the same array.
    fn with_storage(id: usize, values: ::std::rc::Rc<::std::cell::RefCell<Vec<T>>>) -> Self { Self { id, values } }
    /// Another handle on this array's shared buffer.
    fn storage(&self) -> ::std::rc::Rc<::std::cell::RefCell<Vec<T>>> { ::std::rc::Rc::clone(&self.values) }
    /// JS reference identity of this list.
    fn id(&self) -> usize { self.id }
    /// Borrow the backing storage for reading. The guard lives to the end of the
    /// enclosing statement; never pair it with `borrow_mut` in one expression.
    fn borrow(&self) -> ::std::cell::Ref<'_, Vec<T>> { self.values.borrow() }
    /// Borrow the backing storage for writing, through the shared cell — so this
    /// takes `&self`, and every other handle on the array observes the write.
    fn borrow_mut(&self) -> ::std::cell::RefMut<'_, Vec<T>> { self.values.borrow_mut() }
    /// Element count, taking its own short-lived borrow.
    fn len(&self) -> usize { self.values.borrow().len() }
    /// Whether the array holds no elements.
    fn is_empty(&self) -> bool { self.values.borrow().is_empty() }
    /// Replace every element in place, so aliases observe the new contents.
    fn replace_all(&self, values: Vec<T>) { *self.values.borrow_mut() = values; }
}
#[allow(dead_code)]
impl<T: Clone> SmeltList<T> {
    /// A JS array copy (`[...a]`, `slice`): same contents, a NEW identity AND a
    /// new buffer. This is the operation that keeps sharing from over-sharing.
    fn fresh_copy(&self) -> Self { Self::new(self.values.borrow().clone()) }
    /// Snapshot the elements. This COPIES unless this is the last handle, so
    /// mutating the result does not write back.
    fn into_vec(self) -> Vec<T> { match ::std::rc::Rc::try_unwrap(self.values) { Ok(cell) => cell.into_inner(), Err(shared) => shared.borrow().clone() } }
    /// Snapshot the elements without consuming the handle.
    fn to_vec(&self) -> Vec<T> { self.values.borrow().clone() }
    /// Read one element by index, cloned out of the shared buffer (JS `arr[i]`).
    fn get_index(&self, index: usize) -> Option<T> { self.values.borrow().get(index).cloned() }
    /// Set the element at a numeric index, extending with `fill` holes to match JS `arr[i] = v`.
    fn set_index(&self, index: usize, value: T, fill: T) { let mut values = self.values.borrow_mut(); if index >= values.len() { values.resize(index.saturating_add(1), fill); } values[index] = value; }
    /// Iterate a snapshot of the elements, so the buffer is not borrowed across the loop body.
    fn iter(&self) -> ::std::vec::IntoIter<T> { self.values.borrow().clone().into_iter() }
}
impl<T> From<Vec<T>> for SmeltList<T> { fn from(values: Vec<T>) -> Self { Self::new(values) } }
impl<T> ::std::iter::FromIterator<T> for SmeltList<T> { fn from_iter<I: IntoIterator<Item = T>>(iter: I) -> Self { Self::new(iter.into_iter().collect()) } }
impl<T: Clone> IntoIterator for SmeltList<T> { type Item = T; type IntoIter = ::std::vec::IntoIter<T>; fn into_iter(self) -> Self::IntoIter { self.into_vec().into_iter() } }
impl<T: Clone> IntoIterator for &SmeltList<T> { type Item = T; type IntoIter = ::std::vec::IntoIter<T>; fn into_iter(self) -> Self::IntoIter { self.values.borrow().clone().into_iter() } }
impl<T: PartialEq> PartialEq for SmeltList<T> { fn eq(&self, other: &Self) -> bool { *self.values.borrow() == *other.values.borrow() } }
impl<T: PartialEq> Eq for SmeltList<T> {}
impl<T: ::std::hash::Hash> ::std::hash::Hash for SmeltList<T> { fn hash<H: ::std::hash::Hasher>(&self, state: &mut H) { self.values.borrow().hash(state); } }
impl<T> Default for SmeltList<T> { fn default() -> Self { Self::new(Vec::new()) } }
impl<T: Clone> From<SmeltList<T>> for Vec<T> { fn from(list: SmeltList<T>) -> Self { list.into_vec() } }

// @smelt:prelude-end — generated program below
fn main() {
    let _smelt_tmp_4: SmeltList<f64>;
    let _smelt_tmp_7: SmeltList<f64>;
    let _smelt_tmp_0: String = escape_html("a\"b&c<d>e".to_owned());
    let _ = { println!("{}", _smelt_tmp_0); };
    let _smelt_tmp_2: String = escape_html("nothing to escape".to_owned());
    let _ = { println!("{}", _smelt_tmp_2); };
    _smelt_tmp_4 = Into::<SmeltList<_>>::into(SmeltList::from({ let smelt_list_items: Vec<f64> = vec![1.0, 2.0, 3.0, 4.0, 5.0]; smelt_list_items }));
    let _smelt_tmp_5: f64 = sum_odd(_smelt_tmp_4);
    let _ = { println!("{}", _smelt_tmp_5); };
    _smelt_tmp_7 = Into::<SmeltList<_>>::into(SmeltList::from({ let smelt_list_items: Vec<f64> = vec![1.0, 2.0, 3.0]; smelt_list_items }));
    let _smelt_tmp_8: String = classify(_smelt_tmp_7);
    let _ = { println!("{}", _smelt_tmp_8); };
    return;
}

// ==== source_main.rs
// @generated by smelt. Do not edit by hand.
// source: <example>/src/main.ts
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

use super::*;

pub(crate) fn escape_html(str: String) -> String {
    let mut code: f64;
    let mut replacement: String;
    let mut _smelt_tmp_6: f64;
    let mut _smelt_tmp_7: bool;
    let mut _smelt_tmp_8: f64;
    let mut _smelt_tmp_9: String;
    let mut _smelt_tmp_10: String;
    let mut _smelt_tmp_11: String;
    let mut _smelt_tmp_12: f64;
    let mut _smelt_tmp_13: f64;
    let mut _smelt_tmp_14: f64;
    let mut _smelt_tmp_15: String;
    let mut _smelt_tmp_16: String;
    let mut out: String = "".to_owned();
    let mut last_index: f64 = 0.0;
    let mut i: f64 = 0.0;
    loop {
    _smelt_tmp_6 = str.chars().count() as f64;
    _smelt_tmp_7 = i < _smelt_tmp_6;
    if !(_smelt_tmp_7) { break; }
    _smelt_tmp_8 = str.clone().chars().nth(i as usize).map_or(f64::NAN, |ch| ch as u32 as f64);
    code = _smelt_tmp_8;
    replacement = "".to_owned();
    match code {
        34.0 => {
    replacement = "&quot;".to_owned();
    _smelt_tmp_9 = str.clone().chars().skip({ let len = str.clone().chars().count() as i64; let index = last_index as i64; if index < 0 { (len + index).clamp(0, len) as usize } else { index.clamp(0, len) as usize } }).take({ let len = str.clone().chars().count() as i64; let index = i as i64; if index < 0 { (len + index).clamp(0, len) as usize } else { index.clamp(0, len) as usize } }.saturating_sub({ let len = str.clone().chars().count() as i64; let index = last_index as i64; if index < 0 { (len + index).clamp(0, len) as usize } else { index.clamp(0, len) as usize } })).collect::<String>();
    _smelt_tmp_10 = _smelt_tmp_9 + &replacement;
    _smelt_tmp_11 = out + &_smelt_tmp_10;
    out = _smelt_tmp_11;
    _smelt_tmp_12 = i + 1.0;
    last_index = _smelt_tmp_12;
    _smelt_tmp_13 = i + 1.0;
    i = _smelt_tmp_13;
    continue;
        }
        38.0 => {
    replacement = "&amp;".to_owned();
    _smelt_tmp_9 = str.clone().chars().skip({ let len = str.clone().chars().count() as i64; let index = last_index as i64; if index < 0 { (len + index).clamp(0, len) as usize } else { index.clamp(0, len) as usize } }).take({ let len = str.clone().chars().count() as i64; let index = i as i64; if index < 0 { (len + index).clamp(0, len) as usize } else { index.clamp(0, len) as usize } }.saturating_sub({ let len = str.clone().chars().count() as i64; let index = last_index as i64; if index < 0 { (len + index).clamp(0, len) as usize } else { index.clamp(0, len) as usize } })).collect::<String>();
    _smelt_tmp_10 = _smelt_tmp_9 + &replacement;
    _smelt_tmp_11 = out + &_smelt_tmp_10;
    out = _smelt_tmp_11;
    _smelt_tmp_12 = i + 1.0;
    last_index = _smelt_tmp_12;
    _smelt_tmp_13 = i + 1.0;
    i = _smelt_tmp_13;
    continue;
        }
        60.0 => {
    replacement = "&lt;".to_owned();
    _smelt_tmp_9 = str.clone().chars().skip({ let len = str.clone().chars().count() as i64; let index = last_index as i64; if index < 0 { (len + index).clamp(0, len) as usize } else { index.clamp(0, len) as usize } }).take({ let len = str.clone().chars().count() as i64; let index = i as i64; if index < 0 { (len + index).clamp(0, len) as usize } else { index.clamp(0, len) as usize } }.saturating_sub({ let len = str.clone().chars().count() as i64; let index = last_index as i64; if index < 0 { (len + index).clamp(0, len) as usize } else { index.clamp(0, len) as usize } })).collect::<String>();
    _smelt_tmp_10 = _smelt_tmp_9 + &replacement;
    _smelt_tmp_11 = out + &_smelt_tmp_10;
    out = _smelt_tmp_11;
    _smelt_tmp_12 = i + 1.0;
    last_index = _smelt_tmp_12;
    _smelt_tmp_13 = i + 1.0;
    i = _smelt_tmp_13;
    continue;
        }
        62.0 => {
    replacement = "&gt;".to_owned();
    _smelt_tmp_9 = str.clone().chars().skip({ let len = str.clone().chars().count() as i64; let index = last_index as i64; if index < 0 { (len + index).clamp(0, len) as usize } else { index.clamp(0, len) as usize } }).take({ let len = str.clone().chars().count() as i64; let index = i as i64; if index < 0 { (len + index).clamp(0, len) as usize } else { index.clamp(0, len) as usize } }.saturating_sub({ let len = str.clone().chars().count() as i64; let index = last_index as i64; if index < 0 { (len + index).clamp(0, len) as usize } else { index.clamp(0, len) as usize } })).collect::<String>();
    _smelt_tmp_10 = _smelt_tmp_9 + &replacement;
    _smelt_tmp_11 = out + &_smelt_tmp_10;
    out = _smelt_tmp_11;
    _smelt_tmp_12 = i + 1.0;
    last_index = _smelt_tmp_12;
    _smelt_tmp_13 = i + 1.0;
    i = _smelt_tmp_13;
    continue;
        }
        _ => {
    _smelt_tmp_13 = i + 1.0;
    i = _smelt_tmp_13;
    continue;
        }
    }
    }
    _smelt_tmp_14 = str.chars().count() as f64;
    _smelt_tmp_15 = str.clone().chars().skip({ let len = str.clone().chars().count() as i64; let index = last_index as i64; if index < 0 { (len + index).clamp(0, len) as usize } else { index.clamp(0, len) as usize } }).take({ let len = str.clone().chars().count() as i64; let index = _smelt_tmp_14 as i64; if index < 0 { (len + index).clamp(0, len) as usize } else { index.clamp(0, len) as usize } }.saturating_sub({ let len = str.clone().chars().count() as i64; let index = last_index as i64; if index < 0 { (len + index).clamp(0, len) as usize } else { index.clamp(0, len) as usize } })).collect::<String>();
    _smelt_tmp_16 = out + &_smelt_tmp_15;
    return _smelt_tmp_16;
}

pub(crate) fn sum_odd(values: SmeltList<f64>) -> f64 {
    let mut value: f64;
    let mut _smelt_tmp_4: f64;
    let mut _smelt_tmp_5: bool;
    let mut _smelt_tmp_6: f64;
    let mut _smelt_tmp_7: f64;
    let mut total: f64 = 0.0;
    let mut _smelt_tmp_3: f64 = 0.0;
    loop {
    _smelt_tmp_4 = values.len() as f64;
    _smelt_tmp_5 = _smelt_tmp_3 < _smelt_tmp_4;
    if !(_smelt_tmp_5) { break; }
    value = values.borrow().get({ let normalized = _smelt_tmp_3 as i64; usize::try_from(normalized).unwrap_or(usize::MAX) }).cloned().unwrap_or_else(|| 0.0);
    _smelt_tmp_6 = value % 2.0;
    match _smelt_tmp_6 {
        0.0 => {
    _smelt_tmp_3 = _smelt_tmp_3 + 1.0;
    continue;
        }
        _ => {
    _smelt_tmp_7 = total + value;
    total = _smelt_tmp_7;
    _smelt_tmp_3 = _smelt_tmp_3 + 1.0;
    continue;
        }
    }
    }
    return total;
}

pub(crate) fn classify(values: SmeltList<f64>) -> String {
    let mut value: f64;
    let mut _smelt_tmp_4: f64;
    let mut _smelt_tmp_5: bool;
    let mut _smelt_tmp_6: String;
    let mut _smelt_tmp_7: String;
    let mut _smelt_tmp_8: String;
    let mut seen: String = "".to_owned();
    let mut _smelt_tmp_3: f64 = 0.0;
    loop {
    _smelt_tmp_4 = values.len() as f64;
    _smelt_tmp_5 = _smelt_tmp_3 < _smelt_tmp_4;
    if !(_smelt_tmp_5) { break; }
    value = values.borrow().get({ let normalized = _smelt_tmp_3 as i64; usize::try_from(normalized).unwrap_or(usize::MAX) }).cloned().unwrap_or_else(|| 0.0);
    match value {
        1.0 => {
    _smelt_tmp_6 = seen + &"one".to_owned();
    seen = _smelt_tmp_6;
    _smelt_tmp_8 = seen + &".".to_owned();
    seen = _smelt_tmp_8;
    _smelt_tmp_3 = _smelt_tmp_3 + 1.0;
    continue;
        }
        2.0 => {
    _smelt_tmp_3 = _smelt_tmp_3 + 1.0;
    continue;
        }
        _ => {
    _smelt_tmp_7 = seen + &"?".to_owned();
    seen = _smelt_tmp_7;
    _smelt_tmp_8 = seen + &".".to_owned();
    seen = _smelt_tmp_8;
    _smelt_tmp_3 = _smelt_tmp_3 + 1.0;
    continue;
        }
    }
    }
    return seen;
}
