// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

#[path = "source_main.rs"]
mod __smelt_module_source_main;
pub(crate) use __smelt_module_source_main::*;


/// `Number::toString(value, 10)`: JavaScript's number formatting.
///
/// Exponential notation at `n > 21` and `n <= -6`, where `n` is the
/// decimal exponent of the shortest round-trip digit string — which is
/// what Rust's `{:e}` already produces.
fn smelt_number_to_string<N: ::std::borrow::Borrow<f64>>(value: N) -> String {
    let value = *value.borrow();
    if value.is_nan() { return "NaN".to_owned(); }
    if value == 0.0 { return "0".to_owned(); }
    if value < 0.0 { return format!("-{}", smelt_number_to_string(-value)); }
    if value.is_infinite() { return "Infinity".to_owned(); }
    let exponential = format!("{value:e}");
    let (mantissa, exponent) = exponential.split_once('e').unwrap_or((exponential.as_str(), "0"));
    let digits: String = mantissa.chars().filter(char::is_ascii_digit).collect();
    let k = i32::try_from(digits.len()).unwrap_or(i32::MAX);
    let n = exponent.parse::<i32>().unwrap_or(0) + 1;
    if k <= n && n <= 21 {
        let zeros = usize::try_from(n - k).unwrap_or(0);
        return digits + &"0".repeat(zeros);
    }
    if 0 < n && n <= 21 {
        let split = usize::try_from(n).unwrap_or(0);
        return format!("{}.{}", &digits[..split], &digits[split..]);
    }
    if -6 < n && n <= 0 {
        let zeros = usize::try_from(-n).unwrap_or(0);
        return format!("0.{}{}", "0".repeat(zeros), digits);
    }
    let sign = if n - 1 < 0 { '-' } else { '+' };
    let magnitude = (n - 1).abs();
    if k == 1 { return format!("{digits}e{sign}{magnitude}"); }
    format!("{}.{}e{sign}{magnitude}", &digits[..1], &digits[1..])
}

/// `console.log`'s number formatting: the spec's rule, but `-0` prints `-0`.
fn smelt_console_number<N: ::std::borrow::Borrow<f64>>(value: N) -> String { let value = *value.borrow(); if value == 0.0 && value.is_sign_negative() { return "-0".to_owned(); } smelt_number_to_string(value) }

// @smelt:prelude-end — generated program below
fn main() {
    let present_text: Option<String>;
    let missing_count: Option<f64>;
    let present_count: Option<f64>;
    let nothing: ();
    let _smelt_tmp_7: String;
    let _smelt_tmp_9: String;
    let _smelt_tmp_11: String;
    let _smelt_tmp_13: String;
    let _smelt_tmp_15: String;
    let _smelt_tmp_17: String;
    let _smelt_tmp_19: String;
    let _smelt_tmp_20: String;
    let missing_text: Option<String> = None::<String>;
    let _smelt_tmp_5: String = missing_text.clone().map_or_else(|| "undefined".to_owned(), |value| value.to_string());
    let _ = { println!("{}", _smelt_tmp_5); };
    _smelt_tmp_7 = "".to_owned() + &missing_text.unwrap_or_else(|| "undefined".to_owned());
    let _ = { println!("{}", _smelt_tmp_7); };
    present_text = Some("here".to_owned());
    _smelt_tmp_9 = present_text.clone().map_or_else(|| "undefined".to_owned(), |value| value.to_string());
    let _ = { println!("{}", _smelt_tmp_9); };
    _smelt_tmp_11 = "".to_owned() + &present_text.unwrap_or_else(|| "undefined".to_owned());
    let _ = { println!("{}", _smelt_tmp_11); };
    missing_count = None::<f64>;
    _smelt_tmp_13 = "count=".to_owned() + &missing_count.map_or_else(|| "undefined".to_owned(), |value| value.to_string());
    let _ = { println!("{}", _smelt_tmp_13); };
    present_count = Some(3.0);
    _smelt_tmp_15 = "count=".to_owned() + &present_count.map_or_else(|| "undefined".to_owned(), |value| value.to_string());
    let _ = { println!("{}", _smelt_tmp_15); };
    nothing = ();
    _smelt_tmp_17 = "".to_owned() + &"null".to_owned();
    let _ = { println!("{}", _smelt_tmp_17); };
    _smelt_tmp_19 = "".to_owned() + &"null".to_owned();
    _smelt_tmp_20 = "x".to_owned() + &_smelt_tmp_19;
    let _ = { println!("{}", _smelt_tmp_20); };
    let _smelt_tmp_22: String = label("p:".to_owned(), Some("v".to_owned()));
    let _ = { println!("{}", _smelt_tmp_22); };
    let _smelt_tmp_24: String = label("p:".to_owned(), None::<String>);
    let _ = { println!("{}", _smelt_tmp_24); };
    return;
}

// ==== source_main.rs
// @generated by smelt. Do not edit by hand.
// source: <example>/src/main.ts
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

use super::*;

pub(crate) fn label(prefix: String, value: Option<String>) -> String {
    let _smelt_tmp_2: String = prefix.clone() + &value.clone().unwrap_or_else(|| "undefined".to_owned());
    return _smelt_tmp_2;
}
