// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

#[path = "source_main.rs"]
mod __smelt_module_source_main;
pub(crate) use __smelt_module_source_main::*;


// @smelt:prelude-end — generated program below
fn main() {
    let present_text: Option<String>;
    let missing_count: Option<f64>;
    let present_count: Option<f64>;
    let nothing: ();
    let _smelt_tmp_7: String;
    let _smelt_tmp_9: String;
    let _smelt_tmp_11: String;
    let _smelt_tmp_13: String;
    let _smelt_tmp_15: String;
    let _smelt_tmp_17: String;
    let _smelt_tmp_19: String;
    let _smelt_tmp_20: String;
    let missing_text: Option<String> = None::<String>;
    let _smelt_tmp_5: String = missing_text.clone().map_or_else(|| "undefined".to_owned(), |value| value.to_string());
    let _ = { println!("{}", _smelt_tmp_5); };
    _smelt_tmp_7 = "".to_owned() + &missing_text.unwrap_or_else(|| "undefined".to_owned());
    let _ = { println!("{}", _smelt_tmp_7); };
    present_text = Some("here".to_owned());
    _smelt_tmp_9 = present_text.clone().map_or_else(|| "undefined".to_owned(), |value| value.to_string());
    let _ = { println!("{}", _smelt_tmp_9); };
    _smelt_tmp_11 = "".to_owned() + &present_text.unwrap_or_else(|| "undefined".to_owned());
    let _ = { println!("{}", _smelt_tmp_11); };
    missing_count = None::<f64>;
    _smelt_tmp_13 = "count=".to_owned() + &missing_count.map_or_else(|| "undefined".to_owned(), |value| value.to_string());
    let _ = { println!("{}", _smelt_tmp_13); };
    present_count = Some(3.0);
    _smelt_tmp_15 = "count=".to_owned() + &present_count.map_or_else(|| "undefined".to_owned(), |value| value.to_string());
    let _ = { println!("{}", _smelt_tmp_15); };
    nothing = ();
    _smelt_tmp_17 = "".to_owned() + &"null".to_owned();
    let _ = { println!("{}", _smelt_tmp_17); };
    _smelt_tmp_19 = "".to_owned() + &"null".to_owned();
    _smelt_tmp_20 = "x".to_owned() + &_smelt_tmp_19;
    let _ = { println!("{}", _smelt_tmp_20); };
    let _smelt_tmp_22: String = label("p:".to_owned(), Some("v".to_owned()));
    let _ = { println!("{}", _smelt_tmp_22); };
    let _smelt_tmp_24: String = label("p:".to_owned(), None::<String>);
    let _ = { println!("{}", _smelt_tmp_24); };
    return;
}

// ==== source_main.rs
// @generated by smelt. Do not edit by hand.
// source: <example>/src/main.ts
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

use super::*;

pub(crate) fn label(prefix: String, value: Option<String>) -> String {
    let _smelt_tmp_2: String = prefix.clone() + &value.clone().unwrap_or_else(|| "undefined".to_owned());
    return _smelt_tmp_2;
}
