// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

#[path = "source_main.rs"]
mod __smelt_module_source_main;
pub(crate) use __smelt_module_source_main::*;


/// `Number::toString(value, 10)`: JavaScript's number formatting.
///
/// Exponential notation at `n > 21` and `n <= -6`, where `n` is the
/// decimal exponent of the shortest round-trip digit string — which is
/// what Rust's `{:e}` already produces.
fn smelt_number_to_string<N: ::std::borrow::Borrow<f64>>(value: N) -> String {
    let value = *value.borrow();
    if value.is_nan() { return "NaN".to_owned(); }
    if value == 0.0 { return "0".to_owned(); }
    if value < 0.0 { return format!("-{}", smelt_number_to_string(-value)); }
    if value.is_infinite() { return "Infinity".to_owned(); }
    let exponential = format!("{value:e}");
    let (mantissa, exponent) = exponential.split_once('e').unwrap_or((exponential.as_str(), "0"));
    let digits: String = mantissa.chars().filter(char::is_ascii_digit).collect();
    let k = i32::try_from(digits.len()).unwrap_or(i32::MAX);
    let n = exponent.parse::<i32>().unwrap_or(0) + 1;
    if k <= n && n <= 21 {
        let zeros = usize::try_from(n - k).unwrap_or(0);
        return digits + &"0".repeat(zeros);
    }
    if 0 < n && n <= 21 {
        let split = usize::try_from(n).unwrap_or(0);
        return format!("{}.{}", &digits[..split], &digits[split..]);
    }
    if -6 < n && n <= 0 {
        let zeros = usize::try_from(-n).unwrap_or(0);
        return format!("0.{}{}", "0".repeat(zeros), digits);
    }
    let sign = if n - 1 < 0 { '-' } else { '+' };
    let magnitude = (n - 1).abs();
    if k == 1 { return format!("{digits}e{sign}{magnitude}"); }
    format!("{}.{}e{sign}{magnitude}", &digits[..1], &digits[1..])
}

/// `console.log`'s number formatting: the spec's rule, but `-0` prints `-0`.
fn smelt_console_number<N: ::std::borrow::Borrow<f64>>(value: N) -> String { let value = *value.borrow(); if value == 0.0 && value.is_sign_negative() { return "-0".to_owned(); } smelt_number_to_string(value) }

#[derive(Clone)]
#[allow(dead_code)]
struct Reader {
    head: ::std::rc::Rc<dyn Fn() -> f64>,
    tail: ::std::rc::Rc<dyn Fn() -> f64>,
}
impl Default for Reader {
    fn default() -> Self {
        Self {
            head: { let smelt_default_callback: ::std::rc::Rc<dyn Fn() -> f64> = ::std::rc::Rc::new(move || -> f64 { 0.0 }); smelt_default_callback },
            tail: { let smelt_default_callback: ::std::rc::Rc<dyn Fn() -> f64> = ::std::rc::Rc::new(move || -> f64 { 0.0 }); smelt_default_callback },
        }
    }
}
impl ::std::fmt::Debug for Reader {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.debug_struct("Reader").finish_non_exhaustive()
    }
}

#[derive(Clone, Debug, Default, PartialEq)]
struct Body {
}

#[derive(Clone, Debug, Default, PartialEq)]
struct Counter {
}

// @smelt:prelude-end — generated program below

fn main() {
    let body: Body;
    let counter: Counter;
    let _smelt_tmp_2: Body = Body::new();
    body = _smelt_tmp_2;
    let _smelt_tmp_3: String = read(body.clone(), "json".to_owned());
    let _ = { println!("{}", _smelt_tmp_3); };
    let _smelt_tmp_5: String = read(body.clone(), "text".to_owned());
    let _ = { println!("{}", _smelt_tmp_5); };
    let _smelt_tmp_7: String = read(body, "raw".to_owned());
    let _ = { println!("{}", _smelt_tmp_7); };
    let _smelt_tmp_9: Counter = Counter::new();
    counter = _smelt_tmp_9;
    let _smelt_tmp_10: f64 = count(counter.clone(), "head".to_owned());
    let _ = { println!("{}", smelt_console_number(_smelt_tmp_10)); };
    let _smelt_tmp_12: f64 = count(counter, "tail".to_owned());
    let _ = { println!("{}", smelt_console_number(_smelt_tmp_12)); };
    return;
}

impl Body {
    fn new() -> Self {
    let this: Self = Body {  };
    return this;
    }
    fn json(&self) -> String {
    return "json-body".to_owned();
    }
    fn text(&self) -> String {
    return "text-body".to_owned();
    }
    fn raw(&self) -> String {
    return "raw-body".to_owned();
    }
}

impl Counter {
    fn new() -> Self {
    let this: Self = Counter {  };
    return this;
    }
    fn head(&self) -> f64 {
    return 1.0;
    }
    fn tail(&self) -> f64 {
    return 2.0;
    }
}

// ==== source_main.rs
// @generated by smelt. Do not edit by hand.
// source: <example>/src/main.ts
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

use super::*;

pub(crate) fn read(body: Body, key: String) -> String {
    let mut _smelt_tmp_3: String;
    let _smelt_tmp_5: bool;
    let mut _smelt_tmp_6: String;
    let _smelt_tmp_2: bool = key.clone() == "json".to_owned();
    if _smelt_tmp_2 {
    let _smelt_tmp_4: String = body.json();
    _smelt_tmp_3 = _smelt_tmp_4;
    return _smelt_tmp_3;
    } else {
    _smelt_tmp_5 = key.clone() == "text".to_owned();
    if _smelt_tmp_5 {
    let _smelt_tmp_7: String = body.text();
    _smelt_tmp_6 = _smelt_tmp_7;
    _smelt_tmp_3 = _smelt_tmp_6;
    return _smelt_tmp_3;
    } else {
    let _smelt_tmp_8: String = body.raw();
    _smelt_tmp_6 = _smelt_tmp_8;
    _smelt_tmp_3 = _smelt_tmp_6;
    return _smelt_tmp_3;
    }
    }
}

pub(crate) fn count(counter: Counter, key: String) -> f64 {
    let mut _smelt_tmp_3: f64;
    let _smelt_tmp_2: bool = key.clone() == "head".to_owned();
    if _smelt_tmp_2 {
    let _smelt_tmp_4: f64 = counter.head();
    _smelt_tmp_3 = _smelt_tmp_4;
    return _smelt_tmp_3;
    } else {
    let _smelt_tmp_5: f64 = counter.tail();
    _smelt_tmp_3 = _smelt_tmp_5;
    return _smelt_tmp_3;
    }
}
