// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

fn main() {
    let mut x: f64;
    let mut _smelt_tmp_5: f64;
    let mut _smelt_tmp_6: bool;
    let mut _smelt_tmp_7: f64;
    let _smelt_tmp_3: Vec<f64> = vec![1.0, 2.0, 3.0];
    let xs: Vec<f64> = _smelt_tmp_3.clone();
    let mut sum: f64 = 0.0;
    let mut _smelt_tmp_4: f64 = 0.0;
    loop {
    _smelt_tmp_5 = xs.len() as f64;
    _smelt_tmp_6 = _smelt_tmp_4.clone() < _smelt_tmp_5.clone();
    if !(_smelt_tmp_6.clone()) { break; }
    x = xs.get({ let len = xs.len() as i64; let index = _smelt_tmp_4.clone() as i64; let normalized = if index < 0 { len + index } else { index }; usize::try_from(normalized).expect("negative index out of bounds") }).cloned().unwrap_or(0.0).clone();
    _smelt_tmp_7 = sum.clone() + x.clone();
    sum = _smelt_tmp_7.clone();
    _smelt_tmp_4 = _smelt_tmp_4.clone() + 1.0;
    }
    let _ = { println!("{}", sum.clone()); };
    return;
}
