// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

fn main() {
    let _smelt_tmp_2: Vec<f64> = vec![5.0, 8.0, 13.0];
    let values: Vec<f64> = _smelt_tmp_2.clone();
    let _smelt_tmp_3: ::std::collections::HashMap<String, String> = ::std::collections::HashMap::from([("first".to_owned(), "Ada".to_owned()), ("second".to_owned(), "Grace".to_owned())]);
    let names: ::std::collections::HashMap<String, String> = _smelt_tmp_3.clone();
    let _smelt_tmp_4: () = { println!("{} {}", values.get({ let len = values.len() as i64; let index = 1.0 as i64; let normalized = if index < 0 { len + index } else { index }; usize::try_from(normalized).expect("negative index out of bounds") }).cloned().expect("index out of bounds").clone(), names.get(&"second".to_owned().clone()).cloned().expect("index out of bounds").clone()); };
}
