// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

thread_local! {
    static SMELT_NEXT_OBJECT_ID: ::std::cell::Cell<usize> = const { ::std::cell::Cell::new(1) };
}

#[allow(dead_code)]
fn smelt_next_object_id() -> usize {
    SMELT_NEXT_OBJECT_ID.with(|next| { let id = next.get(); next.set(id.saturating_add(1)); id })
}

/// A JavaScript array: a reference identity plus a shared backing buffer.
pub struct SmeltList<T> {
    id: usize,
    values: ::std::rc::Rc<::std::cell::RefCell<Vec<T>>>,
}
impl<T: ::std::fmt::Debug> ::std::fmt::Debug for SmeltList<T> { fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result { self.values.borrow().fmt(formatter) } }
impl<T> Clone for SmeltList<T> { fn clone(&self) -> Self { Self { id: self.id, values: ::std::rc::Rc::clone(&self.values) } } }
#[allow(dead_code)]
impl<T> SmeltList<T> {
    /// Create an identity-bearing typed list with a fresh JS reference identity.
    fn new(values: Vec<T>) -> Self { Self { id: smelt_next_object_id(), values: ::std::rc::Rc::new(::std::cell::RefCell::new(values)) } }
    /// Reuse a caller-supplied identity so an erase/extract round-trip stays `===` equal.
    fn with_id(id: usize, values: Vec<T>) -> Self { Self { id, values: ::std::rc::Rc::new(::std::cell::RefCell::new(values)) } }
    /// Reuse an existing shared buffer, so a re-wrap keeps aliasing the same array.
    fn with_storage(id: usize, values: ::std::rc::Rc<::std::cell::RefCell<Vec<T>>>) -> Self { Self { id, values } }
    /// Another handle on this array's shared buffer.
    fn storage(&self) -> ::std::rc::Rc<::std::cell::RefCell<Vec<T>>> { ::std::rc::Rc::clone(&self.values) }
    /// JS reference identity of this list.
    fn id(&self) -> usize { self.id }
    /// Borrow the backing storage for reading. The guard lives to the end of the
    /// enclosing statement; never pair it with `borrow_mut` in one expression.
    fn borrow(&self) -> ::std::cell::Ref<'_, Vec<T>> { self.values.borrow() }
    /// Borrow the backing storage for writing, through the shared cell — so this
    /// takes `&self`, and every other handle on the array observes the write.
    fn borrow_mut(&self) -> ::std::cell::RefMut<'_, Vec<T>> { self.values.borrow_mut() }
    /// Element count, taking its own short-lived borrow.
    fn len(&self) -> usize { self.values.borrow().len() }
    /// Whether the array holds no elements.
    fn is_empty(&self) -> bool { self.values.borrow().is_empty() }
    /// Replace every element in place, so aliases observe the new contents.
    fn replace_all(&self, values: Vec<T>) { *self.values.borrow_mut() = values; }
}
#[allow(dead_code)]
impl<T: Clone> SmeltList<T> {
    /// A JS array copy (`[...a]`, `slice`): same contents, a NEW identity AND a
    /// new buffer. This is the operation that keeps sharing from over-sharing.
    fn fresh_copy(&self) -> Self { Self::new(self.values.borrow().clone()) }
    /// Snapshot the elements. This COPIES unless this is the last handle, so
    /// mutating the result does not write back.
    fn into_vec(self) -> Vec<T> { match ::std::rc::Rc::try_unwrap(self.values) { Ok(cell) => cell.into_inner(), Err(shared) => shared.borrow().clone() } }
    /// Snapshot the elements without consuming the handle.
    fn to_vec(&self) -> Vec<T> { self.values.borrow().clone() }
    /// Read one element by index, cloned out of the shared buffer (JS `arr[i]`).
    fn get_index(&self, index: usize) -> Option<T> { self.values.borrow().get(index).cloned() }
    /// Set the element at a numeric index, extending with `fill` holes to match JS `arr[i] = v`.
    fn set_index(&self, index: usize, value: T, fill: T) { let mut values = self.values.borrow_mut(); if index >= values.len() { values.resize(index.saturating_add(1), fill); } values[index] = value; }
    /// Iterate a snapshot of the elements, so the buffer is not borrowed across the loop body.
    fn iter(&self) -> ::std::vec::IntoIter<T> { self.values.borrow().clone().into_iter() }
}
impl<T> From<Vec<T>> for SmeltList<T> { fn from(values: Vec<T>) -> Self { Self::new(values) } }
impl<T> ::std::iter::FromIterator<T> for SmeltList<T> { fn from_iter<I: IntoIterator<Item = T>>(iter: I) -> Self { Self::new(iter.into_iter().collect()) } }
impl<T: Clone> IntoIterator for SmeltList<T> { type Item = T; type IntoIter = ::std::vec::IntoIter<T>; fn into_iter(self) -> Self::IntoIter { self.into_vec().into_iter() } }
impl<T: Clone> IntoIterator for &SmeltList<T> { type Item = T; type IntoIter = ::std::vec::IntoIter<T>; fn into_iter(self) -> Self::IntoIter { self.values.borrow().clone().into_iter() } }
impl<T: PartialEq> PartialEq for SmeltList<T> { fn eq(&self, other: &Self) -> bool { *self.values.borrow() == *other.values.borrow() } }
impl<T: PartialEq> Eq for SmeltList<T> {}
impl<T: ::std::hash::Hash> ::std::hash::Hash for SmeltList<T> { fn hash<H: ::std::hash::Hasher>(&self, state: &mut H) { self.values.borrow().hash(state); } }
impl<T> Default for SmeltList<T> { fn default() -> Self { Self::new(Vec::new()) } }
impl<T: Clone> From<SmeltList<T>> for Vec<T> { fn from(list: SmeltList<T>) -> Self { list.into_vec() } }

// @smelt:prelude-end — generated program below
fn main() {
    let _smelt_tmp_2: SmeltList<f64> = Into::<SmeltList<_>>::into(SmeltList::from({ let smelt_list_items: Vec<f64> = vec![5.0, 8.0, 13.0]; smelt_list_items }));
    let values: SmeltList<f64> = Into::<SmeltList<_>>::into(_smelt_tmp_2);
    let _smelt_tmp_3: ::std::collections::HashMap<String, String> = ::std::collections::HashMap::from([("first".to_owned(), "Ada".to_owned()), ("second".to_owned(), "Grace".to_owned())]);
    let names: ::std::collections::HashMap<String, String> = _smelt_tmp_3;
    let _ = { println!("{} {}", values.borrow().get({ let len = values.len() as i64; let index = 1.0 as i64; let normalized = if index < 0 { len + index } else { index }; usize::try_from(normalized).unwrap_or(usize::MAX) }).cloned().unwrap_or_else(|| 0.0), names.get(&"second".to_owned().clone()).cloned().unwrap_or(String::new())); };
    return;
}
