// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

fn main() {
    let source_value: f64 = 7.0;
    let copied_value: f64 = source_value.clone();
    let _ = { println!("{}", source_value.clone()); };
}
