// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

#[path = "source_main.rs"]
mod __smelt_module_source_main;
pub(crate) use __smelt_module_source_main::*;


/// `Number::toString(value, 10)`: JavaScript's number formatting.
///
/// Exponential notation at `n > 21` and `n <= -6`, where `n` is the
/// decimal exponent of the shortest round-trip digit string — which is
/// what Rust's `{:e}` already produces.
fn smelt_number_to_string<N: ::std::borrow::Borrow<f64>>(value: N) -> String {
    let value = *value.borrow();
    if value.is_nan() { return "NaN".to_owned(); }
    if value == 0.0 { return "0".to_owned(); }
    if value < 0.0 { return format!("-{}", smelt_number_to_string(-value)); }
    if value.is_infinite() { return "Infinity".to_owned(); }
    let exponential = format!("{value:e}");
    let (mantissa, exponent) = exponential.split_once('e').unwrap_or((exponential.as_str(), "0"));
    let digits: String = mantissa.chars().filter(char::is_ascii_digit).collect();
    let k = i32::try_from(digits.len()).unwrap_or(i32::MAX);
    let n = exponent.parse::<i32>().unwrap_or(0) + 1;
    if k <= n && n <= 21 {
        let zeros = usize::try_from(n - k).unwrap_or(0);
        return digits + &"0".repeat(zeros);
    }
    if 0 < n && n <= 21 {
        let split = usize::try_from(n).unwrap_or(0);
        return format!("{}.{}", &digits[..split], &digits[split..]);
    }
    if -6 < n && n <= 0 {
        let zeros = usize::try_from(-n).unwrap_or(0);
        return format!("0.{}{}", "0".repeat(zeros), digits);
    }
    let sign = if n - 1 < 0 { '-' } else { '+' };
    let magnitude = (n - 1).abs();
    if k == 1 { return format!("{digits}e{sign}{magnitude}"); }
    format!("{}.{}e{sign}{magnitude}", &digits[..1], &digits[1..])
}

/// `console.log`'s number formatting: the spec's rule, but `-0` prints `-0`.
fn smelt_console_number<N: ::std::borrow::Borrow<f64>>(value: N) -> String { let value = *value.borrow(); if value == 0.0 && value.is_sign_negative() { return "-0".to_owned(); } smelt_number_to_string(value) }

thread_local! {
    static SMELT_NEXT_CAPTURE_SCOPE: ::std::cell::Cell<usize> = const { ::std::cell::Cell::new(1) };
    static SMELT_SHARED_CAPTURES: ::std::cell::RefCell<::std::collections::HashMap<(usize, usize), ::std::rc::Weak<dyn ::std::any::Any>>> = ::std::cell::RefCell::new(::std::collections::HashMap::new());
}

fn smelt_next_capture_scope() -> usize {
    SMELT_NEXT_CAPTURE_SCOPE.with(|next| { let id = next.get(); next.set(id.saturating_add(1)); id })
}

fn smelt_shared_capture<T: Clone + 'static>(scope: usize, slot: *mut T, initial: T) -> ::std::rc::Rc<::std::cell::RefCell<T>> {
    let key = (scope, slot as usize);
    SMELT_SHARED_CAPTURES.with(|captures| {
        let mut captures = captures.borrow_mut();
        if let Some(existing) = captures.get(&key).and_then(::std::rc::Weak::upgrade) {
            return existing.downcast::<::std::cell::RefCell<T>>().expect("shared capture type mismatch");
        }
        let value: ::std::rc::Rc<::std::cell::RefCell<T>> = ::std::rc::Rc::new(::std::cell::RefCell::new(initial));
        let erased: ::std::rc::Rc<dyn ::std::any::Any> = value.clone();
        captures.insert(key, ::std::rc::Rc::downgrade(&erased));
        value
    })
}

// @smelt:prelude-end — generated program below
fn main() {
    let _smelt_tmp_0: f64 = total_down(4.0);
    let _ = { println!("{}", smelt_console_number(_smelt_tmp_0)); };
    let _smelt_tmp_2: String = banner("ab".to_owned(), 3.0);
    let _ = { println!("{}", _smelt_tmp_2); };
    let _smelt_tmp_4: String = trim("done!!!".to_owned());
    let _ = { println!("{}", _smelt_tmp_4); };
    return;
}

// ==== source_main.rs
// @generated by smelt. Do not edit by hand.
// source: <example>/src/main.ts
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

use super::*;

pub(crate) fn total_down(start: f64) -> f64 {
    let smelt_capture_sum_down: ::std::rc::Rc<::std::cell::RefCell<::std::rc::Rc<dyn Fn(f64) -> f64>>> = ::std::rc::Rc::new(::std::cell::RefCell::new({ let smelt_default_callback: ::std::rc::Rc<dyn Fn(f64) -> f64> = ::std::rc::Rc::new(move |arg0: f64| -> f64 { 0.0 }); smelt_default_callback }));
    let _smelt_tmp_2 = ::std::rc::Rc::new({
    let smelt_capture_sum_down = ::std::rc::Rc::downgrade(&smelt_capture_sum_down);
    move |closure_arg_0: f64| {
    let _smelt_tmp_3: f64;
    let _smelt_tmp_4: f64;
    let _smelt_tmp_5: f64;
    let _smelt_tmp_2: bool = closure_arg_0 <= 0.0;
    if _smelt_tmp_2 {
    0.0
    } else {
    _smelt_tmp_3 = closure_arg_0 - 1.0;
    _smelt_tmp_4 = ((*smelt_capture_sum_down.upgrade().expect("self-recursive closure called after its defining scope returned").borrow()))(_smelt_tmp_3);
    _smelt_tmp_5 = closure_arg_0 + _smelt_tmp_4;
    _smelt_tmp_5
    }
    }
});
    (*smelt_capture_sum_down.borrow_mut()) = _smelt_tmp_2.clone();
    let _smelt_tmp_3: f64 = { let smelt_callable = ::std::clone::Clone::clone(&(*smelt_capture_sum_down.borrow())); (smelt_callable)(start) };
    return _smelt_tmp_3;
}

pub(crate) fn banner(text: String, times: f64) -> String {
    let smelt_capture_repeat: ::std::rc::Rc<::std::cell::RefCell<::std::rc::Rc<dyn Fn(f64, String) -> String>>> = ::std::rc::Rc::new(::std::cell::RefCell::new({ let smelt_default_callback: ::std::rc::Rc<dyn Fn(f64, String) -> String> = ::std::rc::Rc::new(move |arg0: f64, arg1: String| -> String { String::new() }); smelt_default_callback }));
    let _smelt_tmp_3 = ::std::rc::Rc::new({
    let text = text.clone();
    let smelt_capture_repeat = ::std::rc::Rc::downgrade(&smelt_capture_repeat);
    move |closure_arg_0: f64, closure_arg_1: String| {
    let mut _smelt_tmp_5: String;
    let _smelt_tmp_6: f64;
    let _smelt_tmp_7: String;
    let _smelt_tmp_8: String;
    let _smelt_tmp_4: bool = closure_arg_0 <= 0.0;
    if _smelt_tmp_4 {
    _smelt_tmp_5 = closure_arg_1.clone();
    } else {
    _smelt_tmp_6 = closure_arg_0 - 1.0;
    _smelt_tmp_7 = closure_arg_1.clone() + &text.clone();
    _smelt_tmp_8 = ((*smelt_capture_repeat.upgrade().expect("self-recursive closure called after its defining scope returned").borrow()))(_smelt_tmp_6, _smelt_tmp_7.clone());
    _smelt_tmp_5 = _smelt_tmp_8.clone();
    }
    _smelt_tmp_5.clone()
    }
});
    (*smelt_capture_repeat.borrow_mut()) = _smelt_tmp_3.clone();
    let _smelt_tmp_4: String = { let smelt_callable = ::std::clone::Clone::clone(&(*smelt_capture_repeat.borrow())); (smelt_callable)(times, "".to_owned()) };
    return _smelt_tmp_4;
}

pub(crate) fn trim(label: String) -> String {
    let smelt_capture_strip: ::std::rc::Rc<::std::cell::RefCell<::std::rc::Rc<dyn Fn(String) -> String>>> = ::std::rc::Rc::new(::std::cell::RefCell::new({ let smelt_default_callback: ::std::rc::Rc<dyn Fn(String) -> String> = ::std::rc::Rc::new(move |arg0: String| -> String { String::new() }); smelt_default_callback }));
    let suffix: String = "!".to_owned();
    let _smelt_tmp_3 = ::std::rc::Rc::new({
    let smelt_capture_strip = ::std::rc::Rc::downgrade(&smelt_capture_strip);
    let suffix = suffix.clone();
    move |closure_arg_0: String| {
    let _smelt_tmp_7: f64;
    let _smelt_tmp_8: f64;
    let _smelt_tmp_9: String;
    let _smelt_tmp_10: String;
    let _smelt_tmp_3: String = closure_arg_0.clone();
    let _smelt_tmp_4: String = suffix.clone();
    let _smelt_tmp_5: bool = _smelt_tmp_3.clone().ends_with(&_smelt_tmp_4.clone());
    let _smelt_tmp_6: bool = !(_smelt_tmp_5);
    if _smelt_tmp_6 {
    closure_arg_0.clone()
    } else {
    _smelt_tmp_7 = closure_arg_0.chars().count() as f64;
    _smelt_tmp_8 = _smelt_tmp_7 - 1.0;
    _smelt_tmp_9 = closure_arg_0.clone().chars().skip({ let smelt_len = closure_arg_0.clone().chars().count() as i64; let smelt_index = 0.0 as i64; if smelt_index < 0 { (smelt_len + smelt_index).clamp(0, smelt_len) as usize } else { smelt_index.clamp(0, smelt_len) as usize } }).take({ let smelt_len = closure_arg_0.clone().chars().count() as i64; let smelt_index = _smelt_tmp_8 as i64; if smelt_index < 0 { (smelt_len + smelt_index).clamp(0, smelt_len) as usize } else { smelt_index.clamp(0, smelt_len) as usize } }.saturating_sub({ let smelt_len = closure_arg_0.clone().chars().count() as i64; let smelt_index = 0.0 as i64; if smelt_index < 0 { (smelt_len + smelt_index).clamp(0, smelt_len) as usize } else { smelt_index.clamp(0, smelt_len) as usize } })).collect::<String>();
    _smelt_tmp_10 = ((*smelt_capture_strip.upgrade().expect("self-recursive closure called after its defining scope returned").borrow()))(_smelt_tmp_9.clone());
    _smelt_tmp_10.clone()
    }
    }
});
    (*smelt_capture_strip.borrow_mut()) = _smelt_tmp_3.clone();
    let _smelt_tmp_4: String = { let smelt_callable = ::std::clone::Clone::clone(&(*smelt_capture_strip.borrow())); (smelt_callable)(label.clone()) };
    return _smelt_tmp_4;
}
