// @generated by smelt. Do not edit by hand.
#![allow(dead_code, unused_variables)]

fn main() {
    let _smelt_tmp_1: ::std::collections::HashMap<String, f64> = ::std::collections::HashMap::from([("ada".to_owned(), 10.0), ("grace".to_owned(), 20.0)]);
    let scores: ::std::collections::HashMap<String, f64> = _smelt_tmp_1.clone();
    let _smelt_tmp_2: () = { println!("{}", scores.get("ada").cloned().expect("missing field").clone()); };
}
