// @generated by smelt. Do not edit by hand.
#![allow(dead_code, unused_variables)]

fn main() {
    let ready: bool = true;
    let blocked: bool = false;
    let _smelt_tmp_3: f64 = -3.0;
    let value: f64 = _smelt_tmp_3.clone();
    let _smelt_tmp_4: bool = !blocked.clone();
    let _smelt_tmp_5: bool = _smelt_tmp_4.clone() && ready.clone();
    let _smelt_tmp_6: bool = _smelt_tmp_5.clone() || false;
    let _smelt_tmp_7: () = { println!("{} {}", _smelt_tmp_6.clone(), value.clone()); };
}
