// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

#[derive(Clone, Debug, Default)]
struct Box {
    value: String,
}


fn main() {
    let mut box_: Box;
    let mut _smelt_tmp_1: Box = Box::new("ok".to_owned());
    box_ = _smelt_tmp_1.clone();
    let _ = { println!("{}", box_.value.clone()); };
    return;
}

impl Box {
    fn new(value: String) -> Self {
    let mut this: Self = Box { value: String::new() };
    this.value = value.clone();
    return this;
    }
}
