// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

#[path = "source_main.rs"]
mod __smelt_module_source_main;
pub(crate) use __smelt_module_source_main::*;


/// `Number::toString(value, 10)`: JavaScript's number formatting.
///
/// Exponential notation at `n > 21` and `n <= -6`, where `n` is the
/// decimal exponent of the shortest round-trip digit string — which is
/// what Rust's `{:e}` already produces.
fn smelt_number_to_string<N: ::std::borrow::Borrow<f64>>(value: N) -> String {
    let value = *value.borrow();
    if value.is_nan() { return "NaN".to_owned(); }
    if value == 0.0 { return "0".to_owned(); }
    if value < 0.0 { return format!("-{}", smelt_number_to_string(-value)); }
    if value.is_infinite() { return "Infinity".to_owned(); }
    let exponential = format!("{value:e}");
    let (mantissa, exponent) = exponential.split_once('e').unwrap_or((exponential.as_str(), "0"));
    let digits: String = mantissa.chars().filter(char::is_ascii_digit).collect();
    let k = i32::try_from(digits.len()).unwrap_or(i32::MAX);
    let n = exponent.parse::<i32>().unwrap_or(0) + 1;
    if k <= n && n <= 21 {
        let zeros = usize::try_from(n - k).unwrap_or(0);
        return digits + &"0".repeat(zeros);
    }
    if 0 < n && n <= 21 {
        let split = usize::try_from(n).unwrap_or(0);
        return format!("{}.{}", &digits[..split], &digits[split..]);
    }
    if -6 < n && n <= 0 {
        let zeros = usize::try_from(-n).unwrap_or(0);
        return format!("0.{}{}", "0".repeat(zeros), digits);
    }
    let sign = if n - 1 < 0 { '-' } else { '+' };
    let magnitude = (n - 1).abs();
    if k == 1 { return format!("{digits}e{sign}{magnitude}"); }
    format!("{}.{}e{sign}{magnitude}", &digits[..1], &digits[1..])
}

/// `console.log`'s number formatting: the spec's rule, but `-0` prints `-0`.
fn smelt_console_number<N: ::std::borrow::Borrow<f64>>(value: N) -> String { let value = *value.borrow(); if value == 0.0 && value.is_sign_negative() { return "-0".to_owned(); } smelt_number_to_string(value) }

/// A Smelt `throw` crossing an unwind boundary, keeping its class.
#[derive(Debug)]
struct SmeltPanic { class: String, message: String }
impl ::std::fmt::Display for SmeltPanic { fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result { write!(formatter, "{}: {}", self.class, self.message) } }
static SMELT_PANIC_HOOK: ::std::sync::Once = ::std::sync::Once::new();
/// Silence the panic report for Smelt-thrown payloads only.
fn smelt_install_panic_hook() { SMELT_PANIC_HOOK.call_once(|| { let previous = ::std::panic::take_hook(); ::std::panic::set_hook(Box::new(move |info| { if info.payload().downcast_ref::<SmeltPanic>().is_some() { return; } previous(info); })); }); }
/// Report a Smelt error through the panic channel, keeping its identity.
fn smelt_panic_throw(error: Box<dyn ::std::error::Error>) -> ! { smelt_install_panic_hook(); ::std::panic::panic_any(smelt_panic_payload(&*error)) }
/// Recover the message text a `catch` observes from a caught panic.
fn smelt_panic_message(panic: &(dyn ::std::any::Any + Send)) -> String { if let Some(payload) = panic.downcast_ref::<SmeltPanic>() { return payload.message.clone(); } if let Some(message) = panic.downcast_ref::<String>() { return message.clone(); } if let Some(message) = panic.downcast_ref::<&'static str>() { return (*message).to_owned(); } "JavaScript exception".to_owned() }
/// Recover the error class a `catch` observes from a caught panic.
fn smelt_panic_class(panic: &(dyn ::std::any::Any + Send)) -> String { panic.downcast_ref::<SmeltPanic>().map_or_else(|| "Error".to_owned(), |payload| payload.class.clone()) }
/// Build the unwind payload for a crate with no erased values.
fn smelt_panic_payload(error: &(dyn ::std::error::Error + 'static)) -> SmeltPanic { SmeltPanic { class: "Error".to_owned(), message: error.to_string() } }
/// JavaScript `Math.round`: a tie rounds toward +∞, not away from zero.
fn smelt_math_round(value: f64) -> f64 { let floor = value.floor(); let rounded = if value - floor >= 0.5 { floor + 1.0 } else { floor }; if rounded == 0.0 && value.is_sign_negative() { -0.0 } else { rounded } }

thread_local! {
    static SMELT_NEXT_OBJECT_ID: ::std::cell::Cell<usize> = const { ::std::cell::Cell::new(1) };
}

#[allow(dead_code)]
fn smelt_next_object_id() -> usize {
    SMELT_NEXT_OBJECT_ID.with(|next| { let id = next.get(); next.set(id.saturating_add(1)); id })
}

/// A JavaScript array: a reference identity plus a shared backing buffer.
pub struct SmeltList<T> {
    id: usize,
    values: ::std::rc::Rc<::std::cell::RefCell<Vec<T>>>,
}
impl<T: ::std::fmt::Debug> ::std::fmt::Debug for SmeltList<T> { fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result { self.values.borrow().fmt(formatter) } }
impl<T> Clone for SmeltList<T> { fn clone(&self) -> Self { Self { id: self.id, values: ::std::rc::Rc::clone(&self.values) } } }
#[allow(dead_code)]
impl<T> SmeltList<T> {
    /// Create an identity-bearing typed list with a fresh JS reference identity.
    fn new(values: Vec<T>) -> Self { Self { id: smelt_next_object_id(), values: ::std::rc::Rc::new(::std::cell::RefCell::new(values)) } }
    /// Reuse a caller-supplied identity so an erase/extract round-trip stays `===` equal.
    fn with_id(id: usize, values: Vec<T>) -> Self { Self { id, values: ::std::rc::Rc::new(::std::cell::RefCell::new(values)) } }
    /// Reuse an existing shared buffer, so a re-wrap keeps aliasing the same array.
    fn with_storage(id: usize, values: ::std::rc::Rc<::std::cell::RefCell<Vec<T>>>) -> Self { Self { id, values } }
    /// Another handle on this array's shared buffer.
    fn storage(&self) -> ::std::rc::Rc<::std::cell::RefCell<Vec<T>>> { ::std::rc::Rc::clone(&self.values) }
    /// JS reference identity of this list.
    fn id(&self) -> usize { self.id }
    /// Borrow the backing storage for reading. The guard lives to the end of the
    /// enclosing statement; never pair it with `borrow_mut` in one expression.
    fn borrow(&self) -> ::std::cell::Ref<'_, Vec<T>> { self.values.borrow() }
    /// Borrow the backing storage for writing, through the shared cell — so this
    /// takes `&self`, and every other handle on the array observes the write.
    fn borrow_mut(&self) -> ::std::cell::RefMut<'_, Vec<T>> { self.values.borrow_mut() }
    /// Element count, taking its own short-lived borrow.
    fn len(&self) -> usize { self.values.borrow().len() }
    /// Whether the array holds no elements.
    fn is_empty(&self) -> bool { self.values.borrow().is_empty() }
    /// Replace every element in place, so aliases observe the new contents.
    fn replace_all(&self, values: Vec<T>) { *self.values.borrow_mut() = values; }
}
#[allow(dead_code)]
impl<T: Clone> SmeltList<T> {
    /// A JS array copy (`[...a]`, `slice`): same contents, a NEW identity AND a
    /// new buffer. This is the operation that keeps sharing from over-sharing.
    fn fresh_copy(&self) -> Self { Self::new(self.values.borrow().clone()) }
    /// Snapshot the elements. This COPIES unless this is the last handle, so
    /// mutating the result does not write back.
    fn into_vec(self) -> Vec<T> { match ::std::rc::Rc::try_unwrap(self.values) { Ok(cell) => cell.into_inner(), Err(shared) => shared.borrow().clone() } }
    /// Snapshot the elements without consuming the handle.
    fn to_vec(&self) -> Vec<T> { self.values.borrow().clone() }
    /// Read one element by index, cloned out of the shared buffer (JS `arr[i]`).
    fn get_index(&self, index: usize) -> Option<T> { self.values.borrow().get(index).cloned() }
    /// Set the element at a numeric index, extending with `fill` holes to match JS `arr[i] = v`.
    fn set_index(&self, index: usize, value: T, fill: T) { let mut values = self.values.borrow_mut(); if index >= values.len() { values.resize(index.saturating_add(1), fill); } values[index] = value; }
    /// Iterate a snapshot of the elements, so the buffer is not borrowed across the loop body.
    fn iter(&self) -> ::std::vec::IntoIter<T> { self.values.borrow().clone().into_iter() }
}
impl<T> From<Vec<T>> for SmeltList<T> { fn from(values: Vec<T>) -> Self { Self::new(values) } }
impl<T> ::std::iter::FromIterator<T> for SmeltList<T> { fn from_iter<I: IntoIterator<Item = T>>(iter: I) -> Self { Self::new(iter.into_iter().collect()) } }
impl<T: Clone> IntoIterator for SmeltList<T> { type Item = T; type IntoIter = ::std::vec::IntoIter<T>; fn into_iter(self) -> Self::IntoIter { self.into_vec().into_iter() } }
impl<T: Clone> IntoIterator for &SmeltList<T> { type Item = T; type IntoIter = ::std::vec::IntoIter<T>; fn into_iter(self) -> Self::IntoIter { self.values.borrow().clone().into_iter() } }
impl<T: PartialEq> PartialEq for SmeltList<T> { fn eq(&self, other: &Self) -> bool { *self.values.borrow() == *other.values.borrow() } }
impl<T: PartialEq> Eq for SmeltList<T> {}
impl<T: ::std::hash::Hash> ::std::hash::Hash for SmeltList<T> { fn hash<H: ::std::hash::Hasher>(&self, state: &mut H) { self.values.borrow().hash(state); } }
impl<T> Default for SmeltList<T> { fn default() -> Self { Self::new(Vec::new()) } }
impl<T: Clone> From<SmeltList<T>> for Vec<T> { fn from(list: SmeltList<T>) -> Self { list.into_vec() } }

#[derive(Clone)]
#[allow(dead_code)]
struct Shape {
    name: String,
    area: ::std::rc::Rc<dyn Fn() -> f64>,
    tag: ::std::rc::Rc<dyn Fn(String) -> String>,
}
impl Default for Shape {
    fn default() -> Self {
        Self {
            name: String::new(),
            area: { let smelt_default_callback: ::std::rc::Rc<dyn Fn() -> f64> = ::std::rc::Rc::new(move || -> f64 { 0.0 }); smelt_default_callback },
            tag: { let smelt_default_callback: ::std::rc::Rc<dyn Fn(String) -> String> = ::std::rc::Rc::new(move |arg0: String| -> String { String::new() }); smelt_default_callback },
        }
    }
}
impl ::std::fmt::Debug for Shape {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.debug_struct("Shape").finish_non_exhaustive()
    }
}

#[allow(dead_code)]
struct Square(::std::rc::Rc<::std::cell::RefCell<SquareInner>>);
#[derive(Debug, Default)]
#[allow(dead_code)]
struct SquareInner {
    name: String,
    tagged: f64,
    side: f64,
}
impl Clone for Square {
    fn clone(&self) -> Self {
        Square(::std::rc::Rc::clone(&self.0))
    }
}
impl PartialEq for Square {
    fn eq(&self, other: &Self) -> bool {
        ::std::rc::Rc::ptr_eq(&self.0, &other.0)
    }
}
impl Default for Square {
    fn default() -> Self {
        Square(::std::rc::Rc::new(::std::cell::RefCell::new(SquareInner::default())))
    }
}
impl ::std::fmt::Debug for Square {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::std::fmt::Debug::fmt(&*self.0.borrow(), formatter)
    }
}

#[allow(dead_code)]
struct Circle(::std::rc::Rc<::std::cell::RefCell<CircleInner>>);
#[derive(Debug, Default)]
#[allow(dead_code)]
struct CircleInner {
    radius: f64,
    name: String,
    tagged: f64,
}
impl Clone for Circle {
    fn clone(&self) -> Self {
        Circle(::std::rc::Rc::clone(&self.0))
    }
}
impl PartialEq for Circle {
    fn eq(&self, other: &Self) -> bool {
        ::std::rc::Rc::ptr_eq(&self.0, &other.0)
    }
}
impl Default for Circle {
    fn default() -> Self {
        Circle(::std::rc::Rc::new(::std::cell::RefCell::new(CircleInner::default())))
    }
}
impl ::std::fmt::Debug for Circle {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::std::fmt::Debug::fmt(&*self.0.borrow(), formatter)
    }
}

// @smelt:prelude-end — generated program below

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let square: Square;
    let shapes: SmeltList<Shape>;
    let mut shape: Shape;
    let _smelt_tmp_5: SmeltList<Shape>;
    let mut _smelt_tmp_6: f64;
    let mut _smelt_tmp_7: f64;
    let mut _smelt_tmp_8: bool;
    let mut _smelt_tmp_15: ::std::rc::Rc<dyn Fn() -> Shape> = { let smelt_default_callback: ::std::rc::Rc<dyn Fn() -> Shape> = ::std::rc::Rc::new(move || -> Shape { Default::default() }); smelt_default_callback };
    let mut _smelt_tmp_16: ::std::collections::HashMap<String, ::std::rc::Rc<dyn Fn() -> Shape>> = ::std::collections::HashMap::new();
    let mut _smelt_tmp_18: ::std::rc::Rc<dyn Fn() -> Shape> = { let smelt_default_callback: ::std::rc::Rc<dyn Fn() -> Shape> = ::std::rc::Rc::new(move || -> Shape { Default::default() }); smelt_default_callback };
    let mut _smelt_tmp_19: ::std::collections::HashMap<String, ::std::rc::Rc<dyn Fn() -> Shape>> = ::std::collections::HashMap::new();
    let _smelt_tmp_3: Square = Square::new(3.0);
    square = _smelt_tmp_3;
    let _smelt_tmp_4: Circle = Circle::new(2.0);
    _smelt_tmp_5 = Into::<SmeltList<_>>::into(SmeltList::from({ let smelt_list_items: Vec<Shape> = vec![{ let smelt_struct_value = square.clone().clone(); Shape { name: smelt_struct_value.0.borrow().name.clone(), area: { let smelt_virtual_receiver = smelt_struct_value.clone(); let smelt_virtual_method: ::std::rc::Rc<dyn Fn() -> f64> = ::std::rc::Rc::new(move || -> f64 { let smelt_method_receiver = smelt_virtual_receiver.clone(); smelt_method_receiver.area() }); smelt_virtual_method }, tag: { let smelt_virtual_receiver = smelt_struct_value.clone(); let smelt_virtual_method: ::std::rc::Rc<dyn Fn(String) -> String> = ::std::rc::Rc::new(move |arg0: String| -> String { let mut smelt_method_receiver = smelt_virtual_receiver.clone(); smelt_method_receiver.tag(arg0.clone()) }); smelt_virtual_method } } }, { let smelt_struct_value = _smelt_tmp_4.clone().clone(); Shape { name: smelt_struct_value.0.borrow().name.clone(), area: { let smelt_virtual_receiver = smelt_struct_value.clone(); let smelt_virtual_method: ::std::rc::Rc<dyn Fn() -> f64> = ::std::rc::Rc::new(move || -> f64 { let smelt_method_receiver = smelt_virtual_receiver.clone(); smelt_method_receiver.area() }); smelt_virtual_method }, tag: { let smelt_virtual_receiver = smelt_struct_value.clone(); let smelt_virtual_method: ::std::rc::Rc<dyn Fn(String) -> String> = ::std::rc::Rc::new(move |arg0: String| -> String { let mut smelt_method_receiver = smelt_virtual_receiver.clone(); smelt_method_receiver.tag(arg0.clone()) }); smelt_virtual_method } } }]; smelt_list_items }));
    shapes = Into::<SmeltList<_>>::into(_smelt_tmp_5);
    _smelt_tmp_6 = 0.0;
    loop {
    _smelt_tmp_7 = shapes.len() as f64;
    _smelt_tmp_8 = _smelt_tmp_6 < _smelt_tmp_7;
    if !(_smelt_tmp_8) { break; }
    shape = shapes.borrow().get({ let smelt_normalized = _smelt_tmp_6 as i64; usize::try_from(smelt_normalized).unwrap_or(usize::MAX) }).cloned().unwrap_or_else(|| Default::default());
    let _smelt_tmp_9: String = describe(shape)?;
    let _ = { println!("{}", _smelt_tmp_9); };
    _smelt_tmp_6 = _smelt_tmp_6 + 1.0;
    }
    let _smelt_tmp_11: Square = Square::new(5.0);
    let _smelt_tmp_12: String = describe({ let smelt_struct_value = _smelt_tmp_11.clone(); Shape { name: smelt_struct_value.0.borrow().name.clone(), area: { let smelt_virtual_receiver = smelt_struct_value.clone(); let smelt_virtual_method: ::std::rc::Rc<dyn Fn() -> f64> = ::std::rc::Rc::new(move || -> f64 { let smelt_method_receiver = smelt_virtual_receiver.clone(); smelt_method_receiver.area() }); smelt_virtual_method }, tag: { let smelt_virtual_receiver = smelt_struct_value.clone(); let smelt_virtual_method: ::std::rc::Rc<dyn Fn(String) -> String> = ::std::rc::Rc::new(move |arg0: String| -> String { let mut smelt_method_receiver = smelt_virtual_receiver.clone(); smelt_method_receiver.tag(arg0.clone()) }); smelt_virtual_method } } })?;
    let _ = { println!("{}", _smelt_tmp_12); };
    let _ = { println!("{} {}", "square tagged".to_owned(), smelt_console_number(square.0.borrow().tagged.clone())); };
    _smelt_tmp_15 = ::std::rc::Rc::new(|| {
    let _smelt_tmp_0: Square = Square::new(4.0);
    { let smelt_struct_value = _smelt_tmp_0.clone().clone(); Shape { name: smelt_struct_value.0.borrow().name.clone(), area: { let smelt_virtual_receiver = smelt_struct_value.clone(); let smelt_virtual_method: ::std::rc::Rc<dyn Fn() -> f64> = ::std::rc::Rc::new(move || -> f64 { let smelt_method_receiver = smelt_virtual_receiver.clone(); smelt_method_receiver.area() }); smelt_virtual_method }, tag: { let smelt_virtual_receiver = smelt_struct_value.clone(); let smelt_virtual_method: ::std::rc::Rc<dyn Fn(String) -> String> = ::std::rc::Rc::new(move |arg0: String| -> String { let mut smelt_method_receiver = smelt_virtual_receiver.clone(); smelt_method_receiver.tag(arg0.clone()) }); smelt_virtual_method } } }
    });
    _smelt_tmp_16 = ::std::collections::HashMap::from([("make".to_owned(), { let smelt_fn: ::std::rc::Rc<dyn Fn() -> Shape> = _smelt_tmp_15.clone(); smelt_fn })]);
    let _ = run_suite(_smelt_tmp_16)?;
    _smelt_tmp_18 = ::std::rc::Rc::new(|| {
    let _smelt_tmp_0: Circle = Circle::new(1.0);
    { let smelt_struct_value = _smelt_tmp_0.clone().clone(); Shape { name: smelt_struct_value.0.borrow().name.clone(), area: { let smelt_virtual_receiver = smelt_struct_value.clone(); let smelt_virtual_method: ::std::rc::Rc<dyn Fn() -> f64> = ::std::rc::Rc::new(move || -> f64 { let smelt_method_receiver = smelt_virtual_receiver.clone(); smelt_method_receiver.area() }); smelt_virtual_method }, tag: { let smelt_virtual_receiver = smelt_struct_value.clone(); let smelt_virtual_method: ::std::rc::Rc<dyn Fn(String) -> String> = ::std::rc::Rc::new(move |arg0: String| -> String { let mut smelt_method_receiver = smelt_virtual_receiver.clone(); smelt_method_receiver.tag(arg0.clone()) }); smelt_virtual_method } } }
    });
    _smelt_tmp_19 = ::std::collections::HashMap::from([("make".to_owned(), { let smelt_fn: ::std::rc::Rc<dyn Fn() -> Shape> = _smelt_tmp_18.clone(); smelt_fn })]);
    let _ = run_suite(_smelt_tmp_19)?;
    return Ok(());
}

impl Square {
    fn new(side: f64) -> Self {
    let mut this: Self = Square(::std::rc::Rc::new(::std::cell::RefCell::new(SquareInner { name: String::new(), tagged: 0.0, side: 0.0 })));
    this.0.borrow_mut().name = "square".to_owned();
    this.0.borrow_mut().tagged = 0.0;
    this.0.borrow_mut().side = side;
    return this;
    }
    fn area(&self) -> f64 {
    let _smelt_tmp_1: f64 = self.0.borrow().side.clone() * self.0.borrow().side.clone();
    return _smelt_tmp_1;
    }
    fn tag(&self, label: String) -> String {
    let _smelt_tmp_2: f64 = self.0.borrow().tagged.clone() + 1.0;
    self.0.borrow_mut().tagged = _smelt_tmp_2;
    return label.clone();
    }
}

impl Circle {
    fn new(radius: f64) -> Self {
    let mut this: Self = Circle(::std::rc::Rc::new(::std::cell::RefCell::new(CircleInner { radius: 0.0, name: String::new(), tagged: 0.0 })));
    this.0.borrow_mut().name = "circle".to_owned();
    this.0.borrow_mut().tagged = 0.0;
    this.0.borrow_mut().radius = radius;
    return this;
    }
    fn area(&self) -> f64 {
    let _smelt_tmp_1: f64 = 3.141592653589793 * self.0.borrow().radius.clone();
    let _smelt_tmp_2: f64 = _smelt_tmp_1 * self.0.borrow().radius.clone();
    let _smelt_tmp_3: f64 = smelt_math_round(_smelt_tmp_2);
    return _smelt_tmp_3;
    }
    fn tag(&self, label: String) -> String {
    let _smelt_tmp_2: f64 = self.0.borrow().tagged.clone() + 2.0;
    self.0.borrow_mut().tagged = _smelt_tmp_2;
    return label.clone();
    }
}

// ==== source_main.rs
// @generated by smelt. Do not edit by hand.
// source: <example>/src/main.ts
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

use super::*;

pub(crate) fn describe(shape: Shape) -> Result<String, Box<dyn std::error::Error>> {
    let _smelt_tmp_1: String = "".to_owned() + &shape.name.clone();
    let _smelt_tmp_2: String = _smelt_tmp_1 + &" area=".to_owned();
    let _smelt_tmp_3: f64 = (shape.area.clone())();
    let _smelt_tmp_4: String = _smelt_tmp_2 + &smelt_number_to_string(_smelt_tmp_3);
    let _smelt_tmp_5: String = _smelt_tmp_4 + &" ".to_owned();
    let _smelt_tmp_6: String = (shape.tag.clone())("x".to_owned());
    let _smelt_tmp_7: String = _smelt_tmp_5 + &_smelt_tmp_6;
    return Ok(_smelt_tmp_7);
}

pub(crate) fn run_suite(__param0: ::std::collections::HashMap<String, ::std::rc::Rc<dyn Fn() -> Shape>>) -> Result<(), Box<dyn std::error::Error>> {
    let make = __param0.get(&"make".to_owned()).cloned().expect("missing field").clone();
    let _smelt_tmp_3: Shape = (make)();
    let shape: Shape = _smelt_tmp_3;
    let _smelt_tmp_4: f64 = (shape.area.clone())();
    let _smelt_tmp_5: String = (shape.tag.clone())("suite".to_owned());
    let _ = { println!("{} {} {}", shape.name.clone(), smelt_console_number(_smelt_tmp_4), _smelt_tmp_5); };
    return Ok(());
}
