// Generated by smelt. Do not edit.

export declare function requestId(prefix: string): (string, () => Promise<void>) => Promise<void>;
export declare function countdown(n: number): number;
export type Next = () => Promise<void>;
export type Handler = (string, () => Promise<void>) => Promise<void>;
export declare function run(): Promise<void>;
