// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

/// `Number::toString(value, 10)`: JavaScript's number formatting.
///
/// Exponential notation at `n > 21` and `n <= -6`, where `n` is the
/// decimal exponent of the shortest round-trip digit string — which is
/// what Rust's `{:e}` already produces.
fn smelt_number_to_string<N: ::std::borrow::Borrow<f64>>(value: N) -> String {
    let value = *value.borrow();
    if value.is_nan() { return "NaN".to_owned(); }
    if value == 0.0 { return "0".to_owned(); }
    if value < 0.0 { return format!("-{}", smelt_number_to_string(-value)); }
    if value.is_infinite() { return "Infinity".to_owned(); }
    let exponential = format!("{value:e}");
    let (mantissa, exponent) = exponential.split_once('e').unwrap_or((exponential.as_str(), "0"));
    let digits: String = mantissa.chars().filter(char::is_ascii_digit).collect();
    let k = i32::try_from(digits.len()).unwrap_or(i32::MAX);
    let n = exponent.parse::<i32>().unwrap_or(0) + 1;
    if k <= n && n <= 21 {
        let zeros = usize::try_from(n - k).unwrap_or(0);
        return digits + &"0".repeat(zeros);
    }
    if 0 < n && n <= 21 {
        let split = usize::try_from(n).unwrap_or(0);
        return format!("{}.{}", &digits[..split], &digits[split..]);
    }
    if -6 < n && n <= 0 {
        let zeros = usize::try_from(-n).unwrap_or(0);
        return format!("0.{}{}", "0".repeat(zeros), digits);
    }
    let sign = if n - 1 < 0 { '-' } else { '+' };
    let magnitude = (n - 1).abs();
    if k == 1 { return format!("{digits}e{sign}{magnitude}"); }
    format!("{}.{}e{sign}{magnitude}", &digits[..1], &digits[1..])
}

/// `console.log`'s number formatting: the spec's rule, but `-0` prints `-0`.
fn smelt_console_number<N: ::std::borrow::Borrow<f64>>(value: N) -> String { let value = *value.borrow(); if value == 0.0 && value.is_sign_negative() { return "-0".to_owned(); } smelt_number_to_string(value) }

#[allow(dead_code)]
struct Registry(::std::rc::Rc<::std::cell::RefCell<RegistryInner>>);
#[derive(Debug, Default)]
#[allow(dead_code)]
struct RegistryInner {
    public_log: String,
    private_log: String,
}
impl Clone for Registry {
    fn clone(&self) -> Self {
        Registry(::std::rc::Rc::clone(&self.0))
    }
}
impl PartialEq for Registry {
    fn eq(&self, other: &Self) -> bool {
        ::std::rc::Rc::ptr_eq(&self.0, &other.0)
    }
}
impl Default for Registry {
    fn default() -> Self {
        Registry(::std::rc::Rc::new(::std::cell::RefCell::new(RegistryInner::default())))
    }
}
impl ::std::fmt::Debug for Registry {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::std::fmt::Debug::fmt(&*self.0.borrow(), formatter)
    }
}

// @smelt:prelude-end — generated program below

fn main() {
    let registry: Registry;
    let _smelt_tmp_4: String;
    let _smelt_tmp_5: String;
    let _smelt_tmp_1: Registry = Registry::new();
    registry = _smelt_tmp_1;
    let _ = registry.add("a".to_owned());
    let _ = registry.add("b".to_owned());
    _smelt_tmp_4 = registry.0.borrow().private_log.clone().clone() + &",".to_owned();
    _smelt_tmp_5 = _smelt_tmp_4 + &registry.0.borrow().public_log.clone().clone();
    let _ = { println!("{}", _smelt_tmp_5); };
    return;
}

impl Registry {
    fn new() -> Self {
    let mut this: Self = Registry(::std::rc::Rc::new(::std::cell::RefCell::new(RegistryInner { public_log: String::new(), private_log: String::new() })));
    this.0.borrow_mut().public_log = "".to_owned();
    this.0.borrow_mut().private_log = "".to_owned();
    return this;
    }
    fn stash(&self, value: String) -> () {
    let _smelt_tmp_2: String = self.0.borrow().private_log.clone().clone() + &value.clone();
    self.0.borrow_mut().private_log = _smelt_tmp_2;
    return;
    }
    fn keep(&self, value: String) -> () {
    let _smelt_tmp_2: String = self.0.borrow().public_log.clone().clone() + &value.clone();
    self.0.borrow_mut().public_log = _smelt_tmp_2;
    return;
    }
    fn add(&self, value: String) -> () {
    let _ = self.stash(value.clone());
    let _ = self.keep(value.clone());
    return;
    }
}
