// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

#[allow(dead_code)]
struct Registry(::std::rc::Rc<::std::cell::RefCell<RegistryInner>>);
#[derive(Debug, Default)]
#[allow(dead_code)]
struct RegistryInner {
    public_log: String,
    private_log: String,
}
impl Clone for Registry {
    fn clone(&self) -> Self {
        Registry(::std::rc::Rc::clone(&self.0))
    }
}
impl PartialEq for Registry {
    fn eq(&self, other: &Self) -> bool {
        ::std::rc::Rc::ptr_eq(&self.0, &other.0)
    }
}
impl Default for Registry {
    fn default() -> Self {
        Registry(::std::rc::Rc::new(::std::cell::RefCell::new(RegistryInner::default())))
    }
}
impl ::std::fmt::Debug for Registry {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::std::fmt::Debug::fmt(&*self.0.borrow(), formatter)
    }
}

// @smelt:prelude-end — generated program below

fn main() {
    let registry: Registry;
    let _smelt_tmp_4: String;
    let _smelt_tmp_5: String;
    let _smelt_tmp_1: Registry = Registry::new();
    registry = _smelt_tmp_1;
    let _ = registry.add("a".to_owned());
    let _ = registry.add("b".to_owned());
    _smelt_tmp_4 = registry.0.borrow().private_log.clone().clone() + &",".to_owned();
    _smelt_tmp_5 = _smelt_tmp_4 + &registry.0.borrow().public_log.clone().clone();
    let _ = { println!("{}", _smelt_tmp_5); };
    return;
}

impl Registry {
    fn new() -> Self {
    let mut this: Self = Registry(::std::rc::Rc::new(::std::cell::RefCell::new(RegistryInner { public_log: String::new(), private_log: String::new() })));
    this.0.borrow_mut().public_log = "".to_owned();
    this.0.borrow_mut().private_log = "".to_owned();
    return this;
    }
    fn stash(&self, value: String) -> () {
    let _smelt_tmp_2: String = self.0.borrow().private_log.clone().clone() + &value.clone();
    self.0.borrow_mut().private_log = _smelt_tmp_2;
    return;
    }
    fn keep(&self, value: String) -> () {
    let _smelt_tmp_2: String = self.0.borrow().public_log.clone().clone() + &value.clone();
    self.0.borrow_mut().public_log = _smelt_tmp_2;
    return;
    }
    fn add(&self, value: String) -> () {
    let _ = self.stash(value.clone());
    let _ = self.keep(value.clone());
    return;
    }
}
