// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

#[derive(Clone, Debug, Default)]
struct User {
    first: String,
    last: String,
}


fn main() {
    let mut _smelt_tmp_1: User = User::new("Ada".to_owned(), "Lovelace".to_owned());
    let mut user: User = _smelt_tmp_1.clone();
    let _smelt_tmp_2: String = user.label();
    let _smelt_tmp_3: () = { println!("{}", _smelt_tmp_2.clone()); };
}

impl User {
    fn new(first: String, last: String) -> Self {
    let mut this: Self = User { first: String::new(), last: String::new() };
    this.first = first.clone();
    this.last = last.clone();
    return this;
    }
    fn label(&self) -> String {
    let _smelt_tmp_1: String = self.first.clone() + &self.last.clone();
    return _smelt_tmp_1.clone();
    }
}
