// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

/// `Number::toString(value, 10)`: JavaScript's number formatting.
///
/// Exponential notation at `n > 21` and `n <= -6`, where `n` is the
/// decimal exponent of the shortest round-trip digit string — which is
/// what Rust's `{:e}` already produces.
fn smelt_number_to_string<N: ::std::borrow::Borrow<f64>>(value: N) -> String {
    let value = *value.borrow();
    if value.is_nan() { return "NaN".to_owned(); }
    if value == 0.0 { return "0".to_owned(); }
    if value < 0.0 { return format!("-{}", smelt_number_to_string(-value)); }
    if value.is_infinite() { return "Infinity".to_owned(); }
    let exponential = format!("{value:e}");
    let (mantissa, exponent) = exponential.split_once('e').unwrap_or((exponential.as_str(), "0"));
    let digits: String = mantissa.chars().filter(char::is_ascii_digit).collect();
    let k = i32::try_from(digits.len()).unwrap_or(i32::MAX);
    let n = exponent.parse::<i32>().unwrap_or(0) + 1;
    if k <= n && n <= 21 {
        let zeros = usize::try_from(n - k).unwrap_or(0);
        return digits + &"0".repeat(zeros);
    }
    if 0 < n && n <= 21 {
        let split = usize::try_from(n).unwrap_or(0);
        return format!("{}.{}", &digits[..split], &digits[split..]);
    }
    if -6 < n && n <= 0 {
        let zeros = usize::try_from(-n).unwrap_or(0);
        return format!("0.{}{}", "0".repeat(zeros), digits);
    }
    let sign = if n - 1 < 0 { '-' } else { '+' };
    let magnitude = (n - 1).abs();
    if k == 1 { return format!("{digits}e{sign}{magnitude}"); }
    format!("{}.{}e{sign}{magnitude}", &digits[..1], &digits[1..])
}

/// `console.log`'s number formatting: the spec's rule, but `-0` prints `-0`.
fn smelt_console_number<N: ::std::borrow::Borrow<f64>>(value: N) -> String { let value = *value.borrow(); if value == 0.0 && value.is_sign_negative() { return "-0".to_owned(); } smelt_number_to_string(value) }

thread_local! {
    static SMELT_NEXT_OBJECT_ID: ::std::cell::Cell<usize> = const { ::std::cell::Cell::new(1) };
}

#[allow(dead_code)]
fn smelt_next_object_id() -> usize {
    SMELT_NEXT_OBJECT_ID.with(|next| { let id = next.get(); next.set(id.saturating_add(1)); id })
}

/// A JavaScript array: a reference identity plus a shared backing buffer.
pub struct SmeltList<T> {
    id: usize,
    values: ::std::rc::Rc<::std::cell::RefCell<Vec<T>>>,
}
impl<T: ::std::fmt::Debug> ::std::fmt::Debug for SmeltList<T> { fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result { self.values.borrow().fmt(formatter) } }
impl<T> Clone for SmeltList<T> { fn clone(&self) -> Self { Self { id: self.id, values: ::std::rc::Rc::clone(&self.values) } } }
#[allow(dead_code)]
impl<T> SmeltList<T> {
    /// Create an identity-bearing typed list with a fresh JS reference identity.
    fn new(values: Vec<T>) -> Self { Self { id: smelt_next_object_id(), values: ::std::rc::Rc::new(::std::cell::RefCell::new(values)) } }
    /// Reuse a caller-supplied identity so an erase/extract round-trip stays `===` equal.
    fn with_id(id: usize, values: Vec<T>) -> Self { Self { id, values: ::std::rc::Rc::new(::std::cell::RefCell::new(values)) } }
    /// Reuse an existing shared buffer, so a re-wrap keeps aliasing the same array.
    fn with_storage(id: usize, values: ::std::rc::Rc<::std::cell::RefCell<Vec<T>>>) -> Self { Self { id, values } }
    /// Another handle on this array's shared buffer.
    fn storage(&self) -> ::std::rc::Rc<::std::cell::RefCell<Vec<T>>> { ::std::rc::Rc::clone(&self.values) }
    /// JS reference identity of this list.
    fn id(&self) -> usize { self.id }
    /// Borrow the backing storage for reading. The guard lives to the end of the
    /// enclosing statement; never pair it with `borrow_mut` in one expression.
    fn borrow(&self) -> ::std::cell::Ref<'_, Vec<T>> { self.values.borrow() }
    /// Borrow the backing storage for writing, through the shared cell — so this
    /// takes `&self`, and every other handle on the array observes the write.
    fn borrow_mut(&self) -> ::std::cell::RefMut<'_, Vec<T>> { self.values.borrow_mut() }
    /// Element count, taking its own short-lived borrow.
    fn len(&self) -> usize { self.values.borrow().len() }
    /// Whether the array holds no elements.
    fn is_empty(&self) -> bool { self.values.borrow().is_empty() }
    /// Replace every element in place, so aliases observe the new contents.
    fn replace_all(&self, values: Vec<T>) { *self.values.borrow_mut() = values; }
}
#[allow(dead_code)]
impl<T: Clone> SmeltList<T> {
    /// A JS array copy (`[...a]`, `slice`): same contents, a NEW identity AND a
    /// new buffer. This is the operation that keeps sharing from over-sharing.
    fn fresh_copy(&self) -> Self { Self::new(self.values.borrow().clone()) }
    /// Snapshot the elements. This COPIES unless this is the last handle, so
    /// mutating the result does not write back.
    fn into_vec(self) -> Vec<T> { match ::std::rc::Rc::try_unwrap(self.values) { Ok(cell) => cell.into_inner(), Err(shared) => shared.borrow().clone() } }
    /// Snapshot the elements without consuming the handle.
    fn to_vec(&self) -> Vec<T> { self.values.borrow().clone() }
    /// Read one element by index, cloned out of the shared buffer (JS `arr[i]`).
    fn get_index(&self, index: usize) -> Option<T> { self.values.borrow().get(index).cloned() }
    /// Set the element at a numeric index, extending with `fill` holes to match JS `arr[i] = v`.
    fn set_index(&self, index: usize, value: T, fill: T) { let mut values = self.values.borrow_mut(); if index >= values.len() { values.resize(index.saturating_add(1), fill); } values[index] = value; }
    /// Iterate a snapshot of the elements, so the buffer is not borrowed across the loop body.
    fn iter(&self) -> ::std::vec::IntoIter<T> { self.values.borrow().clone().into_iter() }
}
impl<T> From<Vec<T>> for SmeltList<T> { fn from(values: Vec<T>) -> Self { Self::new(values) } }
impl<T> ::std::iter::FromIterator<T> for SmeltList<T> { fn from_iter<I: IntoIterator<Item = T>>(iter: I) -> Self { Self::new(iter.into_iter().collect()) } }
impl<T: Clone> IntoIterator for SmeltList<T> { type Item = T; type IntoIter = ::std::vec::IntoIter<T>; fn into_iter(self) -> Self::IntoIter { self.into_vec().into_iter() } }
impl<T: Clone> IntoIterator for &SmeltList<T> { type Item = T; type IntoIter = ::std::vec::IntoIter<T>; fn into_iter(self) -> Self::IntoIter { self.values.borrow().clone().into_iter() } }
impl<T: PartialEq> PartialEq for SmeltList<T> { fn eq(&self, other: &Self) -> bool { *self.values.borrow() == *other.values.borrow() } }
impl<T: PartialEq> Eq for SmeltList<T> {}
impl<T: ::std::hash::Hash> ::std::hash::Hash for SmeltList<T> { fn hash<H: ::std::hash::Hasher>(&self, state: &mut H) { self.values.borrow().hash(state); } }
impl<T> Default for SmeltList<T> { fn default() -> Self { Self::new(Vec::new()) } }
impl<T: Clone> From<SmeltList<T>> for Vec<T> { fn from(list: SmeltList<T>) -> Self { list.into_vec() } }

#[derive(Debug, Clone)]
pub struct SmeltPrimSetStore<T> {
    entries: Vec<T>,
    index: ::std::collections::HashSet<T>,
}

pub struct SmeltPrimSet<T> {
    id: usize,
    store: ::std::rc::Rc<SmeltPrimSetStore<T>>,
}

impl<T> SmeltPrimSet<T> {
    fn new() -> Self { Self::with_id(smelt_next_object_id()) }
    fn with_id(id: usize) -> Self { Self { id, store: ::std::rc::Rc::new(SmeltPrimSetStore { entries: Vec::new(), index: ::std::collections::HashSet::new() }) } }
    fn len(&self) -> usize { self.store.entries.len() }
    fn is_empty(&self) -> bool { self.store.entries.is_empty() }
    fn iter(&self) -> ::std::slice::Iter<'_, T> { self.store.entries.iter() }
}

impl<T: Clone + ::std::cmp::Eq + ::std::hash::Hash> SmeltPrimSet<T> {
    fn store_mut(&mut self) -> &mut SmeltPrimSetStore<T> { ::std::rc::Rc::make_mut(&mut self.store) }
    fn contains(&self, value: &T) -> bool { self.store.index.contains(value) }
    fn insert(&mut self, value: T) -> bool { if self.store.index.contains(&value) { return false; } let store = self.store_mut(); store.index.insert(value.clone()); store.entries.push(value); true }
    fn remove(&mut self, value: &T) -> bool { if !self.store.index.contains(value) { return false; } let store = self.store_mut(); store.index.remove(value); store.entries.retain(|entry| entry != value); true }
    fn clear(&mut self) { let store = self.store_mut(); store.entries.clear(); store.index.clear(); }
    fn extend<I: IntoIterator<Item = T>>(&mut self, iter: I) { for value in iter { self.insert(value); } }
    fn is_disjoint(&self, other: &Self) -> bool { self.store.entries.iter().all(|value| !other.contains(value)) }
    fn is_subset(&self, other: &Self) -> bool { self.store.entries.iter().all(|value| other.contains(value)) }
    fn is_superset(&self, other: &Self) -> bool { other.is_subset(self) }
    fn union<'smelt_set>(&'smelt_set self, other: &'smelt_set Self) -> ::std::vec::IntoIter<&'smelt_set T> { let mut out: Vec<&T> = self.store.entries.iter().collect(); out.extend(other.store.entries.iter().filter(|value| !self.contains(value))); out.into_iter() }
    fn intersection<'smelt_set>(&'smelt_set self, other: &'smelt_set Self) -> ::std::vec::IntoIter<&'smelt_set T> { self.store.entries.iter().filter(|value| other.contains(value)).collect::<Vec<_>>().into_iter() }
    fn difference<'smelt_set>(&'smelt_set self, other: &'smelt_set Self) -> ::std::vec::IntoIter<&'smelt_set T> { self.store.entries.iter().filter(|value| !other.contains(value)).collect::<Vec<_>>().into_iter() }
    fn symmetric_difference<'smelt_set>(&'smelt_set self, other: &'smelt_set Self) -> ::std::vec::IntoIter<&'smelt_set T> { let mut out: Vec<&T> = self.store.entries.iter().filter(|value| !other.contains(value)).collect(); for value in other.store.entries.iter() { if !self.contains(value) { out.push(value); } } out.into_iter() }
}

impl<T> Clone for SmeltPrimSet<T> { fn clone(&self) -> Self { Self { id: self.id, store: self.store.clone() } } }
impl<T: ::std::fmt::Debug> ::std::fmt::Debug for SmeltPrimSet<T> { fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result { formatter.debug_struct("SmeltPrimSet").field("id", &self.id).field("entries", &self.store.entries).finish() } }
impl<T> Default for SmeltPrimSet<T> { fn default() -> Self { Self::new() } }
impl<T: Clone + ::std::cmp::Eq + ::std::hash::Hash, const N: usize> From<[T; N]> for SmeltPrimSet<T> { fn from(values: [T; N]) -> Self { values.into_iter().collect() } }
impl<T: Clone + ::std::cmp::Eq + ::std::hash::Hash> ::std::iter::FromIterator<T> for SmeltPrimSet<T> { fn from_iter<I: IntoIterator<Item = T>>(iter: I) -> Self { let mut set = Self::new(); set.extend(iter); set } }
impl<T: Clone> IntoIterator for SmeltPrimSet<T> { type Item = T; type IntoIter = ::std::vec::IntoIter<T>; fn into_iter(self) -> Self::IntoIter { match ::std::rc::Rc::try_unwrap(self.store) { Ok(store) => store.entries.into_iter(), Err(store) => store.entries.clone().into_iter() } } }
impl<'smelt_set, T> IntoIterator for &'smelt_set SmeltPrimSet<T> { type Item = &'smelt_set T; type IntoIter = ::std::slice::Iter<'smelt_set, T>; fn into_iter(self) -> Self::IntoIter { self.store.entries.iter() } }
impl<T: Clone + ::std::cmp::Eq + ::std::hash::Hash> PartialEq for SmeltPrimSet<T> { fn eq(&self, other: &Self) -> bool { self.store.entries.len() == other.store.entries.len() && self.store.entries.iter().all(|value| other.contains(value)) } }

// @smelt:prelude-end — generated program below
fn main() {
    let repeated: SmeltPrimSet<String>;
    let from_array: SmeltPrimSet<String>;
    let copied: SmeltPrimSet<String>;
    let direct: SmeltPrimSet<String>;
    let via_spread: SmeltPrimSet<String>;
    let _smelt_tmp_10: bool;
    let _smelt_tmp_12: bool;
    let _smelt_tmp_14: bool;
    let _smelt_tmp_16: bool;
    let _smelt_tmp_18: SmeltList<String>;
    let _smelt_tmp_19: String;
    let _smelt_tmp_21: SmeltList<String>;
    let _smelt_tmp_22: SmeltPrimSet<String>;
    let _smelt_tmp_23: f64;
    let _smelt_tmp_25: SmeltList<String>;
    let _smelt_tmp_26: String;
    let _smelt_tmp_28: bool;
    let _smelt_tmp_30: SmeltPrimSet<String>;
    let _smelt_tmp_31: f64;
    let _smelt_tmp_33: SmeltList<String>;
    let _smelt_tmp_34: String;
    let _smelt_tmp_36: SmeltPrimSet<String>;
    let _smelt_tmp_37: f64;
    let _smelt_tmp_39: SmeltList<String>;
    let _smelt_tmp_40: String;
    let _smelt_tmp_42: SmeltList<String>;
    let _smelt_tmp_43: SmeltPrimSet<String>;
    let _smelt_tmp_44: SmeltList<String>;
    let _smelt_tmp_45: SmeltPrimSet<String>;
    let _smelt_tmp_46: SmeltList<String>;
    let _smelt_tmp_47: String;
    let _smelt_tmp_49: SmeltList<String>;
    let _smelt_tmp_50: String;
    let _smelt_tmp_51: SmeltList<String>;
    let _smelt_tmp_52: String;
    let _smelt_tmp_53: bool;
    let _smelt_tmp_6: SmeltList<String> = Into::<SmeltList<_>>::into(".\\+*[^]$()".to_owned().chars().map(|ch| ch.to_string()).collect::<Vec<_>>());
    let _smelt_tmp_7: SmeltPrimSet<String> = _smelt_tmp_6.borrow().iter().cloned().collect::<SmeltPrimSet<_>>();
    let reg_exp_meta_chars: SmeltPrimSet<String> = _smelt_tmp_7;
    let _smelt_tmp_8: f64 = reg_exp_meta_chars.len() as f64;
    let _ = { println!("{}", smelt_console_number(_smelt_tmp_8)); };
    _smelt_tmp_10 = reg_exp_meta_chars.clone().contains(&"*".to_owned());
    let _ = { println!("{}", _smelt_tmp_10); };
    _smelt_tmp_12 = reg_exp_meta_chars.clone().contains(&"$".to_owned());
    let _ = { println!("{}", _smelt_tmp_12); };
    _smelt_tmp_14 = reg_exp_meta_chars.clone().contains(&"(".to_owned());
    let _ = { println!("{}", _smelt_tmp_14); };
    _smelt_tmp_16 = reg_exp_meta_chars.clone().contains(&"a".to_owned());
    let _ = { println!("{}", _smelt_tmp_16); };
    _smelt_tmp_18 = Into::<SmeltList<_>>::into(reg_exp_meta_chars.iter().cloned().collect::<Vec<_>>());
    _smelt_tmp_19 = _smelt_tmp_18.borrow().join(&"".to_owned());
    let _ = { println!("{}", _smelt_tmp_19); };
    _smelt_tmp_21 = Into::<SmeltList<_>>::into("aabbcc".to_owned().chars().map(|ch| ch.to_string()).collect::<Vec<_>>());
    _smelt_tmp_22 = _smelt_tmp_21.borrow().iter().cloned().collect::<SmeltPrimSet<_>>();
    repeated = _smelt_tmp_22;
    _smelt_tmp_23 = repeated.len() as f64;
    let _ = { println!("{}", smelt_console_number(_smelt_tmp_23)); };
    _smelt_tmp_25 = Into::<SmeltList<_>>::into(repeated.iter().cloned().collect::<Vec<_>>());
    _smelt_tmp_26 = _smelt_tmp_25.borrow().join(&"|".to_owned());
    let _ = { println!("{}", _smelt_tmp_26); };
    _smelt_tmp_28 = repeated.contains(&"d".to_owned());
    let _ = { println!("{}", _smelt_tmp_28); };
    _smelt_tmp_30 = SmeltPrimSet::from(["c".to_owned(), "a".to_owned(), "b".to_owned(), "a".to_owned()]);
    from_array = _smelt_tmp_30;
    _smelt_tmp_31 = from_array.len() as f64;
    let _ = { println!("{}", smelt_console_number(_smelt_tmp_31)); };
    _smelt_tmp_33 = Into::<SmeltList<_>>::into(from_array.iter().cloned().collect::<Vec<_>>());
    _smelt_tmp_34 = _smelt_tmp_33.borrow().join(&"|".to_owned());
    let _ = { println!("{}", _smelt_tmp_34); };
    _smelt_tmp_36 = from_array.clone();
    copied = from_array;
    _smelt_tmp_37 = copied.len() as f64;
    let _ = { println!("{}", smelt_console_number(_smelt_tmp_37)); };
    _smelt_tmp_39 = Into::<SmeltList<_>>::into(copied.iter().cloned().collect::<Vec<_>>());
    _smelt_tmp_40 = _smelt_tmp_39.borrow().join(&"|".to_owned());
    let _ = { println!("{}", _smelt_tmp_40); };
    _smelt_tmp_42 = Into::<SmeltList<_>>::into("hello".to_owned().chars().map(|ch| ch.to_string()).collect::<Vec<_>>());
    _smelt_tmp_43 = _smelt_tmp_42.borrow().iter().cloned().collect::<SmeltPrimSet<_>>();
    direct = _smelt_tmp_43;
    _smelt_tmp_44 = Into::<SmeltList<_>>::into("hello".to_owned().chars().map(|ch| ch.to_string()).collect::<Vec<_>>());
    _smelt_tmp_45 = _smelt_tmp_44.borrow().iter().cloned().collect::<SmeltPrimSet<_>>();
    via_spread = _smelt_tmp_45;
    _smelt_tmp_46 = Into::<SmeltList<_>>::into(direct.iter().cloned().collect::<Vec<_>>());
    _smelt_tmp_47 = _smelt_tmp_46.borrow().join(&"|".to_owned());
    let _ = { println!("{}", _smelt_tmp_47); };
    _smelt_tmp_49 = Into::<SmeltList<_>>::into(direct.iter().cloned().collect::<Vec<_>>());
    _smelt_tmp_50 = _smelt_tmp_49.borrow().join(&"|".to_owned());
    _smelt_tmp_51 = Into::<SmeltList<_>>::into(via_spread.iter().cloned().collect::<Vec<_>>());
    _smelt_tmp_52 = _smelt_tmp_51.borrow().join(&"|".to_owned());
    _smelt_tmp_53 = _smelt_tmp_50 == _smelt_tmp_52;
    let _ = { println!("{}", _smelt_tmp_53); };
    return;
}
