// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

#[path = "source_main.rs"]
mod __smelt_module_source_main;
pub(crate) use __smelt_module_source_main::*;


/// `Number::toString(value, 10)`: JavaScript's number formatting.
///
/// Exponential notation at `n > 21` and `n <= -6`, where `n` is the
/// decimal exponent of the shortest round-trip digit string — which is
/// what Rust's `{:e}` already produces.
fn smelt_number_to_string<N: ::std::borrow::Borrow<f64>>(value: N) -> String {
    let value = *value.borrow();
    if value.is_nan() { return "NaN".to_owned(); }
    if value == 0.0 { return "0".to_owned(); }
    if value < 0.0 { return format!("-{}", smelt_number_to_string(-value)); }
    if value.is_infinite() { return "Infinity".to_owned(); }
    let exponential = format!("{value:e}");
    let (mantissa, exponent) = exponential.split_once('e').unwrap_or((exponential.as_str(), "0"));
    let digits: String = mantissa.chars().filter(char::is_ascii_digit).collect();
    let k = i32::try_from(digits.len()).unwrap_or(i32::MAX);
    let n = exponent.parse::<i32>().unwrap_or(0) + 1;
    if k <= n && n <= 21 {
        let zeros = usize::try_from(n - k).unwrap_or(0);
        return digits + &"0".repeat(zeros);
    }
    if 0 < n && n <= 21 {
        let split = usize::try_from(n).unwrap_or(0);
        return format!("{}.{}", &digits[..split], &digits[split..]);
    }
    if -6 < n && n <= 0 {
        let zeros = usize::try_from(-n).unwrap_or(0);
        return format!("0.{}{}", "0".repeat(zeros), digits);
    }
    let sign = if n - 1 < 0 { '-' } else { '+' };
    let magnitude = (n - 1).abs();
    if k == 1 { return format!("{digits}e{sign}{magnitude}"); }
    format!("{}.{}e{sign}{magnitude}", &digits[..1], &digits[1..])
}

/// `console.log`'s number formatting: the spec's rule, but `-0` prints `-0`.
fn smelt_console_number<N: ::std::borrow::Borrow<f64>>(value: N) -> String { let value = *value.borrow(); if value == 0.0 && value.is_sign_negative() { return "-0".to_owned(); } smelt_number_to_string(value) }

/// A Smelt `throw` crossing an unwind boundary, keeping its class.
#[derive(Debug)]
struct SmeltPanic { class: String, message: String }
impl ::std::fmt::Display for SmeltPanic { fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result { write!(formatter, "{}: {}", self.class, self.message) } }
static SMELT_PANIC_HOOK: ::std::sync::Once = ::std::sync::Once::new();
/// Silence the panic report for Smelt-thrown payloads only.
fn smelt_install_panic_hook() { SMELT_PANIC_HOOK.call_once(|| { let previous = ::std::panic::take_hook(); ::std::panic::set_hook(Box::new(move |info| { if info.payload().downcast_ref::<SmeltPanic>().is_some() { return; } previous(info); })); }); }
/// Report a Smelt error through the panic channel, keeping its identity.
fn smelt_panic_throw(error: Box<dyn ::std::error::Error>) -> ! { smelt_install_panic_hook(); ::std::panic::panic_any(smelt_panic_payload(&*error)) }
/// Recover the message text a `catch` observes from a caught panic.
fn smelt_panic_message(panic: &(dyn ::std::any::Any + Send)) -> String { if let Some(payload) = panic.downcast_ref::<SmeltPanic>() { return payload.message.clone(); } if let Some(message) = panic.downcast_ref::<String>() { return message.clone(); } if let Some(message) = panic.downcast_ref::<&'static str>() { return (*message).to_owned(); } "JavaScript exception".to_owned() }
/// Recover the error class a `catch` observes from a caught panic.
fn smelt_panic_class(panic: &(dyn ::std::any::Any + Send)) -> String { panic.downcast_ref::<SmeltPanic>().map_or_else(|| "Error".to_owned(), |payload| payload.class.clone()) }
/// Build the unwind payload for a crate with no erased values.
fn smelt_panic_payload(error: &(dyn ::std::error::Error + 'static)) -> SmeltPanic { SmeltPanic { class: "Error".to_owned(), message: error.to_string() } }
#[derive(Clone)]
#[allow(dead_code)]
struct Animal {
    name: String,
    legs: f64,
    speak: ::std::rc::Rc<dyn Fn() -> String>,
}
impl Default for Animal {
    fn default() -> Self {
        Self {
            name: String::new(),
            legs: 0.0,
            speak: { let smelt_default_callback: ::std::rc::Rc<dyn Fn() -> String> = ::std::rc::Rc::new(move || -> String { String::new() }); smelt_default_callback },
        }
    }
}
impl ::std::fmt::Debug for Animal {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.debug_struct("Animal").finish_non_exhaustive()
    }
}

#[derive(Clone)]
#[allow(dead_code)]
struct Dog {
    name: String,
    legs: f64,
    speak: ::std::rc::Rc<dyn Fn() -> String>,
    breed: String,
}
impl Default for Dog {
    fn default() -> Self {
        Self {
            name: String::new(),
            legs: 0.0,
            speak: { let smelt_default_callback: ::std::rc::Rc<dyn Fn() -> String> = ::std::rc::Rc::new(move || -> String { String::new() }); smelt_default_callback },
            breed: String::new(),
        }
    }
}
impl ::std::fmt::Debug for Dog {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.debug_struct("Dog").finish_non_exhaustive()
    }
}

#[allow(dead_code)]
struct Counter(::std::rc::Rc<::std::cell::RefCell<CounterInner>>);
#[allow(dead_code)]
struct CounterInner {
    count: f64,
    label: ::std::rc::Rc<dyn Fn() -> String>,
}
impl Default for CounterInner {
    fn default() -> Self {
        Self {
            count: 0.0,
            label: { let smelt_default_callback: ::std::rc::Rc<dyn Fn() -> String> = ::std::rc::Rc::new(move || -> String { String::new() }); smelt_default_callback },
        }
    }
}
impl ::std::fmt::Debug for CounterInner {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.debug_struct("CounterInner").finish_non_exhaustive()
    }
}
impl Clone for Counter {
    fn clone(&self) -> Self {
        Counter(::std::rc::Rc::clone(&self.0))
    }
}
impl PartialEq for Counter {
    fn eq(&self, other: &Self) -> bool {
        ::std::rc::Rc::ptr_eq(&self.0, &other.0)
    }
}
impl Default for Counter {
    fn default() -> Self {
        Counter(::std::rc::Rc::new(::std::cell::RefCell::new(CounterInner::default())))
    }
}
impl ::std::fmt::Debug for Counter {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::std::fmt::Debug::fmt(&*self.0.borrow(), formatter)
    }
}

#[allow(dead_code)]
struct NamedCounter(::std::rc::Rc<::std::cell::RefCell<NamedCounterInner>>);
#[allow(dead_code)]
struct NamedCounterInner {
    count: f64,
    label: ::std::rc::Rc<dyn Fn() -> String>,
    title: String,
}
impl Default for NamedCounterInner {
    fn default() -> Self {
        Self {
            count: 0.0,
            label: { let smelt_default_callback: ::std::rc::Rc<dyn Fn() -> String> = ::std::rc::Rc::new(move || -> String { String::new() }); smelt_default_callback },
            title: String::new(),
        }
    }
}
impl ::std::fmt::Debug for NamedCounterInner {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.debug_struct("NamedCounterInner").finish_non_exhaustive()
    }
}
impl Clone for NamedCounter {
    fn clone(&self) -> Self {
        NamedCounter(::std::rc::Rc::clone(&self.0))
    }
}
impl PartialEq for NamedCounter {
    fn eq(&self, other: &Self) -> bool {
        ::std::rc::Rc::ptr_eq(&self.0, &other.0)
    }
}
impl Default for NamedCounter {
    fn default() -> Self {
        NamedCounter(::std::rc::Rc::new(::std::cell::RefCell::new(NamedCounterInner::default())))
    }
}
impl ::std::fmt::Debug for NamedCounter {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::std::fmt::Debug::fmt(&*self.0.borrow(), formatter)
    }
}

// @smelt:prelude-end — generated program below

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let generic: Animal;
    let dog: Dog;
    let plain: Counter;
    let named: NamedCounter;
    let _smelt_tmp_4: Animal = Animal::new("Snake".to_owned(), 0.0);
    generic = _smelt_tmp_4;
    let _smelt_tmp_5: Dog = Dog::new("Rex".to_owned(), "beagle".to_owned());
    dog = _smelt_tmp_5;
    let _smelt_tmp_6: String = introduce(generic)?;
    let _ = { println!("{}", _smelt_tmp_6); };
    let _smelt_tmp_8: String = introduce({ let smelt_struct_value = dog.clone().clone(); Animal { name: smelt_struct_value.name.clone(), legs: smelt_struct_value.legs.clone(), speak: { let smelt_virtual_receiver = smelt_struct_value.clone(); let smelt_virtual_method: ::std::rc::Rc<dyn Fn() -> String> = ::std::rc::Rc::new(move || -> String { let smelt_method_receiver = smelt_virtual_receiver.clone(); smelt_method_receiver.speak() }); smelt_virtual_method } } })?;
    let _ = { println!("{}", _smelt_tmp_8); };
    let _ = { println!("{}", dog.breed.clone()); };
    let _smelt_tmp_11: Counter = Counter::new();
    plain = _smelt_tmp_11;
    let _ = plain.bump();
    let _smelt_tmp_13: NamedCounter = NamedCounter::new("clicks".to_owned());
    named = _smelt_tmp_13;
    let _ = named.bump();
    let _ = named.bump();
    let _smelt_tmp_16: String = report(plain)?;
    let _ = { println!("{}", _smelt_tmp_16); };
    let _smelt_tmp_18: String = report({ let smelt_struct_value = named.clone(); Counter(::std::rc::Rc::new(::std::cell::RefCell::new(CounterInner { count: smelt_struct_value.0.borrow().count.clone(), label: { let smelt_virtual_receiver = smelt_struct_value.clone(); let smelt_virtual_method: ::std::rc::Rc<dyn Fn() -> String> = ::std::rc::Rc::new(move || -> String { let smelt_method_receiver = smelt_virtual_receiver.clone(); smelt_method_receiver.label() }); smelt_virtual_method } }))) })?;
    let _ = { println!("{}", _smelt_tmp_18); };
    return Ok(());
}

impl Animal {
    fn new(name: String, legs: f64) -> Self {
    let mut this: Self = Animal { name: String::new(), legs: 0.0, speak: { let smelt_default_callback: ::std::rc::Rc<dyn Fn() -> String> = ::std::rc::Rc::new(move || -> String { String::new() }); smelt_default_callback } };
    this.name = name.clone();
    this.legs = legs;
    { let smelt_struct_value = this.clone(); let smelt_bound_slot = { let smelt_virtual_receiver = smelt_struct_value.clone(); let smelt_virtual_method: ::std::rc::Rc<dyn Fn() -> String> = ::std::rc::Rc::new(move || -> String { let smelt_method_receiver = smelt_virtual_receiver.clone(); smelt_method_receiver.speak() }); smelt_virtual_method }; this.speak = smelt_bound_slot; }
    return this;
    }
    fn speak(&self) -> String {
    let _smelt_tmp_1: String = self.name.clone() + &" makes a sound".to_owned();
    return _smelt_tmp_1;
    }
    fn describe(&self) -> String {
    let _smelt_tmp_1: String = self.name.clone() + &" has ".to_owned();
    let _smelt_tmp_2: String = _smelt_tmp_1 + &smelt_number_to_string(self.legs);
    let _smelt_tmp_3: String = _smelt_tmp_2 + &" legs".to_owned();
    return _smelt_tmp_3;
    }
}

impl Dog {
    fn new(name: String, breed: String) -> Self {
    let __smelt_super: Animal;
    let mut this: Self = Dog { name: String::new(), legs: 0.0, speak: { let smelt_default_callback: ::std::rc::Rc<dyn Fn() -> String> = ::std::rc::Rc::new(move || -> String { String::new() }); smelt_default_callback }, breed: String::new() };
    let _smelt_tmp_4: Animal = Animal::new(name.clone(), 4.0);
    __smelt_super = _smelt_tmp_4;
    this.name = __smelt_super.name.clone();
    this.legs = __smelt_super.legs;
    this.breed = breed.clone();
    return this;
    }
    fn speak(&self) -> String {
    let _smelt_tmp_1: String = self.name.clone() + &" the ".to_owned();
    let _smelt_tmp_2: String = _smelt_tmp_1 + &self.breed.clone();
    let _smelt_tmp_3: String = _smelt_tmp_2 + &" barks".to_owned();
    return _smelt_tmp_3;
    }
    fn describe(&self) -> String {
    let _smelt_tmp_1: String = self.name.clone() + &" has ".to_owned();
    let _smelt_tmp_2: String = _smelt_tmp_1 + &smelt_number_to_string(self.legs);
    let _smelt_tmp_3: String = _smelt_tmp_2 + &" legs".to_owned();
    return _smelt_tmp_3;
    }
}

impl Counter {
    fn new() -> Self {
    let mut this: Self = Counter(::std::rc::Rc::new(::std::cell::RefCell::new(CounterInner { count: 0.0, label: { let smelt_default_callback: ::std::rc::Rc<dyn Fn() -> String> = ::std::rc::Rc::new(move || -> String { String::new() }); smelt_default_callback } })));
    this.0.borrow_mut().count = 0.0;
    { let smelt_struct_value = this.clone(); let smelt_bound_slot = { let smelt_virtual_receiver = smelt_struct_value.clone(); let smelt_virtual_method: ::std::rc::Rc<dyn Fn() -> String> = ::std::rc::Rc::new(move || -> String { let smelt_method_receiver = smelt_virtual_receiver.clone(); smelt_method_receiver.label() }); smelt_virtual_method }; this.0.borrow_mut().label = smelt_bound_slot; }
    return this;
    }
    fn bump(&self) -> () {
    let _smelt_tmp_1: f64 = self.0.borrow().count.clone() + 1.0;
    self.0.borrow_mut().count = _smelt_tmp_1;
    return;
    }
    fn label(&self) -> String {
    let _smelt_tmp_1: String = "counter at ".to_owned() + &smelt_number_to_string(self.0.borrow().count.clone());
    return _smelt_tmp_1;
    }
}

impl NamedCounter {
    fn new(title: String) -> Self {
    let __smelt_super: Counter;
    let mut this: Self = NamedCounter(::std::rc::Rc::new(::std::cell::RefCell::new(NamedCounterInner { count: 0.0, label: { let smelt_default_callback: ::std::rc::Rc<dyn Fn() -> String> = ::std::rc::Rc::new(move || -> String { String::new() }); smelt_default_callback }, title: String::new() })));
    let _smelt_tmp_3: Counter = Counter::new();
    __smelt_super = _smelt_tmp_3;
    this.0.borrow_mut().count = __smelt_super.0.borrow().count.clone();
    this.0.borrow_mut().title = title.clone();
    return this;
    }
    fn bump(&self) -> () {
    let _smelt_tmp_1: f64 = self.0.borrow().count.clone() + 1.0;
    self.0.borrow_mut().count = _smelt_tmp_1;
    return;
    }
    fn label(&self) -> String {
    let _smelt_tmp_1: String = self.0.borrow().title.clone().clone() + &" at ".to_owned();
    let _smelt_tmp_2: String = _smelt_tmp_1 + &smelt_number_to_string(self.0.borrow().count.clone());
    return _smelt_tmp_2;
    }
}

// ==== source_main.rs
// @generated by smelt. Do not edit by hand.
// source: <example>/src/main.ts
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

use super::*;

pub(crate) fn introduce(animal: Animal) -> Result<String, Box<dyn std::error::Error>> {
    let _smelt_tmp_4: String;
    let _smelt_tmp_1: String = (animal.speak.clone())();
    let _smelt_tmp_2: String = _smelt_tmp_1 + &"; ".to_owned();
    let _smelt_tmp_3: String = animal.describe();
    _smelt_tmp_4 = _smelt_tmp_2 + &_smelt_tmp_3;
    return Ok(_smelt_tmp_4);
}

pub(crate) fn report(counter: Counter) -> Result<String, Box<dyn std::error::Error>> {
    let _smelt_tmp_1: String = { let smelt_callable = ::std::clone::Clone::clone(&counter.0.borrow().label.clone()); (smelt_callable)() };
    return Ok(_smelt_tmp_1);
}
