// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

fn main() {
    let _smelt_tmp_1: (String, f64) = ("age".to_owned(), 42.0);
    let pair: (String, f64) = _smelt_tmp_1.clone();
    let _smelt_tmp_2: () = { println!("{:?}", pair.clone()); };
}
