// Generated by smelt. Do not edit.

export declare function depth(n: number): number;
export declare function factorial(n: number): number;
export type Handler = (string) => string;
export declare function walk(n: number): string;
export declare function tagger(prefix: string): (string) => string;
export declare function report(): void;
