// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

fn main() {
    let code: f64 = 2.0;
    let mut label: String = "".to_owned();
    match code.clone() {
        1.0 => {
    label = "one".to_owned();
        }
        2.0 => {
    label = "two".to_owned();
        }
        _ => {
    label = "other".to_owned();
        }
    }
    let _ = { println!("{}", label.clone()); };
}
