// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

#[derive(Clone, Debug, Default)]
struct Secret {
    token: String,
    count: f64,
}


fn main() {
    let mut secret: Secret;
    let mut _smelt_tmp_1: Secret = Secret::new("s".to_owned(), 1.0);
    secret = _smelt_tmp_1.clone();
    let _smelt_tmp_2: String = secret.reveal();
    let _ = { println!("{}", _smelt_tmp_2.clone()); };
    return;
}

impl Secret {
    fn new(token: String, count: f64) -> Self {
    let mut this: Self = Secret { token: String::new(), count: 0.0 };
    this.token = token.clone();
    this.count = count.clone();
    return this;
    }
    fn reveal(&self) -> String {
    return self.token.clone();
    }
}
