// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

// @smelt:prelude-end — generated program below
fn main() {
    let mut _smelt_tmp_2: bool;
    let mut _smelt_tmp_3: f64;
    let mut _smelt_tmp_4: bool;
    let mut _smelt_tmp_5: f64;
    let mut i: f64 = 0.0;
    let mut sum: f64 = 0.0;
    loop {
    _smelt_tmp_2 = i < 6.0;
    if !(_smelt_tmp_2) { break; }
    _smelt_tmp_3 = i + 1.0;
    i = _smelt_tmp_3;
    _smelt_tmp_4 = i == 2.0;
    if _smelt_tmp_4 {
    continue;
    } else {
    _smelt_tmp_5 = sum + i;
    sum = _smelt_tmp_5;
    continue;
    }
    }
    let _ = { println!("{}", sum); };
    return;
}
