// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

fn main() {
    let message: String = "hello smelt".to_owned();
    let _smelt_tmp_1: () = { println!("{}", message.clone()); };
}
