// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

#[path = "source_main.rs"]
mod __smelt_module_source_main;
pub(crate) use __smelt_module_source_main::*;


thread_local! {
    static SMELT_NEXT_OBJECT_ID: ::std::cell::Cell<usize> = const { ::std::cell::Cell::new(1) };
}

#[allow(dead_code)]
fn smelt_next_object_id() -> usize {
    SMELT_NEXT_OBJECT_ID.with(|next| { let id = next.get(); next.set(id.saturating_add(1)); id })
}

/// A WHATWG `Headers` list: ordered name/value pairs, case-insensitive
/// names, comma-joined reads, and the `Set-Cookie` carve-out.
#[derive(Clone)]
pub struct SmeltHeaders {
    id: usize,
    /// Lower-cased name and normalized value, in insertion order.
    entries: ::std::rc::Rc<::std::cell::RefCell<Vec<(String, String)>>>,
}

impl PartialEq for SmeltHeaders { fn eq(&self, other: &Self) -> bool { self.entries_sorted() == other.entries_sorted() } }
impl ::std::fmt::Debug for SmeltHeaders { fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result { formatter.debug_map().entries(self.entries_sorted()).finish() } }
impl Default for SmeltHeaders { fn default() -> Self { Self::new() } }

#[allow(dead_code)]
impl SmeltHeaders {
    /// An empty header list with a fresh JS reference identity.
    pub fn new() -> Self { Self { id: smelt_next_object_id(), entries: ::std::rc::Rc::new(::std::cell::RefCell::new(Vec::new())) } }
    /// JS reference identity of this header list.
    pub fn id(&self) -> usize { self.id }
    /// Build a header list from name/value pairs, appending in order.
    pub fn from_pairs(pairs: Vec<(String, String)>) -> Self { let headers = Self::new(); for (name, value) in pairs { headers.append(&name, &value); } headers }
    /// The spec's header-name normalization: lower-cased.
    fn normalize_name(name: &str) -> String { name.trim().to_ascii_lowercase() }
    /// The spec's header-value normalization: strip HTTP whitespace.
    fn normalize_value(value: &str) -> String { value.trim_matches(|ch| ch == ' ' || ch == '\t' || ch == '\r' || ch == '\n').to_owned() }
    /// `get(name)`: every value for the name, joined with `", "`.
    ///
    /// `None` is the source `null`: the name is not in the list. The
    /// return type is the source type, so no caller has to re-narrow it.
    pub fn get(&self, name: &str) -> Option<String> {
        let key = Self::normalize_name(name);
        let values: Vec<String> = self.entries.borrow().iter().filter(|(entry_name, _)| *entry_name == key).map(|(_, value)| value.clone()).collect();
        if values.is_empty() { None } else { Some(values.join(", ")) }
    }
    /// `has(name)`.
    pub fn has(&self, name: &str) -> bool { let key = Self::normalize_name(name); self.entries.borrow().iter().any(|(entry_name, _)| *entry_name == key) }
    /// `append(name, value)`: add a pair, keeping existing ones.
    pub fn append(&self, name: &str, value: &str) { self.entries.borrow_mut().push((Self::normalize_name(name), Self::normalize_value(value))); }
    /// `set(name, value)`: replace every value for the name.
    ///
    /// The first existing pair's position is kept, matching the spec's
    /// "set the value of the first such header and remove the others".
    pub fn set(&self, name: &str, value: &str) {
        let key = Self::normalize_name(name);
        let normalized = Self::normalize_value(value);
        let mut entries = self.entries.borrow_mut();
        let position = entries.iter().position(|(entry_name, _)| *entry_name == key);
        let Some(index) = position else { entries.push((key, normalized)); return; };
        entries[index] = (key.clone(), normalized);
        // Keep the first pair with this name (the one just written) and
        // drop the rest, as the spec's `set` does.
        let mut kept = false;
        entries.retain(|(entry_name, _)| { if *entry_name != key { return true; } let first = !kept; kept = true; first });
    }
    /// `delete(name)`: remove every pair with the name.
    pub fn delete(&self, name: &str) { let key = Self::normalize_name(name); self.entries.borrow_mut().retain(|(entry_name, _)| *entry_name != key); }
    /// The spec's iteration order: sorted by name, values combined.
    ///
    /// `set-cookie` is the exception the spec carves out: its values are
    /// never combined, so each cookie stays its own entry.
    pub fn entries_sorted(&self) -> Vec<(String, String)> {
        let entries = self.entries.borrow().clone();
        let mut names: Vec<String> = entries.iter().map(|(name, _)| name.clone()).collect();
        names.sort();
        names.dedup();
        let mut combined = Vec::new();
        for name in names {
            let values: Vec<String> = entries.iter().filter(|(entry_name, _)| *entry_name == name).map(|(_, value)| value.clone()).collect();
            if name == "set-cookie" {
                for value in values { combined.push((name.clone(), value)); }
            }
            else {
                combined.push((name.clone(), values.join(", ")));
            }
        }
        combined
    }
    /// The stored pairs, in insertion order, uncombined.
    ///
    /// NOT the spec's iteration order (`entries_sorted`), which sorts by
    /// name and comma-joins values. Copying a header list has to go
    /// through this instead: rebuilding from the combined view would turn
    /// two `Accept` headers into one, which a copy must not do.
    pub fn entries_in_insertion_order(&self) -> Vec<(String, String)> { self.entries.borrow().clone() }
    /// `keys()`: header names in iteration order.
    pub fn keys(&self) -> Vec<String> { self.entries_sorted().into_iter().map(|(name, _)| name).collect() }
    /// `values()`: header values in iteration order.
    pub fn values(&self) -> Vec<String> { self.entries_sorted().into_iter().map(|(_, value)| value).collect() }
    /// `getSetCookie()`: each `Set-Cookie` value, uncombined.
    pub fn get_set_cookie(&self) -> Vec<String> { self.entries.borrow().iter().filter(|(name, _)| name == "set-cookie").map(|(_, value)| value.clone()).collect() }
}

/// A WHATWG `URLSearchParams` list: ordered, case-sensitive
/// name/value pairs with urlencoded serialization.
#[derive(Clone)]
pub struct SmeltUrlSearchParams {
    id: usize,
    /// Name/value pairs in insertion order.
    entries: ::std::rc::Rc<::std::cell::RefCell<Vec<(String, String)>>>,
}

impl PartialEq for SmeltUrlSearchParams { fn eq(&self, other: &Self) -> bool { *self.entries.borrow() == *other.entries.borrow() } }
impl ::std::fmt::Debug for SmeltUrlSearchParams { fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result { formatter.write_str(&self.to_text()) } }
impl Default for SmeltUrlSearchParams { fn default() -> Self { Self::new() } }

#[allow(dead_code)]
impl SmeltUrlSearchParams {
    /// An empty parameter list with a fresh JS reference identity.
    pub fn new() -> Self { Self { id: smelt_next_object_id(), entries: ::std::rc::Rc::new(::std::cell::RefCell::new(Vec::new())) } }
    /// JS reference identity of this parameter list.
    pub fn id(&self) -> usize { self.id }
    /// Build a parameter list from name/value pairs, in order.
    pub fn from_pairs(pairs: Vec<(String, String)>) -> Self { let params = Self::new(); params.entries.borrow_mut().extend(pairs); params }
    /// Parse a query string (with or without a leading `?`).
    ///
    /// `url::form_urlencoded` owns the decoding: `+` is a space, `%XX` is
    /// a byte, and a pair with no `=` has the empty string as its value.
    pub fn from_query(query: &str) -> Self {
        let trimmed = query.strip_prefix('?').unwrap_or(query);
        let pairs = url::form_urlencoded::parse(trimmed.as_bytes()).map(|(name, value): (::std::borrow::Cow<'_, str>, ::std::borrow::Cow<'_, str>)| (name.into_owned(), value.into_owned())).collect::<Vec<(String, String)>>();
        Self::from_pairs(pairs)
    }
    /// `get(name)`: the FIRST value for a name, or `null`.
    pub fn get(&self, name: &str) -> Option<String> { self.entries.borrow().iter().find(|(entry_name, _)| entry_name == name).map(|(_, value)| value.clone()) }
    /// `getAll(name)`: every value for a name, in order.
    pub fn get_all(&self, name: &str) -> Vec<String> { self.entries.borrow().iter().filter(|(entry_name, _)| entry_name == name).map(|(_, value)| value.clone()).collect() }
    /// `has(name)`.
    pub fn has(&self, name: &str) -> bool { self.entries.borrow().iter().any(|(entry_name, _)| entry_name == name) }
    /// `append(name, value)`.
    pub fn append(&self, name: &str, value: &str) { self.entries.borrow_mut().push((name.to_owned(), value.to_owned())); }
    /// `set(name, value)`: replace the first value, drop the rest.
    pub fn set(&self, name: &str, value: &str) {
        let mut entries = self.entries.borrow_mut();
        let position = entries.iter().position(|(entry_name, _)| entry_name == name);
        let Some(index) = position else { entries.push((name.to_owned(), value.to_owned())); return; };
        entries[index] = (name.to_owned(), value.to_owned());
        let mut kept = false;
        entries.retain(|(entry_name, _)| { if entry_name != name { return true; } let first = !kept; kept = true; first });
    }
    /// `delete(name)`: remove every pair with the name.
    pub fn delete(&self, name: &str) { self.entries.borrow_mut().retain(|(entry_name, _)| entry_name != name); }
    /// `sort()`: stable sort by name, keeping equal names in order.
    pub fn sort(&self) { self.entries.borrow_mut().sort_by(|left, right| left.0.cmp(&right.0)); }
    /// `toString()`: the urlencoded serialization.
    pub fn to_text(&self) -> String {
        let mut serializer = url::form_urlencoded::Serializer::new(String::new());
        for (name, value) in self.entries.borrow().iter() { serializer.append_pair(name, value); }
        serializer.finish()
    }
    /// `entries()`: the pairs in insertion order.
    pub fn entries_in_order(&self) -> Vec<(String, String)> { self.entries.borrow().clone() }
    /// `keys()`: parameter names in insertion order.
    pub fn keys(&self) -> Vec<String> { self.entries.borrow().iter().map(|(name, _)| name.clone()).collect() }
    /// `values()`: parameter values in insertion order.
    pub fn values(&self) -> Vec<String> { self.entries.borrow().iter().map(|(_, value)| value.clone()).collect() }
    /// `size`: the number of pairs.
    pub fn size(&self) -> f64 { self.entries.borrow().len() as f64 }
}

/// The element type of a typed-array view.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[allow(dead_code)]
pub enum SmeltTypedArrayKind {
    /// `Int8Array`: 1-byte element.
    Int8,
    /// `Uint8Array`: 1-byte element.
    Uint8,
    /// `Uint8ClampedArray`: 1-byte element.
    Uint8Clamped,
    /// `Int16Array`: 2-byte elements.
    Int16,
    /// `Uint16Array`: 2-byte elements.
    Uint16,
    /// `Int32Array`: 4-byte elements.
    Int32,
    /// `Uint32Array`: 4-byte elements.
    Uint32,
    /// `Float32Array`: 4-byte elements.
    Float32,
    /// `Float64Array`: 8-byte elements.
    Float64,
    /// `BigInt64Array`: 8-byte elements.
    BigInt64,
    /// `BigUint64Array`: 8-byte elements.
    BigUint64,
}

#[allow(dead_code)]
impl SmeltTypedArrayKind {
    /// The constructor name, which is also the `[object X]` tag.
    pub fn class_name(self) -> &'static str {
        match self {
            Self::Int8 => "Int8Array",
            Self::Uint8 => "Uint8Array",
            Self::Uint8Clamped => "Uint8ClampedArray",
            Self::Int16 => "Int16Array",
            Self::Uint16 => "Uint16Array",
            Self::Int32 => "Int32Array",
            Self::Uint32 => "Uint32Array",
            Self::Float32 => "Float32Array",
            Self::Float64 => "Float64Array",
            Self::BigInt64 => "BigInt64Array",
            Self::BigUint64 => "BigUint64Array",
        }
    }
    /// The identity marker the erased face stamps for this kind.
    pub fn marker(self) -> &'static str {
        match self {
            Self::Int8 => "__smelt_int8array",
            Self::Uint8 => "__smelt_uint8array",
            Self::Uint8Clamped => "__smelt_uint8clampedarray",
            Self::Int16 => "__smelt_int16array",
            Self::Uint16 => "__smelt_uint16array",
            Self::Int32 => "__smelt_int32array",
            Self::Uint32 => "__smelt_uint32array",
            Self::Float32 => "__smelt_float32array",
            Self::Float64 => "__smelt_float64array",
            Self::BigInt64 => "__smelt_bigint64array",
            Self::BigUint64 => "__smelt_biguint64array",
        }
    }
    /// `BYTES_PER_ELEMENT`: the stride between elements.
    pub fn byte_width(self) -> usize {
        match self {
            Self::Int8 => 1,
            Self::Uint8 => 1,
            Self::Uint8Clamped => 1,
            Self::Int16 => 2,
            Self::Uint16 => 2,
            Self::Int32 => 4,
            Self::Uint32 => 4,
            Self::Float32 => 4,
            Self::Float64 => 8,
            Self::BigInt64 => 8,
            Self::BigUint64 => 8,
        }
    }
    /// The kind whose marker a byte-backed record carries, if any.
    pub fn from_marker(marker: &str) -> Option<Self> {
        if marker == "__smelt_int8array" { return Some(Self::Int8); }
        if marker == "__smelt_uint8array" { return Some(Self::Uint8); }
        if marker == "__smelt_uint8clampedarray" { return Some(Self::Uint8Clamped); }
        if marker == "__smelt_int16array" { return Some(Self::Int16); }
        if marker == "__smelt_uint16array" { return Some(Self::Uint16); }
        if marker == "__smelt_int32array" { return Some(Self::Int32); }
        if marker == "__smelt_uint32array" { return Some(Self::Uint32); }
        if marker == "__smelt_float32array" { return Some(Self::Float32); }
        if marker == "__smelt_float64array" { return Some(Self::Float64); }
        if marker == "__smelt_bigint64array" { return Some(Self::BigInt64); }
        if marker == "__smelt_biguint64array" { return Some(Self::BigUint64); }
        None
    }
    /// Read one element out of `bytes` at a byte offset.
    pub fn decode(self, bytes: &[u8], at: usize) -> f64 {
        let width = self.byte_width();
        if at + width > bytes.len() { return 0.0; }
        let window = &bytes[at..at + width];
        match self {
            Self::Int8 => f64::from(window[0] as i8),
            Self::Uint8 | Self::Uint8Clamped => f64::from(window[0]),
            Self::Int16 => f64::from(i16::from_le_bytes([window[0], window[1]])),
            Self::Uint16 => f64::from(u16::from_le_bytes([window[0], window[1]])),
            Self::Int32 => f64::from(i32::from_le_bytes([window[0], window[1], window[2], window[3]])),
            Self::Uint32 => f64::from(u32::from_le_bytes([window[0], window[1], window[2], window[3]])),
            Self::Float32 => f64::from(f32::from_le_bytes([window[0], window[1], window[2], window[3]])),
            Self::Float64 => f64::from_le_bytes([window[0], window[1], window[2], window[3], window[4], window[5], window[6], window[7]]),
            Self::BigInt64 => i64::from_le_bytes([window[0], window[1], window[2], window[3], window[4], window[5], window[6], window[7]]) as f64,
            Self::BigUint64 => u64::from_le_bytes([window[0], window[1], window[2], window[3], window[4], window[5], window[6], window[7]]) as f64,
        }
    }
    /// Write one element into `bytes` at a byte offset.
    pub fn encode(self, value: f64, bytes: &mut [u8], at: usize) {
        let width = self.byte_width();
        if at + width > bytes.len() { return; }
        let encoded = self.encode_bytes(value);
        bytes[at..at + width].copy_from_slice(&encoded[..width]);
    }
    /// One element's little-endian bytes, low-order first.
    fn encode_bytes(self, value: f64) -> [u8; 8] {
        match self {
            Self::Int8 => [(value as i64 as i8) as u8, 0, 0, 0, 0, 0, 0, 0],
            Self::Uint8 => [(value as i64 as u8), 0, 0, 0, 0, 0, 0, 0],
            Self::Uint8Clamped => [(if value.is_nan() { 0.0 } else { value.round_ties_even().clamp(0.0, 255.0) }) as u8, 0, 0, 0, 0, 0, 0, 0],
            Self::Int16 => { let mut out = [0_u8; 8]; out[..2].copy_from_slice(&(value as i64 as i16).to_le_bytes()); out },
            Self::Uint16 => { let mut out = [0_u8; 8]; out[..2].copy_from_slice(&(value as i64 as u16).to_le_bytes()); out },
            Self::Int32 => { let mut out = [0_u8; 8]; out[..4].copy_from_slice(&(value as i64 as i32).to_le_bytes()); out },
            Self::Uint32 => { let mut out = [0_u8; 8]; out[..4].copy_from_slice(&(value as i64 as u32).to_le_bytes()); out },
            Self::Float32 => { let mut out = [0_u8; 8]; out[..4].copy_from_slice(&(value as f32).to_le_bytes()); out },
            Self::Float64 => value.to_le_bytes(),
            Self::BigInt64 => (value as i64).to_le_bytes(),
            Self::BigUint64 => (value as i64 as u64).to_le_bytes(),
        }
    }
}

/// Byte storage with a JavaScript reference identity (`ArrayBuffer`).
#[derive(Clone)]
pub struct SmeltArrayBuffer {
    id: usize,
    /// The storage, shared by every view over it.
    bytes: ::std::rc::Rc<::std::cell::RefCell<Vec<u8>>>,
}

impl PartialEq for SmeltArrayBuffer { fn eq(&self, other: &Self) -> bool { *self.bytes.borrow() == *other.bytes.borrow() } }
impl ::std::fmt::Debug for SmeltArrayBuffer { fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result { write!(formatter, "ArrayBuffer {{ byteLength: {} }}", self.bytes.borrow().len()) } }
#[allow(dead_code)]
impl SmeltArrayBuffer {
    /// Zeroed storage of `byte_length` bytes.
    pub fn new(byte_length: usize) -> Self { Self::from_bytes(vec![0_u8; byte_length]) }
    /// Storage over owned bytes, with a fresh identity.
    pub fn from_bytes(bytes: Vec<u8>) -> Self { Self { id: smelt_next_object_id(), bytes: ::std::rc::Rc::new(::std::cell::RefCell::new(bytes)) } }
    /// JS reference identity of this storage.
    pub fn id(&self) -> usize { self.id }
    /// `byteLength`: the storage size in bytes.
    pub fn byte_length(&self) -> f64 { self.bytes.borrow().len() as f64 }
    /// A COPY of the storage's bytes.
    pub fn to_bytes(&self) -> Vec<u8> { self.bytes.borrow().clone() }
    /// The shared storage handle, for a view over it.
    pub fn storage(&self) -> ::std::rc::Rc<::std::cell::RefCell<Vec<u8>>> { ::std::rc::Rc::clone(&self.bytes) }
    /// Storage sharing this buffer's bytes handle and identity.
    pub fn from_storage(id: usize, bytes: ::std::rc::Rc<::std::cell::RefCell<Vec<u8>>>) -> Self { Self { id, bytes } }
    /// `slice(start, end)`: a COPY of a byte range in fresh storage.
    pub fn slice(&self, start: i64, end: Option<i64>) -> Self {
        let bytes = self.bytes.borrow();
        let len = bytes.len() as i64;
        let from = (if start < 0 { len + start } else { start }).clamp(0, len) as usize;
        let to = end.map_or(len, |end| if end < 0 { len + end } else { end }).clamp(0, len) as usize;
        Self::from_bytes(bytes[from..to.max(from)].to_vec())
    }
}

/// An element view over byte storage: kind, offset, length.
#[derive(Clone)]
pub struct SmeltTypedArray {
    id: usize,
    /// The element type this view reads and writes.
    kind: SmeltTypedArrayKind,
    /// The storage, SHARED with every other view over it.
    bytes: ::std::rc::Rc<::std::cell::RefCell<Vec<u8>>>,
    /// Identity of the `ArrayBuffer` this view reports.
    buffer_id: usize,
    /// `byteOffset`: where this view starts in the storage.
    byte_offset: usize,
    /// `length`: how many elements this view spans.
    length: usize,
}

impl PartialEq for SmeltTypedArray { fn eq(&self, other: &Self) -> bool { self.kind == other.kind && self.to_elements() == other.to_elements() } }
impl ::std::fmt::Debug for SmeltTypedArray {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let elements = self.to_elements();
        let name = self.kind.class_name();
        if elements.is_empty() { return write!(formatter, "{name}(0) []"); }
        let items = elements.iter().map(|element| element.to_string()).collect::<Vec<String>>().join(", ");
        write!(formatter, "{name}({}) [ {items} ]", elements.len())
    }
}
impl Default for SmeltTypedArray { fn default() -> Self { Self::new() } }

#[allow(dead_code)]
impl SmeltTypedArray {
    /// An empty `Uint8` view with a fresh reference identity.
    pub fn new() -> Self { Self::from_bytes(Vec::new()) }
    /// A `Uint8` view over owned bytes, with a fresh identity.
    pub fn from_bytes(bytes: Vec<u8>) -> Self { Self::with_bytes(SmeltTypedArrayKind::Uint8, bytes) }
    /// A view of `kind` over owned bytes, in fresh storage.
    pub fn with_bytes(kind: SmeltTypedArrayKind, bytes: Vec<u8>) -> Self {
        let length = bytes.len() / kind.byte_width();
        Self { id: smelt_next_object_id(), kind, bytes: ::std::rc::Rc::new(::std::cell::RefCell::new(bytes)), buffer_id: smelt_next_object_id(), byte_offset: 0, length }
    }
    /// A view of `kind` over the given elements, in fresh storage.
    pub fn with_elements(kind: SmeltTypedArrayKind, elements: &[f64]) -> Self {
        let width = kind.byte_width();
        let mut bytes = vec![0_u8; elements.len() * width];
        for (index, element) in elements.iter().enumerate() { kind.encode(*element, &mut bytes, index * width); }
        Self::with_bytes(kind, bytes)
    }
    /// A view of `kind` over an existing buffer's storage.
    pub fn over_buffer(kind: SmeltTypedArrayKind, buffer: &SmeltArrayBuffer, byte_offset: usize, length: Option<usize>) -> Self {
        let storage = buffer.storage();
        let available = storage.borrow().len().saturating_sub(byte_offset) / kind.byte_width();
        let length = length.map_or(available, |length| length.min(available));
        Self { id: smelt_next_object_id(), kind, bytes: storage, buffer_id: buffer.id(), byte_offset, length }
    }
    /// JS reference identity of this view.
    pub fn id(&self) -> usize { self.id }
    /// The element type this view reads.
    pub fn kind(&self) -> SmeltTypedArrayKind { self.kind }
    /// The constructor name, which is also the `[object X]` tag.
    pub fn class_name(&self) -> &'static str { self.kind.class_name() }
    /// `length`: the element count.
    pub fn length(&self) -> f64 { self.length as f64 }
    /// `byteLength`: the byte count this view spans.
    pub fn byte_length(&self) -> f64 { (self.length * self.kind.byte_width()) as f64 }
    /// `byteOffset`: where this view starts in its buffer.
    pub fn byte_offset(&self) -> f64 { self.byte_offset as f64 }
    /// `buffer`: the storage this view reads, shared not copied.
    pub fn buffer(&self) -> SmeltArrayBuffer { SmeltArrayBuffer::from_storage(self.buffer_id, ::std::rc::Rc::clone(&self.bytes)) }
    /// A COPY of the bytes this view spans.
    pub fn to_bytes(&self) -> Vec<u8> {
        let bytes = self.bytes.borrow();
        let start = self.byte_offset.min(bytes.len());
        let end = (start + self.length * self.kind.byte_width()).min(bytes.len());
        bytes[start..end].to_vec()
    }
    /// The view's decoded elements, at its own width and signedness.
    pub fn to_elements(&self) -> Vec<f64> {
        let bytes = self.bytes.borrow();
        let width = self.kind.byte_width();
        (0..self.length).map(|index| self.kind.decode(&bytes, self.byte_offset + index * width)).collect()
    }
    /// An indexed element read; `None` past the end.
    pub fn get(&self, index: f64) -> Option<f64> {
        if index < 0.0 || index.fract() != 0.0 { return None; }
        let index = index as usize;
        if index >= self.length { return None; }
        let bytes = self.bytes.borrow();
        Some(self.kind.decode(&bytes, self.byte_offset + index * self.kind.byte_width()))
    }
    /// An indexed element write; dropped past the end.
    pub fn set_index(&self, index: f64, value: f64) {
        if index < 0.0 || index.fract() != 0.0 { return; }
        let index = index as usize;
        if index >= self.length { return; }
        let mut bytes = self.bytes.borrow_mut();
        let at = self.byte_offset + index * self.kind.byte_width();
        self.kind.encode(value, &mut bytes, at);
    }
    /// `subarray(start, end)`: another view over the SAME storage.
    pub fn subarray(&self, start: i64, end: Option<i64>) -> Self {
        let (from, to) = self.element_range(start, end);
        Self { id: smelt_next_object_id(), kind: self.kind, bytes: ::std::rc::Rc::clone(&self.bytes), buffer_id: self.buffer_id, byte_offset: self.byte_offset + from * self.kind.byte_width(), length: to.saturating_sub(from) }
    }
    /// `slice(start, end)`: a COPY of an element range.
    pub fn slice(&self, start: i64, end: Option<i64>) -> Self {
        let (from, to) = self.element_range(start, end);
        let width = self.kind.byte_width();
        let bytes = self.bytes.borrow();
        let at = self.byte_offset + from * width;
        let until = (self.byte_offset + to * width).min(bytes.len());
        Self::with_bytes(self.kind, bytes[at.min(until)..until].to_vec())
    }
    /// `set(source, offset)`: copy elements in, converting per element.
    pub fn set_from(&self, source: &Self, offset: usize) {
        for (index, element) in source.to_elements().into_iter().enumerate() { self.set_index((offset + index) as f64, element); }
    }
    /// `fill(value, start, end)`: write one value across a range.
    pub fn fill(&self, value: f64, start: i64, end: Option<i64>) -> Self {
        let (from, to) = self.element_range(start, end);
        for index in from..to { self.set_index(index as f64, value); }
        self.clone()
    }
    /// Clamped element bounds, counting back from the end when negative.
    fn element_range(&self, start: i64, end: Option<i64>) -> (usize, usize) {
        let len = self.length as i64;
        let from = (if start < 0 { len + start } else { start }).clamp(0, len);
        let to = end.map_or(len, |end| if end < 0 { len + end } else { end }).clamp(0, len);
        (from as usize, to.max(from) as usize)
    }
}

/// The `Uint8` face of the family: Smelt's concrete byte view.
pub type SmeltUint8Array = SmeltTypedArray;

/// A WHATWG `TextEncoder`: a UTF-8 encoder with a JS reference identity.
#[derive(Clone)]
pub struct SmeltTextEncoder {
    id: usize,
}

impl PartialEq for SmeltTextEncoder { fn eq(&self, _other: &Self) -> bool { true } }
impl ::std::fmt::Debug for SmeltTextEncoder { fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result { formatter.write_str("TextEncoder { encoding: 'utf-8' }") } }
impl Default for SmeltTextEncoder { fn default() -> Self { Self::new() } }

#[allow(dead_code)]
impl SmeltTextEncoder {
    /// A fresh encoder with a fresh JS reference identity.
    pub fn new() -> Self { Self { id: smelt_next_object_id() } }
    /// JS reference identity of this encoder.
    pub fn id(&self) -> usize { self.id }
    /// `encoding`: always `"utf-8"` per the spec.
    pub fn encoding(&self) -> String { "utf-8".to_owned() }
    /// `encode(input)`: the input's UTF-8 bytes.
    pub fn encode(&self, input: &str) -> SmeltUint8Array { SmeltUint8Array::from_bytes(input.as_bytes().to_vec()) }
}

/// A WHATWG `TextDecoder`: a UTF-8 decoder with a JS reference identity.
#[derive(Clone)]
pub struct SmeltTextDecoder {
    id: usize,
    /// The decoder's normalized encoding label.
    encoding: String,
}

impl PartialEq for SmeltTextDecoder { fn eq(&self, other: &Self) -> bool { self.encoding == other.encoding } }
impl ::std::fmt::Debug for SmeltTextDecoder { fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result { write!(formatter, "TextDecoder {{ encoding: '{}', fatal: false, ignoreBOM: false }}", self.encoding) } }
impl Default for SmeltTextDecoder { fn default() -> Self { Self::new() } }

#[allow(dead_code)]
impl SmeltTextDecoder {
    /// A fresh UTF-8 decoder with a fresh JS reference identity.
    pub fn new() -> Self { Self { id: smelt_next_object_id(), encoding: "utf-8".to_owned() } }
    /// A decoder for an encoding label, which is always a UTF-8 label.
    pub fn from_label(_label: &str) -> Self { Self::new() }
    /// JS reference identity of this decoder.
    pub fn id(&self) -> usize { self.id }
    /// `encoding`: the normalized encoding label.
    pub fn encoding(&self) -> String { self.encoding.clone() }
    /// `decode(input)`: the bytes read back as a string, substituting
    /// U+FFFD for ill-formed sequences as the non-`fatal` spec does.
    pub fn decode(&self, input: &SmeltUint8Array) -> String { String::from_utf8_lossy(&input.to_bytes()).into_owned() }
}

// @smelt:prelude-end — generated program below

thread_local! {
    static SMELT_GLOBAL_ENCODER_0: ::std::cell::RefCell<SmeltTextEncoder> = ::std::cell::RefCell::new(smelt_global_init__encoder__0());
    static SMELT_GLOBAL_DECODER_1: ::std::cell::RefCell<SmeltTextDecoder> = ::std::cell::RefCell::new(smelt_global_init__decoder__1());
    static SMELT_GLOBAL_HEADERS_2: ::std::cell::RefCell<SmeltHeaders> = ::std::cell::RefCell::new(smelt_global_init__headers__2());
    static SMELT_GLOBAL_PARAMS_3: ::std::cell::RefCell<SmeltUrlSearchParams> = ::std::cell::RefCell::new(smelt_global_init__params__3());
}
fn smelt_global_init__encoder__0() -> SmeltTextEncoder {
    let _smelt_tmp_0: SmeltTextEncoder = SmeltTextEncoder::new();
    return _smelt_tmp_0;
}

fn smelt_global_init__decoder__1() -> SmeltTextDecoder {
    let _smelt_tmp_0: SmeltTextDecoder = SmeltTextDecoder::new();
    return _smelt_tmp_0;
}

fn smelt_global_init__headers__2() -> SmeltHeaders {
    let _smelt_tmp_0: ::std::collections::HashMap<String, String> = ::std::collections::HashMap::from([("content-type".to_owned(), "text/plain".to_owned())]);
    let _smelt_tmp_1: SmeltHeaders = SmeltHeaders::from_pairs(_smelt_tmp_0.iter().map(|(smelt_name, smelt_value)| (smelt_name.clone(), smelt_value.clone())).collect::<Vec<(String, String)>>());
    return _smelt_tmp_1;
}

fn smelt_global_init__params__3() -> SmeltUrlSearchParams {
    let _smelt_tmp_0: SmeltUrlSearchParams = SmeltUrlSearchParams::from_query(&"a=1&b=2".to_owned());
    return _smelt_tmp_0;
}

fn main() {
    let _smelt_tmp_16: SmeltUrlSearchParams;
    let _smelt_tmp_17: String;
    let _smelt_tmp_19: SmeltHeaders;
    let _smelt_tmp_20: Option<String>;
    let _smelt_tmp_21: String;
    let _smelt_tmp_0: f64 = encoded_length("hello".to_owned());
    let _ = { println!("{}", _smelt_tmp_0); };
    let _smelt_tmp_2: f64 = encoded_length("héllo".to_owned());
    let _ = { println!("{}", _smelt_tmp_2); };
    let _smelt_tmp_4: String = round_trip("round trip".to_owned());
    let _ = { println!("{}", _smelt_tmp_4); };
    let _smelt_tmp_6: String = content_type();
    let _ = { println!("{}", _smelt_tmp_6); };
    let _smelt_tmp_8: String = extra();
    let _ = { println!("{}", _smelt_tmp_8); };
    let _ = add_header();
    let _smelt_tmp_11: String = extra();
    let _ = { println!("{}", _smelt_tmp_11); };
    let _smelt_tmp_13: String = param_a();
    let _ = { println!("{}", _smelt_tmp_13); };
    let _ = append_param();
    _smelt_tmp_16 = SMELT_GLOBAL_PARAMS_3.with(|value| value.borrow().clone());
    _smelt_tmp_17 = _smelt_tmp_16.to_text();
    let _ = { println!("{}", _smelt_tmp_17); };
    _smelt_tmp_19 = SMELT_GLOBAL_HEADERS_2.with(|value| value.borrow().clone());
    _smelt_tmp_20 = _smelt_tmp_19.get(&"content-type".to_owned());
    _smelt_tmp_21 = _smelt_tmp_20.clone().unwrap_or("none".to_owned());
    let _ = { println!("{}", _smelt_tmp_21); };
    return;
}
