// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

#[derive(Clone, Debug, Default)]
struct Named {
    name: String,
}

#[derive(Clone, Debug, Default)]
struct User {
    name: String,
}


fn main() {
    let mut _smelt_tmp_1: User = User::new("Ada".to_owned());
    let mut user: User = _smelt_tmp_1.clone();
    let _smelt_tmp_2: () = { println!("{}", user.name.clone()); };
}

impl User {
    fn new(name: String) -> Self {
    let mut this: Self = User { name: String::new() };
    this.name = name.clone();
    return this;
    }
}
