// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

#[path = "source_main.rs"]
mod __smelt_module_source_main;
pub(crate) use __smelt_module_source_main::*;


/// `Number::toString(value, 10)`: JavaScript's number formatting.
///
/// Exponential notation at `n > 21` and `n <= -6`, where `n` is the
/// decimal exponent of the shortest round-trip digit string — which is
/// what Rust's `{:e}` already produces.
fn smelt_number_to_string<N: ::std::borrow::Borrow<f64>>(value: N) -> String {
    let value = *value.borrow();
    if value.is_nan() { return "NaN".to_owned(); }
    if value == 0.0 { return "0".to_owned(); }
    if value < 0.0 { return format!("-{}", smelt_number_to_string(-value)); }
    if value.is_infinite() { return "Infinity".to_owned(); }
    let exponential = format!("{value:e}");
    let (mantissa, exponent) = exponential.split_once('e').unwrap_or((exponential.as_str(), "0"));
    let digits: String = mantissa.chars().filter(char::is_ascii_digit).collect();
    let k = i32::try_from(digits.len()).unwrap_or(i32::MAX);
    let n = exponent.parse::<i32>().unwrap_or(0) + 1;
    if k <= n && n <= 21 {
        let zeros = usize::try_from(n - k).unwrap_or(0);
        return digits + &"0".repeat(zeros);
    }
    if 0 < n && n <= 21 {
        let split = usize::try_from(n).unwrap_or(0);
        return format!("{}.{}", &digits[..split], &digits[split..]);
    }
    if -6 < n && n <= 0 {
        let zeros = usize::try_from(-n).unwrap_or(0);
        return format!("0.{}{}", "0".repeat(zeros), digits);
    }
    let sign = if n - 1 < 0 { '-' } else { '+' };
    let magnitude = (n - 1).abs();
    if k == 1 { return format!("{digits}e{sign}{magnitude}"); }
    format!("{}.{}e{sign}{magnitude}", &digits[..1], &digits[1..])
}

/// `console.log`'s number formatting: the spec's rule, but `-0` prints `-0`.
fn smelt_console_number<N: ::std::borrow::Borrow<f64>>(value: N) -> String { let value = *value.borrow(); if value == 0.0 && value.is_sign_negative() { return "-0".to_owned(); } smelt_number_to_string(value) }

thread_local! {
    static SMELT_NEXT_OBJECT_ID: ::std::cell::Cell<usize> = const { ::std::cell::Cell::new(1) };
}

#[allow(dead_code)]
fn smelt_next_object_id() -> usize {
    SMELT_NEXT_OBJECT_ID.with(|next| { let id = next.get(); next.set(id.saturating_add(1)); id })
}

/// A JavaScript array: a reference identity plus a shared backing buffer.
pub struct SmeltList<T> {
    id: usize,
    values: ::std::rc::Rc<::std::cell::RefCell<Vec<T>>>,
}
impl<T: ::std::fmt::Debug> ::std::fmt::Debug for SmeltList<T> { fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result { self.values.borrow().fmt(formatter) } }
impl<T> Clone for SmeltList<T> { fn clone(&self) -> Self { Self { id: self.id, values: ::std::rc::Rc::clone(&self.values) } } }
#[allow(dead_code)]
impl<T> SmeltList<T> {
    /// Create an identity-bearing typed list with a fresh JS reference identity.
    fn new(values: Vec<T>) -> Self { Self { id: smelt_next_object_id(), values: ::std::rc::Rc::new(::std::cell::RefCell::new(values)) } }
    /// Reuse a caller-supplied identity so an erase/extract round-trip stays `===` equal.
    fn with_id(id: usize, values: Vec<T>) -> Self { Self { id, values: ::std::rc::Rc::new(::std::cell::RefCell::new(values)) } }
    /// Reuse an existing shared buffer, so a re-wrap keeps aliasing the same array.
    fn with_storage(id: usize, values: ::std::rc::Rc<::std::cell::RefCell<Vec<T>>>) -> Self { Self { id, values } }
    /// Another handle on this array's shared buffer.
    fn storage(&self) -> ::std::rc::Rc<::std::cell::RefCell<Vec<T>>> { ::std::rc::Rc::clone(&self.values) }
    /// JS reference identity of this list.
    fn id(&self) -> usize { self.id }
    /// Borrow the backing storage for reading. The guard lives to the end of the
    /// enclosing statement; never pair it with `borrow_mut` in one expression.
    fn borrow(&self) -> ::std::cell::Ref<'_, Vec<T>> { self.values.borrow() }
    /// Borrow the backing storage for writing, through the shared cell — so this
    /// takes `&self`, and every other handle on the array observes the write.
    fn borrow_mut(&self) -> ::std::cell::RefMut<'_, Vec<T>> { self.values.borrow_mut() }
    /// Element count, taking its own short-lived borrow.
    fn len(&self) -> usize { self.values.borrow().len() }
    /// Whether the array holds no elements.
    fn is_empty(&self) -> bool { self.values.borrow().is_empty() }
    /// Replace every element in place, so aliases observe the new contents.
    fn replace_all(&self, values: Vec<T>) { *self.values.borrow_mut() = values; }
}
#[allow(dead_code)]
impl<T: Clone> SmeltList<T> {
    /// A JS array copy (`[...a]`, `slice`): same contents, a NEW identity AND a
    /// new buffer. This is the operation that keeps sharing from over-sharing.
    fn fresh_copy(&self) -> Self { Self::new(self.values.borrow().clone()) }
    /// Snapshot the elements. This COPIES unless this is the last handle, so
    /// mutating the result does not write back.
    fn into_vec(self) -> Vec<T> { match ::std::rc::Rc::try_unwrap(self.values) { Ok(cell) => cell.into_inner(), Err(shared) => shared.borrow().clone() } }
    /// Snapshot the elements without consuming the handle.
    fn to_vec(&self) -> Vec<T> { self.values.borrow().clone() }
    /// Read one element by index, cloned out of the shared buffer (JS `arr[i]`).
    fn get_index(&self, index: usize) -> Option<T> { self.values.borrow().get(index).cloned() }
    /// Set the element at a numeric index, extending with `fill` holes to match JS `arr[i] = v`.
    fn set_index(&self, index: usize, value: T, fill: T) { let mut values = self.values.borrow_mut(); if index >= values.len() { values.resize(index.saturating_add(1), fill); } values[index] = value; }
    /// Iterate a snapshot of the elements, so the buffer is not borrowed across the loop body.
    fn iter(&self) -> ::std::vec::IntoIter<T> { self.values.borrow().clone().into_iter() }
}
impl<T> From<Vec<T>> for SmeltList<T> { fn from(values: Vec<T>) -> Self { Self::new(values) } }
impl<T> ::std::iter::FromIterator<T> for SmeltList<T> { fn from_iter<I: IntoIterator<Item = T>>(iter: I) -> Self { Self::new(iter.into_iter().collect()) } }
impl<T: Clone> IntoIterator for SmeltList<T> { type Item = T; type IntoIter = ::std::vec::IntoIter<T>; fn into_iter(self) -> Self::IntoIter { self.into_vec().into_iter() } }
impl<T: Clone> IntoIterator for &SmeltList<T> { type Item = T; type IntoIter = ::std::vec::IntoIter<T>; fn into_iter(self) -> Self::IntoIter { self.values.borrow().clone().into_iter() } }
impl<T: PartialEq> PartialEq for SmeltList<T> { fn eq(&self, other: &Self) -> bool { *self.values.borrow() == *other.values.borrow() } }
impl<T: PartialEq> Eq for SmeltList<T> {}
impl<T: ::std::hash::Hash> ::std::hash::Hash for SmeltList<T> { fn hash<H: ::std::hash::Hasher>(&self, state: &mut H) { self.values.borrow().hash(state); } }
impl<T> Default for SmeltList<T> { fn default() -> Self { Self::new(Vec::new()) } }
impl<T: Clone> From<SmeltList<T>> for Vec<T> { fn from(list: SmeltList<T>) -> Self { list.into_vec() } }

/// A WHATWG `Headers` list: ordered name/value pairs, case-insensitive
/// names, comma-joined reads, and the `Set-Cookie` carve-out.
#[derive(Clone)]
pub struct SmeltHeaders {
    id: usize,
    /// Lower-cased name and normalized value, in insertion order.
    entries: ::std::rc::Rc<::std::cell::RefCell<Vec<(String, String)>>>,
}

impl PartialEq for SmeltHeaders { fn eq(&self, other: &Self) -> bool { self.entries_sorted() == other.entries_sorted() } }
impl ::std::fmt::Debug for SmeltHeaders { fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result { formatter.debug_map().entries(self.entries_sorted()).finish() } }
impl Default for SmeltHeaders { fn default() -> Self { Self::new() } }

#[allow(dead_code)]
impl SmeltHeaders {
    /// An empty header list with a fresh JS reference identity.
    pub fn new() -> Self { Self { id: smelt_next_object_id(), entries: ::std::rc::Rc::new(::std::cell::RefCell::new(Vec::new())) } }
    /// JS reference identity of this header list.
    pub fn id(&self) -> usize { self.id }
    /// Build a header list from name/value pairs, appending in order.
    pub fn from_pairs(pairs: Vec<(String, String)>) -> Self { let headers = Self::new(); for (name, value) in pairs { headers.append(&name, &value); } headers }
    /// The spec's header-name normalization: lower-cased.
    fn normalize_name(name: &str) -> String { name.trim().to_ascii_lowercase() }
    /// The spec's header-value normalization: strip HTTP whitespace.
    fn normalize_value(value: &str) -> String { value.trim_matches(|ch| ch == ' ' || ch == '\t' || ch == '\r' || ch == '\n').to_owned() }
    /// `get(name)`: every value for the name, joined with `", "`.
    ///
    /// `None` is the source `null`: the name is not in the list. The
    /// return type is the source type, so no caller has to re-narrow it.
    pub fn get(&self, name: &str) -> Option<String> {
        let key = Self::normalize_name(name);
        let values: Vec<String> = self.entries.borrow().iter().filter(|(entry_name, _)| *entry_name == key).map(|(_, value)| value.clone()).collect();
        if values.is_empty() { None } else { Some(values.join(", ")) }
    }
    /// `has(name)`.
    pub fn has(&self, name: &str) -> bool { let key = Self::normalize_name(name); self.entries.borrow().iter().any(|(entry_name, _)| *entry_name == key) }
    /// `append(name, value)`: add a pair, keeping existing ones.
    pub fn append(&self, name: &str, value: &str) { self.entries.borrow_mut().push((Self::normalize_name(name), Self::normalize_value(value))); }
    /// `set(name, value)`: replace every value for the name.
    ///
    /// The first existing pair's position is kept, matching the spec's
    /// "set the value of the first such header and remove the others".
    pub fn set(&self, name: &str, value: &str) {
        let key = Self::normalize_name(name);
        let normalized = Self::normalize_value(value);
        let mut entries = self.entries.borrow_mut();
        let position = entries.iter().position(|(entry_name, _)| *entry_name == key);
        let Some(index) = position else { entries.push((key, normalized)); return; };
        entries[index] = (key.clone(), normalized);
        // Keep the first pair with this name (the one just written) and
        // drop the rest, as the spec's `set` does.
        let mut kept = false;
        entries.retain(|(entry_name, _)| { if *entry_name != key { return true; } let first = !kept; kept = true; first });
    }
    /// `delete(name)`: remove every pair with the name.
    pub fn delete(&self, name: &str) { let key = Self::normalize_name(name); self.entries.borrow_mut().retain(|(entry_name, _)| *entry_name != key); }
    /// The spec's iteration order: sorted by name, values combined.
    ///
    /// `set-cookie` is the exception the spec carves out: its values are
    /// never combined, so each cookie stays its own entry.
    pub fn entries_sorted(&self) -> Vec<(String, String)> {
        let entries = self.entries.borrow().clone();
        let mut names: Vec<String> = entries.iter().map(|(name, _)| name.clone()).collect();
        names.sort();
        names.dedup();
        let mut combined = Vec::new();
        for name in names {
            let values: Vec<String> = entries.iter().filter(|(entry_name, _)| *entry_name == name).map(|(_, value)| value.clone()).collect();
            if name == "set-cookie" {
                for value in values { combined.push((name.clone(), value)); }
            }
            else {
                combined.push((name.clone(), values.join(", ")));
            }
        }
        combined
    }
    /// The stored pairs, in insertion order, uncombined.
    ///
    /// NOT the spec's iteration order (`entries_sorted`), which sorts by
    /// name and comma-joins values. Copying a header list has to go
    /// through this instead: rebuilding from the combined view would turn
    /// two `Accept` headers into one, which a copy must not do.
    pub fn entries_in_insertion_order(&self) -> Vec<(String, String)> { self.entries.borrow().clone() }
    /// `keys()`: header names in iteration order.
    pub fn keys(&self) -> Vec<String> { self.entries_sorted().into_iter().map(|(name, _)| name).collect() }
    /// `values()`: header values in iteration order.
    pub fn values(&self) -> Vec<String> { self.entries_sorted().into_iter().map(|(_, value)| value).collect() }
    /// `getSetCookie()`: each `Set-Cookie` value, uncombined.
    pub fn get_set_cookie(&self) -> Vec<String> { self.entries.borrow().iter().filter(|(name, _)| name == "set-cookie").map(|(_, value)| value.clone()).collect() }
}

/// The bytes a `Request`/`Response` carries, and whether they were read.
///
/// A body is **single-use**: the spec's `bodyUsed` becomes `true` on the
/// first reader, and a second read is a `TypeError`. That is why the
/// payload sits behind an `Rc<RefCell<..>>` with a `Cell<bool>` beside it
/// rather than being moved out: two variables holding the same response
/// observe one another's consumption, exactly as in JavaScript.
#[derive(Clone)]
pub enum SmeltBodyPayload {
    /// No body at all (`new Response()`, a GET request).
    Empty,
    /// A fully-buffered body: a string, bytes, or form data.
    Bytes(Vec<u8>),
    /// A body still arriving in chunks, in arrival order.
    ///
    /// This is the shape `node:http`'s `IncomingMessage` and a streamed
    /// `fetch` response need. Reading it concatenates the chunks;
    /// `ReadableStream` (not implemented yet) is the surface that will
    /// expose them one at a time.
    Stream(Vec<Vec<u8>>),
}

/// A single-use body with a JS reference identity.
#[derive(Clone)]
pub struct SmeltBody {
    id: usize,
    payload: ::std::rc::Rc<::std::cell::RefCell<SmeltBodyPayload>>,
    /// The spec's `bodyUsed`, shared by every clone of this handle.
    used: ::std::rc::Rc<::std::cell::Cell<bool>>,
    /// The `Content-Type` this body implies, when it implies one.
    ///
    /// The spec's "extract a body" step returns a body *and* a type, and
    /// the type is what a `Request`/`Response` constructor appends to the
    /// header list when the caller did not set one. A string body implies
    /// `text/plain;charset=UTF-8`; raw bytes and a stream imply nothing,
    /// which is why this is an `Option` rather than a default string.
    content_type: Option<String>,
}

impl PartialEq for SmeltBody { fn eq(&self, other: &Self) -> bool { self.peek_bytes() == other.peek_bytes() } }
impl ::std::fmt::Debug for SmeltBody { fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result { formatter.debug_struct("SmeltBody").field("used", &self.used.get()).field("len", &self.peek_bytes().len()).finish() } }
impl Default for SmeltBody { fn default() -> Self { Self::empty() } }

#[allow(dead_code)]
impl SmeltBody {
    /// An unused empty body with a fresh JS reference identity.
    pub fn empty() -> Self { Self::from_payload(SmeltBodyPayload::Empty) }
    /// A buffered body holding `text`'s UTF-8 bytes.
    ///
    /// Carries `text/plain;charset=UTF-8` as its implied type, which the
    /// holder's constructor appends when the caller set no `Content-Type`.
    pub fn from_text(text: &str) -> Self { let mut body = Self::from_payload(SmeltBodyPayload::Bytes(text.as_bytes().to_vec())); body.content_type = Some("text/plain;charset=UTF-8".to_owned()); body }
    /// A buffered body holding `bytes`.
    pub fn from_bytes(bytes: Vec<u8>) -> Self { Self::from_payload(SmeltBodyPayload::Bytes(bytes)) }
    /// A body from a blob's bytes, carrying the blob's MIME type.
    pub fn from_blob(bytes: Vec<u8>, blob_type: String) -> Self { let mut body = Self::from_payload(SmeltBodyPayload::Bytes(bytes)); if !blob_type.is_empty() { body.content_type = Some(blob_type); } body }
    /// A streaming body whose chunks arrive in order.
    pub fn from_chunks(chunks: Vec<Vec<u8>>) -> Self { Self::from_payload(SmeltBodyPayload::Stream(chunks)) }
    /// Take a source body: same payload, fresh used flag, source disturbed.
    pub fn take_from_source(source: &Self) -> Self {
        if !source.is_empty() { source.used.set(true); }
        Self { id: smelt_next_object_id(), payload: ::std::rc::Rc::clone(&source.payload), used: ::std::rc::Rc::new(::std::cell::Cell::new(false)), content_type: source.content_type.clone() }
    }
    /// Wrap a payload, unused, with a fresh identity.
    fn from_payload(payload: SmeltBodyPayload) -> Self { Self { id: smelt_next_object_id(), payload: ::std::rc::Rc::new(::std::cell::RefCell::new(payload)), used: ::std::rc::Rc::new(::std::cell::Cell::new(false)), content_type: None } }
    /// JS reference identity of this body.
    pub fn id(&self) -> usize { self.id }
    /// The spec's `bodyUsed`.
    pub fn body_used(&self) -> bool { self.used.get() }
    /// The `Content-Type` this body implies, when it implies one.
    pub fn content_type(&self) -> Option<String> { self.content_type.clone() }
    /// Whether there is no body at all (the spec's null body).
    pub fn is_empty(&self) -> bool { matches!(&*self.payload.borrow(), SmeltBodyPayload::Empty) }
    /// The body's bytes WITHOUT consuming it.
    ///
    /// Only for observers that the spec does not count as readers:
    /// equality, `Debug`, and cloning a response. Every source-visible
    /// reader goes through `take_bytes`.
    pub fn peek_bytes(&self) -> Vec<u8> {
        match &*self.payload.borrow() {
            SmeltBodyPayload::Empty => Vec::new(),
            SmeltBodyPayload::Bytes(bytes) => bytes.clone(),
            SmeltBodyPayload::Stream(chunks) => chunks.concat(),
        }
    }
    /// Consume the body, or fail the way the spec does.
    ///
    /// The first reader gets the bytes and sets `bodyUsed`; a second
    /// reader gets the spec's `TypeError: Body is unusable`. The error is
    /// a thrown JS value rather than a Rust panic, so source-level
    /// `try`/`catch` around a double read behaves as it does in Node.
    pub fn take_bytes(&self) -> Result<Vec<u8>, Box<dyn ::std::error::Error>> {
        if self.used.get() {
            return Err(Box::<dyn ::std::error::Error>::from("TypeError: Body is unusable: Body has already been read"));
        }
        self.used.set(true);
        Ok(self.peek_bytes())
    }
    /// `text()`: the body decoded as UTF-8, lossily, as the spec does.
    pub fn take_text(&self) -> Result<String, Box<dyn ::std::error::Error>> { Ok(String::from_utf8_lossy(&self.take_bytes()?).into_owned()) }
    /// A clone that shares neither the bytes nor the used flag.
    ///
    /// This is `Response.clone()`: the spec gives the clone its own
    /// unread body, so reading one must not consume the other. `Clone`
    /// (the Rust trait) is the *handle* copy and shares both, which is
    /// what assigning a response to another variable does.
    pub fn tee(&self) -> Self { let mut body = Self::from_payload(self.payload.borrow().clone()); body.content_type = self.content_type.clone(); body }
}

/// A WHATWG `Response`: a status line, a header list, and a body.
///
/// The status line and headers are plain fields because the spec makes
/// them immutable on a response, so there is nothing for a shared cell to
/// coordinate. The BODY is the mutable part — reading it is observable
/// through every handle — and `SmeltBody` owns that sharing, which is why
/// this struct does not wrap itself in another `Rc<RefCell<..>>`.
#[derive(Clone)]
pub struct SmeltResponse {
    id: usize,
    status: f64,
    status_text: String,
    headers: SmeltHeaders,
    body: SmeltBody,
}

impl PartialEq for SmeltResponse { fn eq(&self, other: &Self) -> bool { self.status == other.status && self.status_text == other.status_text && self.headers == other.headers && self.body == other.body } }
impl ::std::fmt::Debug for SmeltResponse { fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result { formatter.debug_struct("SmeltResponse").field("status", &self.status).field("statusText", &self.status_text).field("headers", &self.headers).field("body", &self.body).finish() } }
impl Default for SmeltResponse { fn default() -> Self { Self::new() } }

#[allow(dead_code)]
impl SmeltResponse {
    /// `new Response()`: 200, empty reason phrase, no body.
    ///
    /// 200 is the spec's default status, and the default reason phrase is
    /// the EMPTY string, not `"OK"` — `new Response().statusText` is `""`
    /// in Node. Filling in a phrase here would invent an observable value.
    pub fn new() -> Self { Self::from_parts(200.0, String::new(), SmeltHeaders::new(), SmeltBody::empty()) }
    /// Assemble a response with a fresh JS reference identity.
    ///
    /// A body that implies a `Content-Type` adds it to the header list
    /// unless the caller already set one — the spec's "extract a body"
    /// step, which is why `new Response('hi').headers.get('content-type')`
    /// is `text/plain;charset=UTF-8` and not `null`.
    pub fn from_parts(status: f64, status_text: String, headers: SmeltHeaders, body: SmeltBody) -> Self {
        if let Some(content_type) = body.content_type() && !headers.has("content-type") {
            headers.append("content-type", &content_type);
        }
        Self { id: smelt_next_object_id(), status, status_text, headers, body }
    }
    /// JS reference identity of this response.
    pub fn id(&self) -> usize { self.id }
    /// `status`.
    pub fn status(&self) -> f64 { self.status }
    /// `statusText`.
    pub fn status_text(&self) -> String { self.status_text.clone() }
    /// `ok`: the spec derives it from the status, so this does too.
    ///
    /// Storing it would let it drift from `status`; deriving cannot.
    pub fn ok(&self) -> bool { self.status >= 200.0 && self.status <= 299.0 }
    /// `headers`.
    ///
    /// The same header list, not a copy: `Headers` is a reference object,
    /// so two reads of `response.headers` observe one another.
    pub fn headers(&self) -> SmeltHeaders { self.headers.clone() }
    /// `bodyUsed`.
    pub fn body_used(&self) -> bool { self.body.body_used() }
    /// The response's body handle.
    pub fn body(&self) -> SmeltBody { self.body.clone() }
    /// `text()`: the body decoded as UTF-8, consuming it.
    ///
    /// Fallible for the spec's reason: a second read is a `TypeError`.
    pub fn take_text(&self) -> Result<String, Box<dyn ::std::error::Error>> { self.body.take_text() }
    /// `clone()`: a response whose body is independently readable.
    ///
    /// The spec's `clone()` tees the body, so reading one side must not
    /// consume the other. It is therefore NOT Rust's `Clone`, which copies
    /// the handle and keeps one shared body — that is what assigning a
    /// response to a second variable does, and both spellings are needed.
    ///
    /// The header list is copied too: the clone's headers are its own.
    pub fn tee(&self) -> Self { Self::from_parts(self.status, self.status_text.clone(), SmeltHeaders::from_pairs(self.headers.entries_in_insertion_order()), self.body.tee()) }
}

// @smelt:prelude-end — generated program below
fn main() {
    let _smelt_tmp_7: ::std::collections::HashMap<String, String>;
    let _smelt_tmp_1: SmeltList<String> = Into::<SmeltList<_>>::into(SmeltList::from({ let smelt_list_items: Vec<String> = vec!["x-token".to_owned(), "from-headers".to_owned()]; smelt_list_items }));
    let _smelt_tmp_2: SmeltList<SmeltList<String>> = Into::<SmeltList<_>>::into(SmeltList::from({ let smelt_list_items: Vec<SmeltList<String>> = vec![_smelt_tmp_1.clone()]; smelt_list_items }));
    let _smelt_tmp_3: SmeltHeaders = SmeltHeaders::from_pairs(_smelt_tmp_2.to_vec().into_iter().filter_map(|smelt_pair| { let smelt_pair = smelt_pair.to_vec(); Some((smelt_pair.first()?.clone(), smelt_pair.get(1)?.clone())) }).collect::<Vec<(String, String)>>());
    let preset: SmeltHeaders = _smelt_tmp_3;
    let _smelt_tmp_4: SmeltResponse = make(Some(preset), None::<::std::collections::HashMap<String, String>>);
    let _smelt_tmp_5: String = show(_smelt_tmp_4);
    let _ = { println!("{}", _smelt_tmp_5); };
    _smelt_tmp_7 = ::std::collections::HashMap::from([("x-token".to_owned(), "from-record".to_owned())]);
    let _smelt_tmp_8: SmeltResponse = make(None::<SmeltHeaders>, Some(_smelt_tmp_7));
    let _smelt_tmp_9: String = show(_smelt_tmp_8);
    let _ = { println!("{}", _smelt_tmp_9); };
    let _smelt_tmp_11: SmeltResponse = make(None::<SmeltHeaders>, None::<::std::collections::HashMap<String, String>>);
    let _smelt_tmp_12: String = show(_smelt_tmp_11);
    let _ = { println!("{}", _smelt_tmp_12); };
    return;
}

// ==== source_main.rs
// @generated by smelt. Do not edit by hand.
// source: <example>/src/main.ts
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

use super::*;

pub(crate) fn make(preferred: Option<SmeltHeaders>, extra: Option<::std::collections::HashMap<String, String>>) -> SmeltResponse {
    let _smelt_tmp_2: Option<SmeltHeaders> = extra.clone().map(|value| SmeltHeaders::from_pairs(value.iter().map(|(smelt_name, smelt_value)| (smelt_name.clone(), smelt_value.clone())).collect::<Vec<(String, String)>>()));
    let _smelt_tmp_3: Option<SmeltHeaders> = preferred.clone().clone().or(_smelt_tmp_2);
    let _smelt_tmp_4: SmeltResponse = SmeltResponse::from_parts(201.0, String::new(), match _smelt_tmp_3 { Some(smelt_init_headers) => SmeltHeaders::from_pairs(smelt_init_headers.entries_sorted()), None => SmeltHeaders::new() }, SmeltBody::from_text(&"ok".to_owned()));
    return _smelt_tmp_4;
}

pub(crate) fn show(response: SmeltResponse) -> String {
    let _smelt_tmp_1: f64 = response.clone().status();
    let _smelt_tmp_2: String = "".to_owned() + &smelt_number_to_string(_smelt_tmp_1);
    let _smelt_tmp_3: String = _smelt_tmp_2 + &":".to_owned();
    let _smelt_tmp_4: SmeltHeaders = response.clone().headers();
    let _smelt_tmp_5: Option<String> = _smelt_tmp_4.get(&"x-token".to_owned());
    let _smelt_tmp_6: String = _smelt_tmp_5.clone().unwrap_or("-".to_owned());
    let _smelt_tmp_7: String = _smelt_tmp_3 + &_smelt_tmp_6;
    return _smelt_tmp_7;
}
