// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

#[derive(Clone, Debug, Default)]
struct Point {
    x: f64,
    y: f64,
}

// @smelt:prelude-end — generated program below

fn main() {
    let mut p: Point;
    let mut _smelt_tmp_1: Point = Point::new(2.0, 3.0);
    p = _smelt_tmp_1;
    let _ = { println!("{}", p.x.clone()); };
    return;
}

impl Point {
    fn new(x: f64, y: f64) -> Self {
    let mut this: Self = Point { x: 0.0, y: 0.0 };
    this.x = x.clone();
    this.y = y.clone();
    return this;
    }
}
