// @generated by smelt. Do not edit by hand.

#[derive(Clone, Debug)]
struct Point {
    x: f64,
    y: f64,
}


fn main() {
    let mut _smelt_tmp_1: Point = Point::new(2.0, 3.0);
    let mut p: Point = _smelt_tmp_1.clone();
    let _smelt_tmp_2: () = { println!("{}", p.x.clone()); };
}

impl Point {
    fn new(arg_1: f64, arg_2: f64) -> Self {
    let mut this: Point = Point { x: 0.0, y: 0.0 };
    this.x = arg_1.clone();
    this.y = arg_2.clone();
    return this;
    }
}
