// @generated by smelt. Do not edit by hand.

fn add(arg_0: f64, arg_1: f64) -> f64 {
    let _smelt_tmp_2: f64 = arg_0.clone() + arg_1.clone();
    return _smelt_tmp_2.clone();
}

fn main() {
    let value: f64 = 4.0;
    let _smelt_tmp_1: f64 = value.clone() + 1.0;
    let _smelt_tmp_2: f64 = add(2.0, 3.0);
    let _smelt_tmp_3: () = { println!("{} {} {}", "sum".to_owned(), _smelt_tmp_1.clone(), _smelt_tmp_2.clone()); };
}
