// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

#[path = "source_main.rs"]
mod __smelt_module_source_main;
pub(crate) use __smelt_module_source_main::*;


// @smelt:prelude-end — generated program below
fn main() {
    let value: f64 = 4.0;
    let _smelt_tmp_1: f64 = value + 1.0;
    let _smelt_tmp_2: f64 = add(2.0, 3.0);
    let _ = { println!("{} {} {}", "sum".to_owned(), _smelt_tmp_1, _smelt_tmp_2); };
    return;
}

// ==== source_main.rs
// @generated by smelt. Do not edit by hand.
// source: <example>/src/main.ts
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

use super::*;

pub(crate) fn add(a: f64, b: f64) -> f64 {
    let _smelt_tmp_2: f64 = a + b;
    return _smelt_tmp_2;
}
