// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

fn main() {
    let mut _smelt_tmp_2: bool;
    let mut _smelt_tmp_3: f64;
    let mut _smelt_tmp_4: f64;
    let mut sum: f64 = 0.0;
    let mut i: f64 = 0.0;
    loop {
    _smelt_tmp_2 = i.clone() < 4.0;
    if !(_smelt_tmp_2.clone()) { break; }
    _smelt_tmp_3 = sum.clone() + i.clone();
    sum = _smelt_tmp_3.clone();
    _smelt_tmp_4 = i.clone() + 1.0;
    i = _smelt_tmp_4.clone();
    }
    let _ = { println!("{}", sum.clone()); };
    return;
}
