// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

#[derive(Clone, Debug, Default)]
struct Named {
    name: String,
}

#[derive(Clone, Debug, Default)]
struct User {
    name: String,
}


fn main() {
    let mut _smelt_tmp_1: User = User::new("Ada".to_owned());
    let mut user: User = _smelt_tmp_1.clone();
    let _smelt_tmp_2: String = user.label("Hi ".to_owned());
    let _smelt_tmp_3: () = { println!("{}", _smelt_tmp_2.clone()); };
}

impl User {
    fn new(name: String) -> Self {
    let mut this: Self = User { name: String::new() };
    this.name = name.clone();
    return this;
    }
    fn label(&self, prefix: String) -> String {
    let _smelt_tmp_2: String = prefix.clone() + &self.name.clone();
    return _smelt_tmp_2.clone();
    }
}
