// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

#[derive(Clone)]
#[allow(dead_code)]
struct Named {
    name: String,
    label: ::std::rc::Rc<dyn Fn(String) -> String>,
}
impl Default for Named {
    fn default() -> Self {
        Self {
            name: String::new(),
            label: { let smelt_default_callback: ::std::rc::Rc<dyn Fn(String) -> String> = ::std::rc::Rc::new(move |arg0: String| -> String { String::new() }); smelt_default_callback },
        }
    }
}
impl ::std::fmt::Debug for Named {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        formatter.debug_struct("Named").finish_non_exhaustive()
    }
}

#[derive(Clone, Debug, Default)]
struct User {
    name: String,
}

// @smelt:prelude-end — generated program below

fn main() {
    let user: User;
    let _smelt_tmp_1: User = User::new("Ada".to_owned());
    user = _smelt_tmp_1;
    let _smelt_tmp_2: String = user.label("Hi ".to_owned());
    let _ = { println!("{}", _smelt_tmp_2); };
    return;
}

impl User {
    fn new(name: String) -> Self {
    let mut this: Self = User { name: String::new() };
    this.name = name.clone();
    return this;
    }
    fn label(&self, prefix: String) -> String {
    let _smelt_tmp_2: String = prefix.clone() + &self.name.clone();
    return _smelt_tmp_2;
    }
}
