//! Declaration stub emission for TypeScript and Python LSPs.

use smelt_hir::{Crate, Function, Item, ModuleId, Type};
use std::{fmt::Write as _, fs, path::Path};

/// Append formatted text to a `String` buffer.
fn push_fmt(out: &mut String, args: std::fmt::Arguments<'_>) {
    let _ignored = out.write_fmt(args);
}

/// Emit `.d.ts` and `.pyi` files next to each lowered source module.
///
/// # Errors
///
/// Returns an error if any declaration file cannot be written.
pub fn emit_type_declarations(
    krate: &Crate,
    modules: &[(String, ModuleId)],
) -> Result<(), Box<dyn std::error::Error>> {
    for (path, module_id) in modules {
        if is_declaration_path(path) {
            continue;
        }
        let source_path = Path::new(path);
        let mut typescript_path = source_path.to_path_buf();
        typescript_path.set_extension("d.ts");
        fs::write(typescript_path, typescript_declaration(krate, *module_id))?;

        let mut python_path = source_path.to_path_buf();
        python_path.set_extension("pyi");
        fs::write(python_path, python_declaration(krate, *module_id))?;
    }
    Ok(())
}

/// Return whether a path is already a declaration/stub file.
fn is_declaration_path(path: &str) -> bool {
    Path::new(path)
        .file_name()
        .and_then(|name| name.to_str())
        .is_some_and(|file_name| {
            let lower_name = file_name.to_ascii_lowercase();
            lower_name.ends_with(".d.ts")
                || lower_name.ends_with(".d.mts")
                || lower_name.ends_with(".d.cts")
        })
        || Path::new(path)
            .extension()
            .is_some_and(|extension| extension.eq_ignore_ascii_case("pyi"))
}

/// Format a TypeScript declaration file for one HIR module.
#[must_use]
#[expect(
    clippy::too_many_lines,
    reason = "declaration formatting keeps the TypeScript item cases together"
)]
fn typescript_declaration(krate: &Crate, module_id: ModuleId) -> String {
    let Some(module_idx) = usize::try_from(module_id.0).ok() else {
        return String::new();
    };
    let Some(module) = krate.modules.get(module_idx) else {
        return String::new();
    };
    let mut out = String::new();
    out.push_str("// Generated by smelt. Do not edit.\n\n");
    for item_id in &module.items {
        let Some(item_idx) = usize::try_from(item_id.0).ok() else {
            continue;
        };
        let Some(item) = krate.items.get(item_idx) else {
            continue;
        };
        match item {
            Item::Function(function)
                if matches!(function.owner, smelt_hir::FunctionOwner::Module) =>
            {
                let params = function
                    .params
                    .iter()
                    .map(|param| {
                        format!(
                            "{}: {}",
                            symbol_name(krate, param.name),
                            ts_type(krate, param.ty)
                        )
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                push_fmt(
                    &mut out,
                    format_args!(
                        "export declare function {}({params}): {};\n",
                        symbol_name(krate, function.name),
                        ts_type(krate, function.return_ty)
                    ),
                );
            }
            Item::Class(class) => {
                push_fmt(
                    &mut out,
                    format_args!(
                        "export declare class {} {{\n",
                        symbol_name(krate, class.name)
                    ),
                );
                for field in &class.fields {
                    push_fmt(
                        &mut out,
                        format_args!(
                            "  {}: {};\n",
                            ts_property_name(symbol_name(krate, field.name)),
                            ts_type(krate, field.ty)
                        ),
                    );
                }
                out.push_str("}\n");
            }
            Item::Interface(interface) => {
                push_fmt(
                    &mut out,
                    format_args!(
                        "export interface {} {{\n",
                        symbol_name(krate, interface.name)
                    ),
                );
                for field in &interface.fields {
                    push_fmt(
                        &mut out,
                        format_args!(
                            "  {}: {};\n",
                            ts_property_name(symbol_name(krate, field.name)),
                            ts_type(krate, field.ty)
                        ),
                    );
                }
                for method in &interface.methods {
                    let params = method
                        .params
                        .iter()
                        .map(|param| {
                            format!(
                                "{}: {}",
                                symbol_name(krate, param.name),
                                ts_type(krate, param.ty)
                            )
                        })
                        .collect::<Vec<_>>()
                        .join(", ");
                    push_fmt(
                        &mut out,
                        format_args!(
                            "  {}({params}): {};\n",
                            ts_property_name(symbol_name(krate, method.name)),
                            ts_type(krate, method.return_ty)
                        ),
                    );
                }
                out.push_str("}\n");
            }
            Item::TypeAlias(alias) => {
                let type_params = if alias.type_params.is_empty() {
                    String::new()
                } else {
                    format!(
                        "<{}>",
                        alias
                            .type_params
                            .iter()
                            .map(|param| symbol_name(krate, param.name))
                            .collect::<Vec<_>>()
                            .join(", ")
                    )
                };
                push_fmt(
                    &mut out,
                    format_args!(
                        "export type {}{} = {};\n",
                        symbol_name(krate, alias.name),
                        type_params,
                        ts_type(krate, alias.ty)
                    ),
                );
            }
            Item::Function(_) | Item::Const(_) | Item::MutableGlobal(_) => {}
        }
    }
    out
}

/// Format a Python stub file for one HIR module.
#[must_use]
fn python_declaration(krate: &Crate, module_id: ModuleId) -> String {
    let Some(module_idx) = usize::try_from(module_id.0).ok() else {
        return String::new();
    };
    let Some(module) = krate.modules.get(module_idx) else {
        return String::new();
    };
    let mut out = String::new();
    out.push_str("# Generated by smelt. Do not edit.\n\n");
    for item_id in &module.items {
        let Some(item_idx) = usize::try_from(item_id.0).ok() else {
            continue;
        };
        let Some(item) = krate.items.get(item_idx) else {
            continue;
        };
        match item {
            Item::Function(function)
                if matches!(function.owner, smelt_hir::FunctionOwner::Module) =>
            {
                write_python_function(krate, function, &mut out);
            }
            Item::Class(class) => {
                push_fmt(
                    &mut out,
                    format_args!("class {}:\n", symbol_name(krate, class.name)),
                );
                if class.fields.is_empty() && class.methods.is_empty() {
                    out.push_str("    ...\n");
                } else {
                    for field in &class.fields {
                        push_fmt(
                            &mut out,
                            format_args!(
                                "    {}: {}\n",
                                symbol_name(krate, field.name),
                                py_type(krate, field.ty)
                            ),
                        );
                    }
                }
            }
            Item::Function(_)
            | Item::Interface(_)
            | Item::TypeAlias(_)
            | Item::Const(_)
            | Item::MutableGlobal(_) => {}
        }
    }
    out
}

/// Append a Python function signature to a stub file.
fn write_python_function(krate: &Crate, function: &Function, out: &mut String) {
    let params = function
        .params
        .iter()
        .map(|param| {
            format!(
                "{}: {}",
                symbol_name(krate, param.name),
                py_type(krate, param.ty)
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    push_fmt(
        out,
        format_args!(
            "def {}({params}) -> {}: ...\n",
            symbol_name(krate, function.name),
            py_type(krate, function.return_ty)
        ),
    );
}

/// Resolve a symbol to display text.
fn symbol_name(krate: &Crate, symbol: smelt_hir::Symbol) -> &str {
    krate
        .names
        .get(symbol)
        .or_else(|| krate.symbols.get(symbol))
        .unwrap_or("_")
}

/// Render a TypeScript class/interface member name safely.
fn ts_property_name(name: &str) -> String {
    if is_ts_identifier_name(name) && !is_ts_reserved_property_name(name) {
        return name.to_owned();
    }
    format!("{name:?}")
}

/// Return whether text can be emitted as a bare TypeScript identifier.
fn is_ts_identifier_name(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    (first == '_' || first == '$' || first.is_ascii_alphabetic())
        && chars.all(|ch| ch == '_' || ch == '$' || ch.is_ascii_alphanumeric())
}

/// Return whether a property should be quoted in declaration output.
fn is_ts_reserved_property_name(name: &str) -> bool {
    matches!(
        name,
        "break"
            | "case"
            | "catch"
            | "class"
            | "const"
            | "continue"
            | "debugger"
            | "default"
            | "delete"
            | "do"
            | "else"
            | "export"
            | "extends"
            | "finally"
            | "for"
            | "function"
            | "if"
            | "import"
            | "in"
            | "instanceof"
            | "new"
            | "return"
            | "super"
            | "switch"
            | "this"
            | "throw"
            | "try"
            | "typeof"
            | "var"
            | "void"
            | "while"
            | "with"
            | "yield"
    )
}

/// Render a HIR type as TypeScript.
fn ts_type(krate: &Crate, ty: smelt_hir::TypeId) -> String {
    match krate.types.get(ty) {
        Some(Type::Bool) => "boolean".to_owned(),
        Some(Type::Int | Type::Float) => "number".to_owned(),
        Some(Type::String) => "string".to_owned(),
        Some(Type::Unknown) | None => "unknown".to_owned(),
        Some(Type::Never) => "never".to_owned(),
        Some(Type::TypeParam { name } | Type::Class { name, .. }) => {
            symbol_name(krate, *name).to_owned()
        }
        Some(Type::None) => "void".to_owned(),
        Some(Type::List(item) | Type::Set(item)) => {
            format!("Array<{}>", ts_type(krate, *item))
        }
        Some(Type::Dict(key, value)) => {
            format!(
                "Record<{}, {}>",
                ts_type(krate, *key),
                ts_type(krate, *value)
            )
        }
        Some(Type::JsMap(key, value)) => {
            format!("Map<{}, {}>", ts_type(krate, *key), ts_type(krate, *value))
        }
        Some(Type::Tuple(items)) => {
            let tuple_items = items
                .iter()
                .map(|item| ts_type(krate, *item))
                .collect::<Vec<_>>()
                .join(", ");
            format!("[{tuple_items}]")
        }
        Some(Type::Optional(item)) => format!("{} | null", ts_union_member_type(krate, *item)),
        Some(Type::Union(items)) => items
            .iter()
            .map(|item| ts_union_member_type(krate, *item))
            .collect::<Vec<_>>()
            .join(" | "),
        Some(Type::Function(function)) => {
            let params = function
                .params
                .iter()
                .map(|param| ts_type(krate, *param))
                .collect::<Vec<_>>()
                .join(", ");
            format!("({params}) => {}", ts_type(krate, function.return_ty))
        }
        Some(Type::Future(item)) => format!("Promise<{}>", ts_type(krate, *item)),
        Some(Type::Generator {
            is_async,
            yield_ty,
            return_ty,
            next_ty,
        }) => format!(
            "{}Generator<{}, {}, {}>",
            if *is_async { "Async" } else { "" },
            ts_type(krate, *yield_ty),
            ts_type(krate, *return_ty),
            ts_type(krate, *next_ty)
        ),
        Some(Type::GeneratorResult {
            yield_ty,
            return_ty,
        }) => format!(
            "IteratorResult<{}, {}>",
            ts_type(krate, *yield_ty),
            ts_type(krate, *return_ty)
        ),
    }
}

/// Render a TypeScript type in a union member position.
fn ts_union_member_type(krate: &Crate, ty: smelt_hir::TypeId) -> String {
    match krate.types.get(ty) {
        Some(Type::Function(_)) => format!("({})", ts_type(krate, ty)),
        _ => ts_type(krate, ty),
    }
}

/// Render a HIR type as Python.
fn py_type(krate: &Crate, ty: smelt_hir::TypeId) -> String {
    match krate.types.get(ty) {
        Some(Type::Bool) => "bool".to_owned(),
        Some(Type::Int) => "int".to_owned(),
        Some(Type::Float) => "float".to_owned(),
        Some(Type::String) => "str".to_owned(),
        Some(Type::Unknown) | None => "typing.Any".to_owned(),
        Some(Type::Never) => "typing.NoReturn".to_owned(),
        Some(Type::TypeParam { name } | Type::Class { name, .. }) => {
            symbol_name(krate, *name).to_owned()
        }
        Some(Type::None) => "None".to_owned(),
        Some(Type::List(item)) => format!("list[{}]", py_type(krate, *item)),
        Some(Type::Set(item)) => format!("set[{}]", py_type(krate, *item)),
        Some(Type::Dict(key, value) | Type::JsMap(key, value)) => {
            format!("dict[{}, {}]", py_type(krate, *key), py_type(krate, *value))
        }
        Some(Type::Tuple(items)) => {
            let tuple_items = items
                .iter()
                .map(|item| py_type(krate, *item))
                .collect::<Vec<_>>()
                .join(", ");
            format!("tuple[{tuple_items}]")
        }
        Some(Type::Optional(item)) => format!("{} | None", py_type(krate, *item)),
        Some(Type::Union(items)) => items
            .iter()
            .map(|item| py_type(krate, *item))
            .collect::<Vec<_>>()
            .join(" | "),
        Some(Type::Function(_)) => "typing.Callable".to_owned(),
        Some(Type::Future(item)) => format!("typing.Awaitable[{}]", py_type(krate, *item)),
        Some(Type::Generator {
            is_async,
            yield_ty,
            return_ty,
            next_ty,
        }) => format!(
            "typing.{}Generator[{}, {}, {}]",
            if *is_async { "Async" } else { "" },
            py_type(krate, *yield_ty),
            py_type(krate, *next_ty),
            py_type(krate, *return_ty)
        ),
        Some(Type::GeneratorResult {
            yield_ty,
            return_ty,
        }) => format!(
            "typing.Union[{}, {}]",
            py_type(krate, *yield_ty),
            py_type(krate, *return_ty)
        ),
    }
}
