// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

/// `Number::toString(value, 10)`: JavaScript's number formatting.
///
/// Exponential notation at `n > 21` and `n <= -6`, where `n` is the
/// decimal exponent of the shortest round-trip digit string — which is
/// what Rust's `{:e}` already produces.
fn smelt_number_to_string<N: ::std::borrow::Borrow<f64>>(value: N) -> String {
    let value = *value.borrow();
    if value.is_nan() { return "NaN".to_owned(); }
    if value == 0.0 { return "0".to_owned(); }
    if value < 0.0 { return format!("-{}", smelt_number_to_string(-value)); }
    if value.is_infinite() { return "Infinity".to_owned(); }
    let exponential = format!("{value:e}");
    let (mantissa, exponent) = exponential.split_once('e').unwrap_or((exponential.as_str(), "0"));
    let digits: String = mantissa.chars().filter(char::is_ascii_digit).collect();
    let k = i32::try_from(digits.len()).unwrap_or(i32::MAX);
    let n = exponent.parse::<i32>().unwrap_or(0) + 1;
    if k <= n && n <= 21 {
        let zeros = usize::try_from(n - k).unwrap_or(0);
        return digits + &"0".repeat(zeros);
    }
    if 0 < n && n <= 21 {
        let split = usize::try_from(n).unwrap_or(0);
        return format!("{}.{}", &digits[..split], &digits[split..]);
    }
    if -6 < n && n <= 0 {
        let zeros = usize::try_from(-n).unwrap_or(0);
        return format!("0.{}{}", "0".repeat(zeros), digits);
    }
    let sign = if n - 1 < 0 { '-' } else { '+' };
    let magnitude = (n - 1).abs();
    if k == 1 { return format!("{digits}e{sign}{magnitude}"); }
    format!("{}.{}e{sign}{magnitude}", &digits[..1], &digits[1..])
}

/// `console.log`'s number formatting: the spec's rule, but `-0` prints `-0`.
fn smelt_console_number<N: ::std::borrow::Borrow<f64>>(value: N) -> String { let value = *value.borrow(); if value == 0.0 && value.is_sign_negative() { return "-0".to_owned(); } smelt_number_to_string(value) }

thread_local! {
    static SMELT_NEXT_OBJECT_ID: ::std::cell::Cell<usize> = const { ::std::cell::Cell::new(1) };
}

#[allow(dead_code)]
fn smelt_next_object_id() -> usize {
    SMELT_NEXT_OBJECT_ID.with(|next| { let id = next.get(); next.set(id.saturating_add(1)); id })
}

/// A WHATWG `Headers` list: ordered name/value pairs, case-insensitive
/// names, comma-joined reads, and the `Set-Cookie` carve-out.
#[derive(Clone)]
pub struct SmeltHeaders {
    id: usize,
    /// Lower-cased name and normalized value, in insertion order.
    entries: ::std::rc::Rc<::std::cell::RefCell<Vec<(String, String)>>>,
}

impl PartialEq for SmeltHeaders { fn eq(&self, other: &Self) -> bool { self.entries_sorted() == other.entries_sorted() } }
impl ::std::fmt::Debug for SmeltHeaders { fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result { formatter.debug_map().entries(self.entries_sorted()).finish() } }
impl Default for SmeltHeaders { fn default() -> Self { Self::new() } }

#[allow(dead_code)]
impl SmeltHeaders {
    /// An empty header list with a fresh JS reference identity.
    pub fn new() -> Self { Self { id: smelt_next_object_id(), entries: ::std::rc::Rc::new(::std::cell::RefCell::new(Vec::new())) } }
    /// JS reference identity of this header list.
    pub fn id(&self) -> usize { self.id }
    /// Build a header list from name/value pairs, appending in order.
    pub fn from_pairs(pairs: Vec<(String, String)>) -> Self { let headers = Self::new(); for (name, value) in pairs { headers.append(&name, &value); } headers }
    /// The spec's header-name normalization: lower-cased.
    fn normalize_name(name: &str) -> String { name.trim().to_ascii_lowercase() }
    /// The spec's header-value normalization: strip HTTP whitespace.
    fn normalize_value(value: &str) -> String { value.trim_matches(|ch| ch == ' ' || ch == '\t' || ch == '\r' || ch == '\n').to_owned() }
    /// `get(name)`: every value for the name, joined with `", "`.
    ///
    /// `None` is the source `null`: the name is not in the list. The
    /// return type is the source type, so no caller has to re-narrow it.
    pub fn get(&self, name: &str) -> Option<String> {
        let key = Self::normalize_name(name);
        let values: Vec<String> = self.entries.borrow().iter().filter(|(entry_name, _)| *entry_name == key).map(|(_, value)| value.clone()).collect();
        if values.is_empty() { None } else { Some(values.join(", ")) }
    }
    /// `has(name)`.
    pub fn has(&self, name: &str) -> bool { let key = Self::normalize_name(name); self.entries.borrow().iter().any(|(entry_name, _)| *entry_name == key) }
    /// `append(name, value)`: add a pair, keeping existing ones.
    pub fn append(&self, name: &str, value: &str) { self.entries.borrow_mut().push((Self::normalize_name(name), Self::normalize_value(value))); }
    /// `set(name, value)`: replace every value for the name.
    ///
    /// The first existing pair's position is kept, matching the spec's
    /// "set the value of the first such header and remove the others".
    pub fn set(&self, name: &str, value: &str) {
        let key = Self::normalize_name(name);
        let normalized = Self::normalize_value(value);
        let mut entries = self.entries.borrow_mut();
        let position = entries.iter().position(|(entry_name, _)| *entry_name == key);
        let Some(index) = position else { entries.push((key, normalized)); return; };
        entries[index] = (key.clone(), normalized);
        // Keep the first pair with this name (the one just written) and
        // drop the rest, as the spec's `set` does.
        let mut kept = false;
        entries.retain(|(entry_name, _)| { if *entry_name != key { return true; } let first = !kept; kept = true; first });
    }
    /// `delete(name)`: remove every pair with the name.
    pub fn delete(&self, name: &str) { let key = Self::normalize_name(name); self.entries.borrow_mut().retain(|(entry_name, _)| *entry_name != key); }
    /// The spec's iteration order: sorted by name, values combined.
    ///
    /// `set-cookie` is the exception the spec carves out: its values are
    /// never combined, so each cookie stays its own entry.
    pub fn entries_sorted(&self) -> Vec<(String, String)> {
        let entries = self.entries.borrow().clone();
        let mut names: Vec<String> = entries.iter().map(|(name, _)| name.clone()).collect();
        names.sort();
        names.dedup();
        let mut combined = Vec::new();
        for name in names {
            let values: Vec<String> = entries.iter().filter(|(entry_name, _)| *entry_name == name).map(|(_, value)| value.clone()).collect();
            if name == "set-cookie" {
                for value in values { combined.push((name.clone(), value)); }
            }
            else {
                combined.push((name.clone(), values.join(", ")));
            }
        }
        combined
    }
    /// The stored pairs, in insertion order, uncombined.
    ///
    /// NOT the spec's iteration order (`entries_sorted`), which sorts by
    /// name and comma-joins values. Copying a header list has to go
    /// through this instead: rebuilding from the combined view would turn
    /// two `Accept` headers into one, which a copy must not do.
    pub fn entries_in_insertion_order(&self) -> Vec<(String, String)> { self.entries.borrow().clone() }
    /// `keys()`: header names in iteration order.
    pub fn keys(&self) -> Vec<String> { self.entries_sorted().into_iter().map(|(name, _)| name).collect() }
    /// `values()`: header values in iteration order.
    pub fn values(&self) -> Vec<String> { self.entries_sorted().into_iter().map(|(_, value)| value).collect() }
    /// `getSetCookie()`: each `Set-Cookie` value, uncombined.
    pub fn get_set_cookie(&self) -> Vec<String> { self.entries.borrow().iter().filter(|(name, _)| name == "set-cookie").map(|(_, value)| value.clone()).collect() }
}

/// The bytes a `Request`/`Response` carries, and whether they were read.
///
/// A body is **single-use**: the spec's `bodyUsed` becomes `true` on the
/// first reader, and a second read is a `TypeError`. That is why the
/// payload sits behind an `Rc<RefCell<..>>` with a `Cell<bool>` beside it
/// rather than being moved out: two variables holding the same response
/// observe one another's consumption, exactly as in JavaScript.
#[derive(Clone)]
pub enum SmeltBodyPayload {
    /// No body at all (`new Response()`, a GET request).
    Empty,
    /// A fully-buffered body: a string, bytes, or form data.
    Bytes(Vec<u8>),
    /// A body still arriving in chunks, in arrival order.
    ///
    /// This is the shape `node:http`'s `IncomingMessage` and a streamed
    /// `fetch` response need. Reading it concatenates the chunks;
    /// `ReadableStream` (not implemented yet) is the surface that will
    /// expose them one at a time.
    Stream(Vec<Vec<u8>>),
}

/// A single-use body with a JS reference identity.
#[derive(Clone)]
pub struct SmeltBody {
    id: usize,
    payload: ::std::rc::Rc<::std::cell::RefCell<SmeltBodyPayload>>,
    /// The spec's `bodyUsed`, shared by every clone of this handle.
    used: ::std::rc::Rc<::std::cell::Cell<bool>>,
    /// The `Content-Type` this body implies, when it implies one.
    ///
    /// The spec's "extract a body" step returns a body *and* a type, and
    /// the type is what a `Request`/`Response` constructor appends to the
    /// header list when the caller did not set one. A string body implies
    /// `text/plain;charset=UTF-8`; raw bytes and a stream imply nothing,
    /// which is why this is an `Option` rather than a default string.
    content_type: Option<String>,
}

impl PartialEq for SmeltBody { fn eq(&self, other: &Self) -> bool { self.peek_bytes() == other.peek_bytes() } }
impl ::std::fmt::Debug for SmeltBody { fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result { formatter.debug_struct("SmeltBody").field("used", &self.used.get()).field("len", &self.peek_bytes().len()).finish() } }
impl Default for SmeltBody { fn default() -> Self { Self::empty() } }

#[allow(dead_code)]
impl SmeltBody {
    /// An unused empty body with a fresh JS reference identity.
    pub fn empty() -> Self { Self::from_payload(SmeltBodyPayload::Empty) }
    /// A buffered body holding `text`'s UTF-8 bytes.
    ///
    /// Carries `text/plain;charset=UTF-8` as its implied type, which the
    /// holder's constructor appends when the caller set no `Content-Type`.
    pub fn from_text(text: &str) -> Self { let mut body = Self::from_payload(SmeltBodyPayload::Bytes(text.as_bytes().to_vec())); body.content_type = Some("text/plain;charset=UTF-8".to_owned()); body }
    /// A buffered body holding `bytes`.
    pub fn from_bytes(bytes: Vec<u8>) -> Self { Self::from_payload(SmeltBodyPayload::Bytes(bytes)) }
    /// A body from a blob's bytes, carrying the blob's MIME type.
    pub fn from_blob(bytes: Vec<u8>, blob_type: String) -> Self { let mut body = Self::from_payload(SmeltBodyPayload::Bytes(bytes)); if !blob_type.is_empty() { body.content_type = Some(blob_type); } body }
    /// A streaming body whose chunks arrive in order.
    pub fn from_chunks(chunks: Vec<Vec<u8>>) -> Self { Self::from_payload(SmeltBodyPayload::Stream(chunks)) }
    /// Take a source body: same payload, fresh used flag, source disturbed.
    pub fn take_from_source(source: &Self) -> Self {
        if !source.is_empty() { source.used.set(true); }
        Self { id: smelt_next_object_id(), payload: ::std::rc::Rc::clone(&source.payload), used: ::std::rc::Rc::new(::std::cell::Cell::new(false)), content_type: source.content_type.clone() }
    }
    /// Wrap a payload, unused, with a fresh identity.
    fn from_payload(payload: SmeltBodyPayload) -> Self { Self { id: smelt_next_object_id(), payload: ::std::rc::Rc::new(::std::cell::RefCell::new(payload)), used: ::std::rc::Rc::new(::std::cell::Cell::new(false)), content_type: None } }
    /// JS reference identity of this body.
    pub fn id(&self) -> usize { self.id }
    /// The spec's `bodyUsed`.
    pub fn body_used(&self) -> bool { self.used.get() }
    /// The `Content-Type` this body implies, when it implies one.
    pub fn content_type(&self) -> Option<String> { self.content_type.clone() }
    /// Whether there is no body at all (the spec's null body).
    pub fn is_empty(&self) -> bool { matches!(&*self.payload.borrow(), SmeltBodyPayload::Empty) }
    /// The body's bytes WITHOUT consuming it.
    ///
    /// Only for observers that the spec does not count as readers:
    /// equality, `Debug`, and cloning a response. Every source-visible
    /// reader goes through `take_bytes`.
    pub fn peek_bytes(&self) -> Vec<u8> {
        match &*self.payload.borrow() {
            SmeltBodyPayload::Empty => Vec::new(),
            SmeltBodyPayload::Bytes(bytes) => bytes.clone(),
            SmeltBodyPayload::Stream(chunks) => chunks.concat(),
        }
    }
    /// Consume the body, or fail the way the spec does.
    ///
    /// The first reader gets the bytes and sets `bodyUsed`; a second
    /// reader gets the spec's `TypeError: Body is unusable`. The error is
    /// a thrown JS value rather than a Rust panic, so source-level
    /// `try`/`catch` around a double read behaves as it does in Node.
    pub fn take_bytes(&self) -> Result<Vec<u8>, Box<dyn ::std::error::Error>> {
        if self.used.get() {
            return Err(Box::<dyn ::std::error::Error>::from("TypeError: Body is unusable: Body has already been read"));
        }
        self.used.set(true);
        Ok(self.peek_bytes())
    }
    /// `text()`: the body decoded as UTF-8, lossily, as the spec does.
    pub fn take_text(&self) -> Result<String, Box<dyn ::std::error::Error>> { Ok(String::from_utf8_lossy(&self.take_bytes()?).into_owned()) }
    /// A clone that shares neither the bytes nor the used flag.
    ///
    /// This is `Response.clone()`: the spec gives the clone its own
    /// unread body, so reading one must not consume the other. `Clone`
    /// (the Rust trait) is the *handle* copy and shares both, which is
    /// what assigning a response to another variable does.
    pub fn tee(&self) -> Self { let mut body = Self::from_payload(self.payload.borrow().clone()); body.content_type = self.content_type.clone(); body }
}

/// A WHATWG `Response`: a status line, a header list, and a body.
///
/// The status line and headers are plain fields because the spec makes
/// them immutable on a response, so there is nothing for a shared cell to
/// coordinate. The BODY is the mutable part — reading it is observable
/// through every handle — and `SmeltBody` owns that sharing, which is why
/// this struct does not wrap itself in another `Rc<RefCell<..>>`.
#[derive(Clone)]
pub struct SmeltResponse {
    id: usize,
    status: f64,
    status_text: String,
    headers: SmeltHeaders,
    body: SmeltBody,
}

impl PartialEq for SmeltResponse { fn eq(&self, other: &Self) -> bool { self.status == other.status && self.status_text == other.status_text && self.headers == other.headers && self.body == other.body } }
impl ::std::fmt::Debug for SmeltResponse { fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result { formatter.debug_struct("SmeltResponse").field("status", &self.status).field("statusText", &self.status_text).field("headers", &self.headers).field("body", &self.body).finish() } }
impl Default for SmeltResponse { fn default() -> Self { Self::new() } }

#[allow(dead_code)]
impl SmeltResponse {
    /// `new Response()`: 200, empty reason phrase, no body.
    ///
    /// 200 is the spec's default status, and the default reason phrase is
    /// the EMPTY string, not `"OK"` — `new Response().statusText` is `""`
    /// in Node. Filling in a phrase here would invent an observable value.
    pub fn new() -> Self { Self::from_parts(200.0, String::new(), SmeltHeaders::new(), SmeltBody::empty()) }
    /// Assemble a response with a fresh JS reference identity.
    ///
    /// A body that implies a `Content-Type` adds it to the header list
    /// unless the caller already set one — the spec's "extract a body"
    /// step, which is why `new Response('hi').headers.get('content-type')`
    /// is `text/plain;charset=UTF-8` and not `null`.
    pub fn from_parts(status: f64, status_text: String, headers: SmeltHeaders, body: SmeltBody) -> Self {
        if let Some(content_type) = body.content_type() && !headers.has("content-type") {
            headers.append("content-type", &content_type);
        }
        Self { id: smelt_next_object_id(), status, status_text, headers, body }
    }
    /// JS reference identity of this response.
    pub fn id(&self) -> usize { self.id }
    /// `status`.
    pub fn status(&self) -> f64 { self.status }
    /// `statusText`.
    pub fn status_text(&self) -> String { self.status_text.clone() }
    /// `ok`: the spec derives it from the status, so this does too.
    ///
    /// Storing it would let it drift from `status`; deriving cannot.
    pub fn ok(&self) -> bool { self.status >= 200.0 && self.status <= 299.0 }
    /// `headers`.
    ///
    /// The same header list, not a copy: `Headers` is a reference object,
    /// so two reads of `response.headers` observe one another.
    pub fn headers(&self) -> SmeltHeaders { self.headers.clone() }
    /// `bodyUsed`.
    pub fn body_used(&self) -> bool { self.body.body_used() }
    /// The response's body handle.
    pub fn body(&self) -> SmeltBody { self.body.clone() }
    /// `text()`: the body decoded as UTF-8, consuming it.
    ///
    /// Fallible for the spec's reason: a second read is a `TypeError`.
    pub fn take_text(&self) -> Result<String, Box<dyn ::std::error::Error>> { self.body.take_text() }
    /// `clone()`: a response whose body is independently readable.
    ///
    /// The spec's `clone()` tees the body, so reading one side must not
    /// consume the other. It is therefore NOT Rust's `Clone`, which copies
    /// the handle and keeps one shared body — that is what assigning a
    /// response to a second variable does, and both spellings are needed.
    ///
    /// The header list is copied too: the clone's headers are its own.
    pub fn tee(&self) -> Self { Self::from_parts(self.status, self.status_text.clone(), SmeltHeaders::from_pairs(self.headers.entries_in_insertion_order()), self.body.tee()) }
}

#[allow(dead_code)]
struct Bag(::std::rc::Rc<::std::cell::RefCell<BagInner>>);
#[derive(Debug, Default)]
#[allow(dead_code)]
struct BagInner {
    prepared: Option<SmeltHeaders>,
    current: Option<SmeltHeaders>,
}
impl Clone for Bag {
    fn clone(&self) -> Self {
        Bag(::std::rc::Rc::clone(&self.0))
    }
}
impl PartialEq for Bag {
    fn eq(&self, other: &Self) -> bool {
        ::std::rc::Rc::ptr_eq(&self.0, &other.0)
    }
}
impl Default for Bag {
    fn default() -> Self {
        Bag(::std::rc::Rc::new(::std::cell::RefCell::new(BagInner::default())))
    }
}
impl ::std::fmt::Debug for Bag {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::std::fmt::Debug::fmt(&*self.0.borrow(), formatter)
    }
}

// @smelt:prelude-end — generated program below

fn main() {
    let bag: Bag;
    let mut maybe: Option<SmeltHeaders>;
    let mut __smelt_logical_2: SmeltHeaders;
    let __smelt_logical_value_3: SmeltHeaders;
    let ensured: SmeltHeaders;
    let mut __smelt_logical_5: SmeltHeaders;
    let __smelt_logical_value_6: SmeltHeaders;
    let again: SmeltHeaders;
    let mut text: String;
    let mut __smelt_logical_9: String;
    let __smelt_logical_value_10: String;
    let filled: String;
    let response: SmeltResponse;
    let _smelt_tmp_23: bool;
    let _smelt_tmp_24: SmeltHeaders;
    let _smelt_tmp_25: ();
    let _smelt_tmp_26: Option<String>;
    let _smelt_tmp_27: String;
    let _smelt_tmp_28: SmeltHeaders;
    let _smelt_tmp_29: Option<String>;
    let _smelt_tmp_30: String;
    let _smelt_tmp_32: bool;
    let _smelt_tmp_33: SmeltHeaders;
    let _smelt_tmp_34: Option<String>;
    let _smelt_tmp_35: String;
    let _smelt_tmp_37: bool;
    let _smelt_tmp_38: bool;
    let _smelt_tmp_40: ::std::collections::HashMap<String, String>;
    let _smelt_tmp_41: SmeltResponse;
    let _smelt_tmp_42: SmeltHeaders;
    let _smelt_tmp_13: Bag = Bag::new();
    bag = _smelt_tmp_13;
    let _smelt_tmp_14: String = bag.peek("x".to_owned());
    let _ = { println!("{}", _smelt_tmp_14); };
    let _ = bag.write("x".to_owned(), "1".to_owned());
    let _smelt_tmp_17: String = bag.peek("x".to_owned());
    let _smelt_tmp_18: String = bag.read("x".to_owned());
    let _ = { println!("{} {}", _smelt_tmp_17, _smelt_tmp_18); };
    let _ = bag.append_to("x".to_owned(), "2".to_owned());
    let _smelt_tmp_21: String = bag.read("x".to_owned());
    let _ = { println!("{}", _smelt_tmp_21); };
    maybe = None::<SmeltHeaders>;
    __smelt_logical_2 = SmeltHeaders::new();
    _smelt_tmp_23 = maybe.clone().is_none();
    if _smelt_tmp_23 {
    _smelt_tmp_24 = SmeltHeaders::new();
    __smelt_logical_value_3 = _smelt_tmp_24;
    maybe = Some(__smelt_logical_value_3.clone());
    __smelt_logical_2 = __smelt_logical_value_3;
    } else {
    __smelt_logical_2 = maybe.clone().clone().expect("optional value was absent after narrowing");
    }
    ensured = __smelt_logical_2;
    _smelt_tmp_25 = ensured.clone().set(&"y".to_owned(), &"3".to_owned());
    _smelt_tmp_26 = ensured.get(&"y".to_owned());
    _smelt_tmp_27 = _smelt_tmp_26.clone().unwrap_or("absent".to_owned());
    _smelt_tmp_28 = maybe.clone().clone().expect("optional value was absent after narrowing");
    _smelt_tmp_29 = _smelt_tmp_28.get(&"y".to_owned());
    _smelt_tmp_30 = _smelt_tmp_29.clone().unwrap_or("absent".to_owned());
    let _ = { println!("{} {}", _smelt_tmp_27, _smelt_tmp_30); };
    __smelt_logical_5 = SmeltHeaders::new();
    _smelt_tmp_32 = maybe.clone().is_none();
    if _smelt_tmp_32 {
    _smelt_tmp_33 = SmeltHeaders::new();
    __smelt_logical_value_6 = _smelt_tmp_33;
    maybe = Some(__smelt_logical_value_6.clone());
    __smelt_logical_5 = __smelt_logical_value_6;
    } else {
    __smelt_logical_5 = maybe.clone().expect("optional value was absent after narrowing");
    }
    again = __smelt_logical_5;
    _smelt_tmp_34 = again.get(&"y".to_owned());
    _smelt_tmp_35 = _smelt_tmp_34.clone().unwrap_or("absent".to_owned());
    let _ = { println!("{}", _smelt_tmp_35); };
    text = "".to_owned();
    __smelt_logical_9 = String::new();
    _smelt_tmp_37 = text.clone() != "".to_owned();
    _smelt_tmp_38 = !(_smelt_tmp_37);
    if _smelt_tmp_38 {
    __smelt_logical_value_10 = "fallback".to_owned();
    text = __smelt_logical_value_10.clone();
    __smelt_logical_9 = __smelt_logical_value_10;
    } else {
    __smelt_logical_9 = text.clone();
    }
    filled = __smelt_logical_9;
    let _ = { println!("{} {}", filled, text); };
    _smelt_tmp_40 = ::std::collections::HashMap::from([("x-from".to_owned(), "response".to_owned())]);
    _smelt_tmp_41 = SmeltResponse::from_parts(200.0, String::new(), SmeltHeaders::from_pairs(_smelt_tmp_40.iter().map(|(smelt_name, smelt_value)| (smelt_name.clone(), smelt_value.clone())).collect::<Vec<(String, String)>>()), SmeltBody::from_text(&"body".to_owned()));
    response = _smelt_tmp_41;
    _smelt_tmp_42 = response.headers();
    let _ = bag.adopt(_smelt_tmp_42);
    let _ = bag.write("x-added".to_owned(), "4".to_owned());
    let _smelt_tmp_45: String = bag.peek("x-from".to_owned());
    let _smelt_tmp_46: String = bag.peek("x-added".to_owned());
    let _ = { println!("{} {}", _smelt_tmp_45, _smelt_tmp_46); };
    return;
}

impl Bag {
    fn new() -> Self {
    let this: Self = Bag(::std::rc::Rc::new(::std::cell::RefCell::new(BagInner { prepared: None::<SmeltHeaders>, current: None::<SmeltHeaders> })));
    return this;
    }
    fn write(&self, name: String, value: String) -> () {
    let mut __smelt_logical_3: SmeltHeaders;
    let __smelt_logical_value_4: SmeltHeaders;
    let headers: Option<SmeltHeaders>;
    let mut _smelt_tmp_7: Option<SmeltHeaders>;
    let _smelt_tmp_8: bool;
    let _smelt_tmp_9: SmeltHeaders;
    let _smelt_tmp_10: SmeltHeaders;
    let _smelt_tmp_11: ();
    let _smelt_tmp_6: bool = !(self.0.borrow().current.clone().is_none());
    if _smelt_tmp_6 {
    _smelt_tmp_7 = self.0.borrow().current.clone();
    headers = _smelt_tmp_7;
    _smelt_tmp_10 = headers.clone().expect("optional value was absent after narrowing");
    _smelt_tmp_11 = _smelt_tmp_10.set(&name.clone(), &value.clone());
    return;
    } else {
    __smelt_logical_3 = SmeltHeaders::new();
    _smelt_tmp_8 = self.0.borrow().prepared.clone().is_none();
    if _smelt_tmp_8 {
    _smelt_tmp_9 = SmeltHeaders::new();
    __smelt_logical_value_4 = _smelt_tmp_9;
    self.0.borrow_mut().prepared = Some(__smelt_logical_value_4.clone());
    __smelt_logical_3 = __smelt_logical_value_4;
    } else {
    __smelt_logical_3 = self.0.borrow().prepared.clone().clone().expect("optional value was absent after narrowing");
    }
    _smelt_tmp_7 = Some(__smelt_logical_3);
    headers = _smelt_tmp_7;
    _smelt_tmp_10 = headers.clone().expect("optional value was absent after narrowing");
    _smelt_tmp_11 = _smelt_tmp_10.set(&name.clone(), &value.clone());
    return;
    }
    }
    fn peek(&self, name: String) -> String {
    let headers: Option<SmeltHeaders>;
    let mut _smelt_tmp_4: Option<SmeltHeaders>;
    let _smelt_tmp_5: bool;
    let mut _smelt_tmp_6: String;
    let _smelt_tmp_7: SmeltHeaders;
    let _smelt_tmp_8: Option<String>;
    let _smelt_tmp_9: String;
    let _smelt_tmp_3: bool = !(self.0.borrow().current.clone().is_none());
    let _smelt_tmp_4: Option<SmeltHeaders> = if _smelt_tmp_3 { self.0.borrow().current.clone() } else { self.0.borrow().prepared.clone() };
    headers = _smelt_tmp_4;
    _smelt_tmp_5 = !(headers.clone().is_none());
    let mut _smelt_tmp_6: String = String::new();
    if _smelt_tmp_5 {
    _smelt_tmp_7 = headers.clone().expect("optional value was absent after narrowing");
    _smelt_tmp_8 = _smelt_tmp_7.get(&name.clone());
    _smelt_tmp_9 = _smelt_tmp_8.clone().unwrap_or("absent".to_owned());
    _smelt_tmp_6 = _smelt_tmp_9;
    } else {
    _smelt_tmp_6 = "none".to_owned();
    }
    return _smelt_tmp_6;
    }
    fn append_to(&self, name: String, value: String) -> () {
    let _smelt_tmp_4: SmeltHeaders;
    let _smelt_tmp_5: ();
    let _smelt_tmp_3: bool = !(self.0.borrow().prepared.clone().is_none());
    if _smelt_tmp_3 {
    _smelt_tmp_4 = self.0.borrow().prepared.clone().clone().expect("optional value was absent after narrowing");
    _smelt_tmp_5 = _smelt_tmp_4.append(&name.clone(), &value.clone());
    }
    return;
    }
    fn read(&self, name: String) -> String {
    let _smelt_tmp_2: SmeltHeaders = self.0.borrow().prepared.clone().clone().expect("optional value was absent after narrowing");
    let _smelt_tmp_3: Option<String> = _smelt_tmp_2.get(&name.clone());
    let _smelt_tmp_4: String = _smelt_tmp_3.clone().unwrap_or("absent".to_owned());
    return _smelt_tmp_4;
    }
    fn adopt(&self, headers: SmeltHeaders) -> () {
    self.0.borrow_mut().current = Some(headers.clone());
    return;
    }
}
