// @generated by smelt. Do not edit by hand.
#![allow(dead_code, unused_variables)]

#[derive(Clone, Debug, PartialEq)]
pub enum SmeltUnknown {
    Null,
    Bool(bool),
    Number(f64),
    String(String),
    Array(Vec<SmeltUnknown>),
    Object(::std::collections::HashMap<String, SmeltUnknown>),
}

impl Default for SmeltUnknown {
    fn default() -> Self {
        Self::Null
    }
}

impl SmeltUnknown {
    /// Returns the JavaScript-style length for unknown string, array, and object values.
    pub fn len(&self) -> usize {
        match self {
            Self::String(value) => value.chars().count(),
            Self::Array(value) => value.len(),
            Self::Object(value) => value.len(),
            Self::Null | Self::Bool(_) | Self::Number(_) => 0,
        }
    }
}

impl ::std::fmt::Display for SmeltUnknown {
    fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match self {
            Self::Null => formatter.write_str("null"),
            Self::Bool(value) => write!(formatter, "{value}"),
            Self::Number(value) => write!(formatter, "{value}"),
            Self::String(value) => formatter.write_str(value),
            Self::Array(_) | Self::Object(_) => formatter.write_str("[object Object]"),
        }
    }
}

impl Eq for SmeltUnknown {}

impl ::std::hash::Hash for SmeltUnknown {
    fn hash<H: ::std::hash::Hasher>(&self, state: &mut H) {
        match self {
            Self::Null => 0_u8.hash(state),
            Self::Bool(value) => { 1_u8.hash(state); value.hash(state); }
            Self::Number(value) => { 2_u8.hash(state); value.to_bits().hash(state); }
            Self::String(value) => { 3_u8.hash(state); value.hash(state); }
            Self::Array(values) => { 4_u8.hash(state); values.hash(state); }
            Self::Object(values) => { 5_u8.hash(state); let mut entries = values.iter().collect::<Vec<_>>(); entries.sort_by(|left, right| left.0.cmp(right.0)); for (key, value) in entries { key.hash(state); value.hash(state); } }
        }
    }
}

impl PartialOrd for SmeltUnknown {
    fn partial_cmp(&self, other: &Self) -> Option<::std::cmp::Ordering> {
        match (self, other) {
            (Self::Number(left), Self::Number(right)) => left.partial_cmp(right),
            (Self::String(left), Self::String(right)) => Some(left.cmp(right)),
            (Self::Bool(left), Self::Bool(right)) => Some(left.cmp(right)),
            (Self::Null, Self::Null) => Some(::std::cmp::Ordering::Equal),
            (left, right) => Some(smelt_unknown_rank(left).cmp(&smelt_unknown_rank(right))),
        }
    }
}

fn smelt_unknown_rank(value: &SmeltUnknown) -> u8 {
    match value {
        SmeltUnknown::Null => 0,
        SmeltUnknown::Bool(_) => 1,
        SmeltUnknown::Number(_) => 2,
        SmeltUnknown::String(_) => 3,
        SmeltUnknown::Array(_) => 4,
        SmeltUnknown::Object(_) => 5,
    }
}

trait IntoSmeltUnknown {
    fn into_smelt_unknown(self) -> SmeltUnknown;
}

impl IntoSmeltUnknown for SmeltUnknown {
    fn into_smelt_unknown(self) -> SmeltUnknown {
        self
    }
}

impl IntoSmeltUnknown for bool {
    fn into_smelt_unknown(self) -> SmeltUnknown {
        SmeltUnknown::Bool(self)
    }
}

impl IntoSmeltUnknown for f64 {
    fn into_smelt_unknown(self) -> SmeltUnknown {
        SmeltUnknown::Number(self)
    }
}

impl IntoSmeltUnknown for i64 {
    fn into_smelt_unknown(self) -> SmeltUnknown {
        SmeltUnknown::Number(self as f64)
    }
}

impl IntoSmeltUnknown for String {
    fn into_smelt_unknown(self) -> SmeltUnknown {
        SmeltUnknown::String(self)
    }
}

trait SmeltIntoF64 {
    fn smelt_into_f64(self) -> f64;
}

impl SmeltIntoF64 for f64 {
    fn smelt_into_f64(self) -> f64 {
        self
    }
}

impl SmeltIntoF64 for SmeltUnknown {
    fn smelt_into_f64(self) -> f64 {
        match self {
            SmeltUnknown::Number(value) => value,
            _ => 0.0,
        }
    }
}

impl<T: IntoSmeltUnknown> IntoSmeltUnknown for Option<T> {
    fn into_smelt_unknown(self) -> SmeltUnknown {
        self.map_or(SmeltUnknown::Null, IntoSmeltUnknown::into_smelt_unknown)
    }
}

impl<T: IntoSmeltUnknown> IntoSmeltUnknown for Vec<T> {
    fn into_smelt_unknown(self) -> SmeltUnknown {
        SmeltUnknown::Array(self.into_iter().map(IntoSmeltUnknown::into_smelt_unknown).collect())
    }
}

impl<A: IntoSmeltUnknown, B: IntoSmeltUnknown> IntoSmeltUnknown for (A, B) {
    fn into_smelt_unknown(self) -> SmeltUnknown {
        SmeltUnknown::Array(vec![self.0.into_smelt_unknown(), self.1.into_smelt_unknown()])
    }
}

impl<K, T> IntoSmeltUnknown for ::std::collections::HashMap<K, T> where K: IntoSmeltUnknown + Eq + ::std::hash::Hash, T: IntoSmeltUnknown {
    fn into_smelt_unknown(self) -> SmeltUnknown {
        SmeltUnknown::Object(self.into_iter().map(|(key, value)| { let key = match key.into_smelt_unknown() { SmeltUnknown::String(value) => value, SmeltUnknown::Number(value) => value.to_string(), SmeltUnknown::Bool(value) => value.to_string(), SmeltUnknown::Null => "null".to_owned(), SmeltUnknown::Array(_) | SmeltUnknown::Object(_) => "[object Object]".to_owned() }; (key, value.into_smelt_unknown()) }).collect())
    }
}

#[derive(Clone, Debug, Default)]
struct Entity {
    id: String,
}

#[derive(Clone, Debug, Default)]
struct Named {
    id: String,
    name: Option<String>,
}

#[derive(Clone, Debug, Default)]
struct User {
    id: String,
}


fn main() {
    let mut _smelt_tmp_1: User = User::new("u1".to_owned());
    let mut user: User = _smelt_tmp_1.clone();
    let _smelt_tmp_2: () = { println!("{}", user.id.clone()); };
}

impl User {
    fn new(id: String) -> Self {
    let mut this: User = User { id: String::new() };
    this.id = id.clone();
    return this;
    }
}
