// @generated by smelt. Do not edit by hand.

#[derive(Clone, Debug)]
struct User {
    id: String,
}


fn main() {
    let mut _smelt_tmp_1: User = User::new("u1".to_owned());
    let mut user: User = _smelt_tmp_1.clone();
    let _smelt_tmp_2: () = { println!("{}", user.id.clone()); };
}

impl User {
    fn new(arg_1: String) -> Self {
    let mut this: User = User { id: String::new() };
    this.id = arg_1.clone();
    return this;
    }
}
