// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

#[derive(Clone, Debug, Default)]
struct Entity {
    id: String,
}

#[derive(Clone, Debug, Default)]
struct Named {
    id: String,
    name: Option<String>,
}

#[derive(Clone, Debug, Default)]
struct User {
    id: String,
}


fn main() {
    let mut user: User;
    let mut _smelt_tmp_1: User = User::new("u1".to_owned());
    user = _smelt_tmp_1.clone();
    let _ = { println!("{}", user.id.clone()); };
    return;
}

impl User {
    fn new(id: String) -> Self {
    let mut this: Self = User { id: String::new() };
    this.id = id.clone();
    return this;
    }
}
