//! pytest-style helpers for generated Rust tests.
//!
//! Most pytest support should lower directly to Rust assertions. This module
//! holds the pieces that need shared behavior, especially failure formatting and
//! source-language exception checks.

use std::fmt;

use crate::fail;

/// Asserts a Python `assert expr` condition.
///
/// # Panics
///
/// Panics when `condition` is false.
pub fn assert_true(condition: bool) {
    assert_true_with_message(condition, "assertion failed");
}

/// Asserts a Python `assert expr, message` condition.
///
/// # Panics
///
/// Panics when `condition` is false.
pub fn assert_true_with_message(condition: bool, message: impl fmt::Display) {
    if !condition {
        fail(message);
    }
}

/// Asserts Python equality.
///
/// # Panics
///
/// Panics when `actual != expected`.
pub fn assert_eq<T, U>(actual: &T, expected: &U)
where
    T: PartialEq<U> + fmt::Debug + ?Sized,
    U: fmt::Debug + ?Sized,
{
    if actual != expected {
        fail(format_args!(
            "assertion failed: left == right\n  left: {actual:?}\n right: {expected:?}"
        ));
    }
}

/// Asserts Python inequality.
///
/// # Panics
///
/// Panics when `actual == expected`.
pub fn assert_ne<T, U>(actual: &T, expected: &U)
where
    T: PartialEq<U> + fmt::Debug + ?Sized,
    U: fmt::Debug + ?Sized,
{
    if actual == expected {
        fail(format_args!(
            "assertion failed: left != right\n  left: {actual:?}\n right: {expected:?}"
        ));
    }
}

/// Asserts that a block does not satisfy a condition.
///
/// # Panics
///
/// Panics when `condition` is true.
pub fn assert_false(condition: bool) {
    if condition {
        fail("assertion failed: expected false");
    }
}

/// Asserts `pytest.raises` for Result-backed exception paths.
///
/// # Panics
///
/// Panics when `function` does not return an error.
pub fn raises<T, E>(function: impl FnOnce() -> Result<T, E>)
where
    E: fmt::Display,
{
    if function().is_ok() {
        fail("expected exception to be raised");
    }
}

/// Asserts `pytest.raises(..., match=...)` message behavior.
///
/// # Panics
///
/// Panics when `function` does not return an error or its message does not contain
/// `expected`.
pub fn raises_message<T, E>(function: impl FnOnce() -> Result<T, E>, expected: &str)
where
    E: fmt::Display,
{
    let error_text = function().err().map(|error| error.to_string());
    let matched = error_text
        .as_deref()
        .is_some_and(|text| text.contains(expected));
    if let Some(text) = error_text {
        if !matched {
            fail(format_args!(
                "expected exception message to contain {expected:?}, got {text:?}"
            ));
        }
    } else {
        fail("expected exception to be raised");
    }
}

/// Asserts `pytest.raises(Type)` for Result-backed exception lowering.
///
/// Rust code generated by Smelt does not currently preserve Python exception
/// classes. Until it does, type-specific raises checks validate that an
/// exception path was taken.
pub fn raises_type<T, E>(function: impl FnOnce() -> Result<T, E>)
where
    E: fmt::Display,
{
    raises(function);
}

/// Asserts that a block does not raise.
///
/// # Panics
///
/// Panics when `function` returns an error.
pub fn does_not_raise<T, E>(function: impl FnOnce() -> Result<T, E>)
where
    E: fmt::Display,
{
    if function().is_err() {
        fail("expected no exception to be raised");
    }
}

#[cfg(test)]
mod tests {
    use super::{
        assert_eq, assert_false, assert_ne, assert_true, assert_true_with_message, does_not_raise,
        raises, raises_message, raises_type,
    };
    use crate::catches_panic;

    #[test]
    fn assert_true_accepts_true() {
        assert_true(true);
    }

    #[test]
    fn assert_true_rejects_false() {
        assert!(
            catches_panic(|| assert_true(false)),
            "false condition should fail"
        );
    }

    #[test]
    fn assert_true_with_message_rejects_false() {
        assert!(
            catches_panic(|| assert_true_with_message(false, "custom failure")),
            "false condition with message should fail"
        );
    }

    #[test]
    fn assert_eq_accepts_equal_values() {
        assert_eq(&vec![1_i32, 2_i32], &vec![1_i32, 2_i32]);
    }

    #[test]
    fn assert_eq_rejects_different_values() {
        assert!(
            catches_panic(|| assert_eq(&1_i32, &2_i32)),
            "different values should fail equality"
        );
    }

    #[test]
    fn assert_ne_accepts_different_values() {
        assert_ne("left", "right");
    }

    #[test]
    fn assert_ne_rejects_equal_values() {
        assert!(
            catches_panic(|| assert_ne(&1_i32, &1_i32)),
            "equal values should fail inequality"
        );
    }

    #[test]
    fn assert_false_accepts_false() {
        assert_false(false);
    }

    #[test]
    fn assert_false_rejects_true() {
        assert!(
            catches_panic(|| assert_false(true)),
            "true condition should fail assert_false"
        );
    }

    #[test]
    fn raises_accepts_errors() {
        raises(|| Err::<(), _>("expected test error"));
    }

    #[test]
    fn raises_rejects_ok() {
        assert!(
            catches_panic(|| raises(|| Ok::<_, &str>(()))),
            "non-error block should fail raises"
        );
    }

    #[test]
    fn raises_message_checks_error_text() {
        raises_message(|| Err::<(), _>("bad value"), "value");
        assert!(
            catches_panic(|| raises_message(|| Err::<(), _>("bad value"), "missing")),
            "different panic message should fail raises_message"
        );
    }

    #[test]
    fn raises_type_accepts_any_error_for_v1() {
        raises_type(|| Err::<(), _>("expected test error"));
        assert!(
            catches_panic(|| raises_type(|| Ok::<_, &str>(()))),
            "non-error block should fail raises_type"
        );
    }

    #[test]
    fn does_not_raise_accepts_ok() {
        does_not_raise(|| Ok::<_, &str>(()));
    }

    #[test]
    fn does_not_raise_rejects_errors() {
        assert!(
            catches_panic(|| does_not_raise(|| Err::<(), _>("expected test error"))),
            "error block should fail does_not_raise"
        );
    }
}
