// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

fn main() {
    let _smelt_tmp_1: Vec<f64> = vec![1.0, 2.0, 3.0];
    let values: Vec<f64> = _smelt_tmp_1.clone();
    let _ = { println!("{:?}", values.clone()); };
    return;
}
