// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

// @smelt:prelude-end — generated program below
fn main() {
    let enabled: bool = true;
    let _ = { println!("{}", enabled); };
    return;
}
