// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

fn main() {
    let enabled: bool = true;
    let _ = { println!("{}", enabled.clone()); };
}
