//! Code generator for emitting Rust source code from the MIR.
//!
//! This crate provides functionality to transform a MIR (Middle Intermediate Representation)
//! into valid Rust source code, including struct definitions and function implementations.

#![expect(
    clippy::doc_markdown,
    reason = "codegen docs mention generated language tokens that are not fully marked up yet"
)]
#![expect(
    clippy::missing_errors_doc,
    reason = "public codegen entrypoint docs need a focused polish pass"
)]
#![expect(
    clippy::type_complexity,
    reason = "control-flow pattern recognizers currently return structured tuples"
)]
#![expect(
    clippy::format_push_string,
    reason = "Rust code emission is still written as direct string assembly"
)]
#![expect(
    clippy::cast_possible_truncation,
    reason = "MIR/HIR IDs are compact u32 indexes and overflow checks will be centralized separately"
)]
#![expect(
    clippy::branches_sharing_code,
    reason = "codegen branches keep target-specific cases explicit"
)]
#![expect(
    clippy::ifs_same_cond,
    reason = "codegen mutability checks are kept parallel while class handling evolves"
)]
#![expect(
    clippy::too_many_arguments,
    reason = "structured codegen emitters pass explicit control-flow context"
)]
#![expect(
    clippy::too_many_lines,
    reason = "large emitters will be split after behavior stabilizes"
)]
#![expect(
    clippy::literal_string_with_formatting_args,
    reason = "generated Rust format strings intentionally contain braces"
)]
#![expect(
    clippy::wildcard_enum_match_arm,
    reason = "operand formatting groups future constants with existing constants"
)]
#![expect(
    clippy::unused_self,
    reason = "helper methods stay on the emitter for future shared state"
)]
#![expect(
    clippy::trivially_copy_pass_by_ref,
    reason = "type lookup helpers use borrowed IDs consistently with other helpers"
)]
#![expect(
    clippy::needless_pass_by_value,
    reason = "type lookup helpers accept owned HIR type values for call-site readability"
)]
#![expect(
    clippy::missing_const_for_fn,
    reason = "utility const qualification will be handled after behavior cleanup"
)]
#![expect(
    clippy::needless_pass_by_ref_mut,
    reason = "emitter entrypoints reserve mutability for incremental generation state"
)]

use std::{
    collections::{HashMap, HashSet},
    fs,
    path::Path,
};

use smelt_hir::{Symbol, Type, TypeId};
use smelt_mir::{
    BasicBlock, BuiltinFn, Callee, Constant, HirOrigin, LocalId, LocalKind, Mir, MirFunction,
    Operand, Place, Rvalue, Statement, Terminator,
};

/// Options for controlling code emission behavior.
#[derive(Debug, Clone)]
pub struct EmitOptions {
    /// The name of the Rust crate to generate.
    pub crate_name: String,
}

impl Default for EmitOptions {
    /// Returns the default emission options with crate name "smelt_app".
    fn default() -> Self {
        Self {
            crate_name: "smelt_app".to_owned(),
        }
    }
}

/// An error encountered during code emission.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EmitError {
    /// The error message.
    pub message: String,
}

impl std::fmt::Display for EmitError {
    /// Formats the error message for display.
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&self.message)
    }
}

impl std::error::Error for EmitError {}

impl EmitError {
    /// Creates a new emit error with the given message.
    fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}

/// Emits a complete Rust crate from the given MIR.
///
/// Creates the crate structure with Cargo.toml and main.rs files.
pub fn emit_crate(
    mir: &Mir,
    output_dir: impl AsRef<Path>,
    options: &EmitOptions,
) -> Result<(), Box<dyn std::error::Error>> {
    let output_dir = output_dir.as_ref();
    let src_dir = output_dir.join("src");
    fs::create_dir_all(&src_dir)?;
    fs::write(output_dir.join("Cargo.toml"), cargo_toml(options))?;
    fs::write(src_dir.join("main.rs"), emit_source(mir)?)?;
    Ok(())
}

/// Emits Rust source code from the given MIR.
///
/// Returns a string containing the complete source code for the MIR, including
/// struct definitions, free functions, and impl blocks for methods.
pub fn emit_source(mir: &Mir) -> Result<String, EmitError> {
    let mut out = String::new();
    out.push_str("// @generated by smelt. Do not edit by hand.\n\n");

    for class in &mir.classes {
        let name = sanitize_ident(
            mir.symbols
                .get(class.name)
                .ok_or_else(|| EmitError::new("class has unknown symbol"))?,
        );
        out.push_str("#[derive(Clone, Debug)]\n");
        out.push_str(&format!("struct {name} {{\n"));
        for field in &class.fields {
            out.push_str(&format!(
                "    {}: {},\n",
                sanitize_ident(
                    mir.symbols
                        .get(field.name)
                        .ok_or_else(|| EmitError::new("field has unknown symbol"))?
                ),
                FunctionEmitter::type_text_for(mir, field.ty)?
            ));
        }
        out.push_str("}\n\n");
    }

    for (idx, function) in mir.functions.iter().enumerate() {
        if matches!(
            function.origin,
            HirOrigin::ClassConstructor { .. } | HirOrigin::ClassMethod { .. }
        ) {
            continue;
        }
        if idx > 0 || !mir.classes.is_empty() {
            out.push('\n');
        }
        let mut emitter = FunctionEmitter::new(mir, function)?;
        emitter.emit(&mut out)?;
    }

    for class in &mir.classes {
        let name = sanitize_ident(
            mir.symbols
                .get(class.name)
                .ok_or_else(|| EmitError::new("class has unknown symbol"))?,
        );
        out.push_str(&format!("\nimpl {name} {{\n"));
        if let Some(constructor) = class.constructor
            && let Some(function) = mir.functions.get(constructor.0 as usize)
        {
            let mut emitter = FunctionEmitter::new(mir, function)?;
            emitter.emit_method(&mut out)?;
        }
        for method in &class.methods {
            if let Some(function) = mir.functions.get(method.0 as usize) {
                let mut emitter = FunctionEmitter::new(mir, function)?;
                emitter.emit_method(&mut out)?;
            }
        }
        out.push_str("}\n");
    }

    Ok(out)
}

/// Generates Cargo.toml content for the given emission options.
fn cargo_toml(options: &EmitOptions) -> String {
    format!(
        "[workspace]\n\n[package]\nname = \"{}\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[dependencies]\n",
        options.crate_name
    )
}

/// Helper struct for emitting Rust code from a MirFunction.
struct FunctionEmitter<'mir> {
    /// Reference to the MIR.
    mir: &'mir Mir,
    /// The function being emitted.
    function: &'mir MirFunction,
    /// Mapping from local IDs to variable names.
    names: HashMap<LocalId, String>,
    /// Set of locals that are mutated.
    mutable_locals: HashSet<LocalId>,
    /// The type ID of the None type.
    none_ty: TypeId,
}

impl<'mir> FunctionEmitter<'mir> {
    /// Creates a new function emitter for the given MIR and function.
    fn new(mir: &'mir Mir, function: &'mir MirFunction) -> Result<Self, EmitError> {
        let mut used = HashMap::<String, usize>::new();
        let mut names = HashMap::new();
        let none_ty = mir
            .types
            .all()
            .iter()
            .position(|ty| *ty == Type::None)
            .map(|idx| TypeId(idx as u32))
            .ok_or_else(|| EmitError::new("type table does not contain None"))?;

        for (idx, local) in function.locals.iter().enumerate() {
            let local_id = LocalId(idx as u32);
            let base = if matches!(function.origin, HirOrigin::ClassMethod { .. }) && idx == 0 {
                "self".to_owned()
            } else {
                match local.kind {
                    LocalKind::Param => format!("arg_{}", local_id.0),
                    LocalKind::Temp => format!("_smelt_tmp_{}", local_id.0),
                    LocalKind::UserBinding(symbol) => sanitize_ident(
                        mir.symbols
                            .get(symbol)
                            .ok_or_else(|| EmitError::new("local has an unknown symbol"))?,
                    ),
                }
            };
            names.insert(local_id, unique_name(base, &mut used));
        }
        let mutable_locals = assigned_locals(mir, function);

        Ok(Self {
            mir,
            function,
            names,
            mutable_locals,
            none_ty,
        })
    }

    /// Emits a free function definition.
    fn emit(&mut self, out: &mut String) -> Result<(), EmitError> {
        let name = self.symbol_name(self.function.name)?;
        if name == "main" && self.function.return_ty == self.none_ty {
            out.push_str("fn main() {\n");
        } else {
            let params = self
                .function
                .params
                .iter()
                .map(|param| {
                    let local = self.local_decl(*param)?;
                    Ok(format!(
                        "{}: {}",
                        self.local_name(*param)?,
                        self.type_text(local.ty)?
                    ))
                })
                .collect::<Result<Vec<_>, EmitError>>()?
                .join(", ");
            out.push_str(&format!(
                "fn {}({params}) -> {} {{\n",
                sanitize_ident(name),
                self.type_text(self.function.return_ty)?
            ));
        }

        self.emit_block(self.entry_block()?, out)?;
        out.push_str("}\n");
        Ok(())
    }

    /// Emits a method or constructor definition.
    fn emit_method(&mut self, out: &mut String) -> Result<(), EmitError> {
        match self.function.origin {
            HirOrigin::ClassConstructor { .. } => {
                let params = self
                    .function
                    .params
                    .iter()
                    .map(|param| {
                        let local = self.local_decl(*param)?;
                        Ok(format!(
                            "{}: {}",
                            self.local_name(*param)?,
                            self.type_text(local.ty)?
                        ))
                    })
                    .collect::<Result<Vec<_>, EmitError>>()?
                    .join(", ");
                out.push_str(&format!("    fn new({params}) -> Self {{\n"));
            }
            HirOrigin::ClassMethod { method, .. } => {
                let name = sanitize_ident(self.symbol_name(method)?);
                let params = self
                    .function
                    .params
                    .iter()
                    .skip(1)
                    .map(|param| {
                        let local = self.local_decl(*param)?;
                        Ok(format!(
                            "{}: {}",
                            self.local_name(*param)?,
                            self.type_text(local.ty)?
                        ))
                    })
                    .collect::<Result<Vec<_>, EmitError>>()?
                    .join(", ");
                let receiver = if method_mutates_this(self.function) {
                    "&mut self"
                } else {
                    "&self"
                };
                let params = if params.is_empty() {
                    receiver.to_owned()
                } else {
                    format!("{receiver}, {params}")
                };
                out.push_str(&format!(
                    "    fn {name}({params}) -> {} {{\n",
                    self.type_text(self.function.return_ty)?
                ));
            }
            HirOrigin::Body(_) => return self.emit(out),
        }
        self.emit_block(self.entry_block()?, out)?;
        out.push_str("    }\n");
        Ok(())
    }

    /// Converts a type ID to its Rust text representation.
    fn type_text_for(mir: &Mir, ty: TypeId) -> Result<String, EmitError> {
        FunctionEmitter {
            mir,
            function: mir
                .functions
                .first()
                .ok_or_else(|| EmitError::new("MIR has no functions"))?,
            names: HashMap::new(),
            mutable_locals: HashSet::new(),
            none_ty: ty,
        }
        .type_text(ty)
    }

    /// Emits a basic block's statements and terminator.
    fn emit_block(&self, block: &BasicBlock, out: &mut String) -> Result<(), EmitError> {
        if let Some((cond, then_block, else_block, cond_statement_idx)) =
            self.while_header(block)?
        {
            for (idx, statement) in block.statements.iter().enumerate() {
                if idx != cond_statement_idx {
                    self.emit_statement(statement, out)?;
                }
            }
            let then = self.block(then_block)?;
            let else_ = self.block(else_block)?;
            out.push_str(&format!("    while {cond} {{\n"));
            self.emit_block_until_goto(then, block.id, Some(else_block), out)?;
            out.push_str("    }\n");
            return self.emit_block(else_, out);
        }

        if let Some((cond, then_block, latch_block, else_block, cond_statement_idx)) =
            self.while_header_with_latch(block)?
        {
            for (idx, statement) in block.statements.iter().enumerate() {
                if idx != cond_statement_idx {
                    self.emit_statement(statement, out)?;
                }
            }
            let then = self.block(then_block)?;
            let latch = self.block(latch_block)?;
            let else_ = self.block(else_block)?;
            out.push_str(&format!("    while {cond} {{\n"));
            self.emit_block_until_goto(then, latch_block, Some(else_block), out)?;
            for statement in &latch.statements {
                self.emit_statement(statement, out)?;
            }
            out.push_str("    }\n");
            return self.emit_block(else_, out);
        }

        for statement in &block.statements {
            self.emit_statement(statement, out)?;
        }

        let Some(terminator) = &block.terminator else {
            return Err(EmitError::new("basic block has no terminator"));
        };
        self.emit_terminator(block.id, terminator, out)
    }

    /// Emits a single statement.
    fn emit_statement(&self, statement: &Statement, out: &mut String) -> Result<(), EmitError> {
        match statement {
            Statement::Assign { dest, value } => {
                let local = self.local_decl(*dest)?;
                let name = self.local_name(*dest)?;
                let value = self.rvalue_text(value)?;
                let mutability = if self.mutable_locals.contains(dest)
                    || matches!(self.mir.types.get(local.ty), Some(Type::Class { .. }))
                {
                    "mut "
                } else {
                    ""
                };
                out.push_str(&format!(
                    "    let {mutability}{name}: {} = {value};\n",
                    self.type_text(local.ty)?
                ));
                Ok(())
            }
            Statement::AssignPlace { place, value } => {
                let place = self.assignment_place_text(place)?;
                let value = self.rvalue_text(value)?;
                out.push_str(&format!("    {place} = {value};\n"));
                Ok(())
            }
            Statement::StorageLive(_) | Statement::StorageDead(_) => Ok(()),
        }
    }

    /// Emits a block terminator.
    fn emit_terminator(
        &self,
        current: smelt_mir::BlockId,
        terminator: &Terminator,
        out: &mut String,
    ) -> Result<(), EmitError> {
        match terminator {
            Terminator::Goto(target) => self.emit_block(self.block(*target)?, out),
            Terminator::Call {
                callee,
                args,
                dest,
                target,
            } => {
                let value = self.call_text(callee, args)?;
                let local = self.local_decl(*dest)?;
                let name = self.local_name(*dest)?;
                let mutability = if self.mutable_locals.contains(dest)
                    || matches!(self.mir.types.get(local.ty), Some(Type::Class { .. }))
                {
                    "mut "
                } else {
                    ""
                };
                out.push_str(&format!(
                    "    let {mutability}{name}: {} = {value};\n",
                    self.type_text(local.ty)?
                ));
                self.emit_block(self.block(*target)?, out)
            }
            Terminator::Switch {
                cond,
                then_block,
                else_block,
            } => self.emit_switch(current, cond, *then_block, *else_block, out),
            Terminator::Match {
                scrutinee,
                arms,
                default,
            } => self.emit_match(scrutinee, arms, *default, out),
            Terminator::Return(operand) => {
                if self.function.return_ty == self.none_ty {
                    if !matches!(operand, Operand::Const(Constant::None)) {
                        out.push_str(&format!("    {};\n", self.operand_text(operand)?));
                    }
                } else {
                    out.push_str(&format!("    return {};\n", self.operand_text(operand)?));
                }
                Ok(())
            }
            Terminator::Unreachable => {
                out.push_str("    unreachable!();\n");
                Ok(())
            }
        }
    }

    /// Emits an if/else or while loop from a switch terminator.
    fn emit_switch(
        &self,
        current: smelt_mir::BlockId,
        cond: &Operand,
        then_block: smelt_mir::BlockId,
        else_block: smelt_mir::BlockId,
        out: &mut String,
    ) -> Result<(), EmitError> {
        let then = self.block(then_block)?;
        let else_ = self.block(else_block)?;

        if matches!(then.terminator, Some(Terminator::Goto(target)) if target == current) {
            out.push_str(&format!("    while {} {{\n", self.operand_text(cond)?));
            self.emit_block_until_goto(then, current, Some(else_block), out)?;
            out.push_str("    }\n");
            return self.emit_block(else_, out);
        }

        if matches!(then.terminator, Some(Terminator::Goto(target)) if target == else_block) {
            out.push_str(&format!("    if {} {{\n", self.operand_text(cond)?));
            self.emit_block_until_goto(then, else_block, None, out)?;
            out.push_str("    }\n");
            return self.emit_block(else_, out);
        }

        if let (Some(Terminator::Goto(then_target)), Some(Terminator::Goto(else_target))) =
            (&then.terminator, &else_.terminator)
            && then_target == else_target
        {
            out.push_str(&format!("    if {} {{\n", self.operand_text(cond)?));
            self.emit_block_until_goto(then, *then_target, None, out)?;
            out.push_str("    } else {\n");
            self.emit_block_until_goto(else_, *else_target, None, out)?;
            out.push_str("    }\n");
            return self.emit_block(self.block(*then_target)?, out);
        }

        if let (Some(Terminator::Goto(then_target)), Some(Terminator::Goto(else_target))) =
            (&then.terminator, &else_.terminator)
            && then_target != else_target
        {
            out.push_str(&format!("    if {} {{\n", self.operand_text(cond)?));
            for statement in &then.statements {
                self.emit_statement(statement, out)?;
            }
            if then_target.0 <= current.0 {
                out.push_str("    continue;\n");
            } else {
                out.push_str("    break;\n");
            }
            out.push_str("    }\n");
            self.emit_block_until_goto(else_, *else_target, None, out)?;
            return self.emit_block(self.block(*else_target)?, out);
        }

        if let Some(Terminator::Goto(then_target)) = then.terminator {
            out.push_str(&format!("    if {} {{\n", self.operand_text(cond)?));
            for statement in &then.statements {
                self.emit_statement(statement, out)?;
            }
            if then_target.0 <= current.0 {
                out.push_str("    continue;\n");
                out.push_str("    }\n");
                self.emit_block_until_goto(else_, then_target, None, out)?;
                return Ok(());
            }
            out.push_str("    break;\n");
            out.push_str("    }\n");
            return self.emit_block(else_, out);
        }

        if block_terminates(then) && block_terminates(else_) {
            out.push_str(&format!("    if {} {{\n", self.operand_text(cond)?));
            self.emit_block(then, out)?;
            out.push_str("    } else {\n");
            self.emit_block(else_, out)?;
            out.push_str("    }\n");
            return Ok(());
        }

        Err(EmitError::new(
            "if/else codegen requires structured branches with a shared join or terminating arms",
        ))
    }

    /// Checks if a block starts a while loop and returns loop details.
    fn while_header(
        &self,
        block: &BasicBlock,
    ) -> Result<Option<(String, smelt_mir::BlockId, smelt_mir::BlockId, usize)>, EmitError> {
        let Some(Terminator::Switch {
            cond: Operand::Copy(Place::Local(cond_local)),
            then_block,
            else_block,
        }) = &block.terminator
        else {
            return Ok(None);
        };
        let then = self.block(*then_block)?;
        if !self.block_exits_to_loop(then, block.id, *else_block, &mut HashSet::new())? {
            return Ok(None);
        }
        let Some((idx, Statement::Assign { dest, value })) = block
            .statements
            .iter()
            .enumerate()
            .rev()
            .find(|(_, statement)| matches!(statement, Statement::Assign { .. }))
        else {
            return Ok(None);
        };
        if dest != cond_local {
            return Ok(None);
        }
        Ok(Some((
            self.rvalue_text(value)?,
            *then_block,
            *else_block,
            idx,
        )))
    }

    /// Checks if a block eventually exits to a loop target.
    fn block_exits_to_loop(
        &self,
        block: &BasicBlock,
        continue_target: smelt_mir::BlockId,
        break_target: smelt_mir::BlockId,
        visited: &mut HashSet<smelt_mir::BlockId>,
    ) -> Result<bool, EmitError> {
        if !visited.insert(block.id) {
            return Ok(true);
        }
        match &block.terminator {
            Some(Terminator::Goto(target)) => {
                Ok(*target == continue_target || *target == break_target)
            }
            Some(Terminator::Switch {
                then_block,
                else_block,
                ..
            }) => Ok(self.block_exits_to_loop(
                self.block(*then_block)?,
                continue_target,
                break_target,
                visited,
            )? && self.block_exits_to_loop(
                self.block(*else_block)?,
                continue_target,
                break_target,
                visited,
            )?),
            _ => Ok(false),
        }
    }

    /// Checks if a block starts a while loop with a latch block.
    fn while_header_with_latch(
        &self,
        block: &BasicBlock,
    ) -> Result<
        Option<(
            String,
            smelt_mir::BlockId,
            smelt_mir::BlockId,
            smelt_mir::BlockId,
            usize,
        )>,
        EmitError,
    > {
        let Some(Terminator::Switch {
            cond: Operand::Copy(Place::Local(cond_local)),
            then_block,
            else_block,
        }) = &block.terminator
        else {
            return Ok(None);
        };
        let then = self.block(*then_block)?;
        let Some(Terminator::Goto(latch_block)) = then.terminator else {
            return Ok(None);
        };
        let latch = self.block(latch_block)?;
        if !matches!(latch.terminator, Some(Terminator::Goto(target)) if target == block.id) {
            return Ok(None);
        }
        let Some((idx, Statement::Assign { dest, value })) = block
            .statements
            .iter()
            .enumerate()
            .rev()
            .find(|(_, statement)| matches!(statement, Statement::Assign { .. }))
        else {
            return Ok(None);
        };
        if dest != cond_local {
            return Ok(None);
        }
        Ok(Some((
            self.rvalue_text(value)?,
            *then_block,
            latch_block,
            *else_block,
            idx,
        )))
    }

    /// Emits a match expression.
    fn emit_match(
        &self,
        scrutinee: &Operand,
        arms: &[smelt_mir::MatchArm],
        default: Option<smelt_mir::BlockId>,
        out: &mut String,
    ) -> Result<(), EmitError> {
        let scrutinee = self.match_scrutinee_text(scrutinee)?;
        out.push_str(&format!("    match {scrutinee} {{\n"));
        for arm in arms {
            out.push_str(&format!(
                "        {} => {{\n",
                self.match_label_text(&arm.label)
            ));
            self.emit_block_as_match_arm(self.block(arm.target)?, out)?;
            out.push_str("        }\n");
        }
        if let Some(default) = default {
            out.push_str("        _ => {\n");
            self.emit_block_as_match_arm(self.block(default)?, out)?;
            out.push_str("        }\n");
        } else {
            out.push_str("        _ => unreachable!(),\n");
        }
        out.push_str("    }\n");
        if let Some(join) = self.match_join(arms, default)? {
            self.emit_block(self.block(join)?, out)?;
        }
        Ok(())
    }

    /// Emits a match arm body.
    fn emit_block_as_match_arm(
        &self,
        block: &BasicBlock,
        out: &mut String,
    ) -> Result<(), EmitError> {
        for statement in &block.statements {
            self.emit_statement(statement, out)?;
        }
        match &block.terminator {
            Some(Terminator::Goto(_)) => Ok(()),
            Some(terminator) => self.emit_terminator(block.id, terminator, out),
            None => Err(EmitError::new("basic block has no terminator")),
        }
    }

    /// Finds the join block where all match arms converge.
    fn match_join(
        &self,
        arms: &[smelt_mir::MatchArm],
        default: Option<smelt_mir::BlockId>,
    ) -> Result<Option<smelt_mir::BlockId>, EmitError> {
        let mut join = None;
        for target in arms.iter().map(|arm| arm.target).chain(default) {
            let block = self.block(target)?;
            if let Some(Terminator::Goto(target)) = block.terminator {
                if join.replace(target).is_some_and(|seen| seen != target) {
                    return Err(EmitError::new(
                        "match codegen requires all non-terminating arms to share one join block",
                    ));
                }
            }
        }
        Ok(join)
    }

    /// Emits a block's statements until reaching a goto to the stop target.
    fn emit_block_until_goto(
        &self,
        block: &BasicBlock,
        stop: smelt_mir::BlockId,
        break_target: Option<smelt_mir::BlockId>,
        out: &mut String,
    ) -> Result<(), EmitError> {
        for statement in &block.statements {
            self.emit_statement(statement, out)?;
        }
        match &block.terminator {
            Some(Terminator::Goto(target)) if *target == stop => Ok(()),
            Some(Terminator::Goto(target)) if Some(*target) == break_target => {
                out.push_str("    break;\n");
                Ok(())
            }
            Some(Terminator::Switch {
                cond,
                then_block,
                else_block,
            }) if break_target.is_some() => {
                out.push_str(&format!("    if {} {{\n", self.operand_text(cond)?));
                self.emit_loop_branch(self.block(*then_block)?, stop, break_target, out)?;
                out.push_str("    } else {\n");
                self.emit_loop_branch(self.block(*else_block)?, stop, break_target, out)?;
                out.push_str("    }\n");
                Ok(())
            }
            Some(terminator) => self.emit_terminator(block.id, terminator, out),
            None => Err(EmitError::new("basic block has no terminator")),
        }
    }

    /// Emits a branch inside a loop.
    fn emit_loop_branch(
        &self,
        block: &BasicBlock,
        continue_target: smelt_mir::BlockId,
        break_target: Option<smelt_mir::BlockId>,
        out: &mut String,
    ) -> Result<(), EmitError> {
        for statement in &block.statements {
            self.emit_statement(statement, out)?;
        }
        match &block.terminator {
            Some(Terminator::Goto(target)) if *target == continue_target => {
                out.push_str("    continue;\n");
                Ok(())
            }
            Some(Terminator::Goto(target)) if Some(*target) == break_target => {
                out.push_str("    break;\n");
                Ok(())
            }
            Some(Terminator::Switch {
                cond,
                then_block,
                else_block,
            }) => {
                out.push_str(&format!("    if {} {{\n", self.operand_text(cond)?));
                self.emit_loop_branch(
                    self.block(*then_block)?,
                    continue_target,
                    break_target,
                    out,
                )?;
                out.push_str("    } else {\n");
                self.emit_loop_branch(
                    self.block(*else_block)?,
                    continue_target,
                    break_target,
                    out,
                )?;
                out.push_str("    }\n");
                Ok(())
            }
            Some(terminator) => self.emit_terminator(block.id, terminator, out),
            None => Err(EmitError::new("basic block has no terminator")),
        }
    }

    /// Converts an rvalue to its Rust text representation.
    fn rvalue_text(&self, value: &Rvalue) -> Result<String, EmitError> {
        match value {
            Rvalue::Use(operand) => self.operand_text(operand),
            Rvalue::List(items) => {
                let items = items
                    .iter()
                    .map(|item| self.operand_text(item))
                    .collect::<Result<Vec<_>, _>>()?
                    .join(", ");
                Ok(format!("vec![{items}]"))
            }
            Rvalue::Dict(entries) => {
                let entries = entries
                    .iter()
                    .map(|(key, value)| {
                        Ok(format!(
                            "({}, {})",
                            self.operand_text(key)?,
                            self.operand_text(value)?
                        ))
                    })
                    .collect::<Result<Vec<_>, EmitError>>()?
                    .join(", ");
                Ok(format!("::std::collections::HashMap::from([{entries}])"))
            }
            Rvalue::Tuple(items) => {
                let items = items
                    .iter()
                    .map(|item| self.operand_text(item))
                    .collect::<Result<Vec<_>, _>>()?
                    .join(", ");
                if items.contains(',') {
                    Ok(format!("({items})"))
                } else {
                    Ok(format!("({items},)"))
                }
            }
            Rvalue::Binary { op, lhs, rhs } => {
                if *op == smelt_hir::BinOp::Add
                    && matches!(
                        self.mir.types.get(self.operand_ty(lhs)?),
                        Some(Type::String)
                    )
                {
                    let rhs_text = self.operand_text(rhs)?;
                    let rhs_expr = if matches!(
                        self.mir.types.get(self.operand_ty(rhs)?),
                        Some(Type::String)
                    ) {
                        format!("&{rhs_text}")
                    } else {
                        format!("&{rhs_text}.to_string()")
                    };
                    return Ok(format!("{} + {rhs_expr}", self.operand_text(lhs)?));
                }
                Ok(format!(
                    "{} {} {}",
                    self.operand_text(lhs)?,
                    smelt_hir::bin_op_text(*op),
                    self.operand_text(rhs)?
                ))
            }
            Rvalue::Unary { op, operand } => {
                let op = match op {
                    smelt_hir::UnaryOp::Not => "!",
                    smelt_hir::UnaryOp::Neg => "-",
                };
                Ok(format!("{op}{}", self.operand_text(operand)?))
            }
            Rvalue::Struct { class, fields } => {
                let class_name = sanitize_ident(self.symbol_name(*class)?);
                let mir_class = self
                    .mir
                    .classes
                    .iter()
                    .find(|item| item.name == *class)
                    .ok_or_else(|| EmitError::new("struct rvalue references an unknown class"))?;
                let mut parts = Vec::new();
                for field in &mir_class.fields {
                    let name = sanitize_ident(self.symbol_name(field.name)?);
                    if let Some((_, value)) = fields
                        .iter()
                        .find(|(field_name, _)| *field_name == field.name)
                    {
                        parts.push(format!("{name}: {}", self.operand_text(value)?));
                    } else {
                        parts.push(format!("{name}: {}", self.default_value(field.ty)?));
                    }
                }
                Ok(format!("{class_name} {{ {} }}", parts.join(", ")))
            }
            Rvalue::Len(operand) => {
                Ok(format!("{} .len() as f64", self.len_operand_text(operand)?))
            }
        }
    }

    /// Converts an operand for len() to its Rust text representation.
    fn len_operand_text(&self, operand: &Operand) -> Result<String, EmitError> {
        match operand {
            Operand::Copy(place) | Operand::Move(place) => self.place_text(place),
            Operand::Const(_) => Err(EmitError::new("len operand cannot be a constant")),
        }
    }

    /// Converts a function call to its Rust text representation.
    fn call_text(&self, callee: &Callee, args: &[Operand]) -> Result<String, EmitError> {
        match callee {
            Callee::Builtin(BuiltinFn::ConsoleLog) => {
                let rendered_args = args
                    .iter()
                    .map(|arg| self.console_arg_text(arg))
                    .collect::<Result<Vec<_>, _>>()?;
                if rendered_args.is_empty() {
                    Ok("{ println!(); }".to_owned())
                } else {
                    let format = rendered_args
                        .iter()
                        .map(|(format, _)| *format)
                        .collect::<Vec<_>>()
                        .join(" ");
                    let args = rendered_args
                        .into_iter()
                        .map(|(_, value)| value)
                        .collect::<Vec<_>>()
                        .join(", ");
                    Ok(format!("{{ println!(\"{format}\", {args}); }}"))
                }
            }
            Callee::Static(func) => {
                let function = self
                    .mir
                    .functions
                    .get(func.0 as usize)
                    .ok_or_else(|| EmitError::new("call references an unknown function"))?;
                if let HirOrigin::ClassConstructor { class, .. } = function.origin {
                    let class_name = sanitize_ident(self.symbol_name(class)?);
                    let args = args
                        .iter()
                        .map(|arg| self.operand_text(arg))
                        .collect::<Result<Vec<_>, _>>()?
                        .join(", ");
                    return Ok(format!("{class_name}::new({args})"));
                }
                if let HirOrigin::ClassMethod { method, .. } = function.origin {
                    let Some((receiver, rest)) = args.split_first() else {
                        return Err(EmitError::new("method call is missing a receiver"));
                    };
                    let receiver = match receiver {
                        Operand::Copy(place) | Operand::Move(place) => self.place_text(place)?,
                        Operand::Const(_) => {
                            return Err(EmitError::new("method receiver cannot be a constant"));
                        }
                    };
                    let args = rest
                        .iter()
                        .map(|arg| self.operand_text(arg))
                        .collect::<Result<Vec<_>, _>>()?
                        .join(", ");
                    let method = sanitize_ident(self.symbol_name(method)?);
                    return if args.is_empty() {
                        Ok(format!("{receiver}.{method}()"))
                    } else {
                        Ok(format!("{receiver}.{method}({args})"))
                    };
                }
                let name = self.symbol_name(function.name)?;
                let args = args
                    .iter()
                    .map(|arg| self.operand_text(arg))
                    .collect::<Result<Vec<_>, _>>()?
                    .join(", ");
                Ok(format!("{}({args})", sanitize_ident(name)))
            }
            Callee::Indirect(_) => Err(EmitError::new("indirect calls are not implemented yet")),
        }
    }

    /// Converts an operand to its Rust text representation.
    fn operand_text(&self, operand: &Operand) -> Result<String, EmitError> {
        match operand {
            Operand::Copy(place) => Ok(format!("{}.clone()", self.place_text(place)?)),
            Operand::Move(place) => self.place_text(place),
            Operand::Const(constant) => Ok(constant_text(constant)),
        }
    }

    /// Converts an operand to console.log argument format and returns format string and value.
    fn console_arg_text(&self, operand: &Operand) -> Result<(&'static str, String), EmitError> {
        if self.operand_ty(operand)? == self.none_ty {
            Ok(("{}", "\"null\"".to_owned()))
        } else if matches!(
            self.mir.types.get(self.operand_ty(operand)?),
            Some(Type::List(_) | Type::Dict(_, _) | Type::Tuple(_))
        ) {
            Ok(("{:?}", self.operand_text(operand)?))
        } else {
            Ok(("{}", self.operand_text(operand)?))
        }
    }

    /// Converts a match scrutinee operand to its Rust text representation.
    fn match_scrutinee_text(&self, operand: &Operand) -> Result<String, EmitError> {
        if self.operand_ty(operand)? == self.type_id(Type::String)? {
            match operand {
                Operand::Copy(place) | Operand::Move(place) => {
                    Ok(format!("{}.as_str()", self.place_text(place)?))
                }
                Operand::Const(Constant::String(value)) => Ok(format!("{value:?}")),
                Operand::Const(_) => self.operand_text(operand),
            }
        } else {
            self.operand_text(operand)
        }
    }

    /// Converts a constant to its match label text.
    fn match_label_text(&self, constant: &Constant) -> String {
        match constant {
            Constant::String(value) => format!("{value:?}"),
            _ => constant_text(constant),
        }
    }

    /// Gets the type of an operand.
    fn operand_ty(&self, operand: &Operand) -> Result<TypeId, EmitError> {
        match operand {
            Operand::Copy(place) | Operand::Move(place) => self.place_ty(place),
            Operand::Const(Constant::None) => Ok(self.none_ty),
            Operand::Const(Constant::Bool(_)) => self.type_id(Type::Bool),
            Operand::Const(Constant::Int(_)) => self.type_id(Type::Int),
            Operand::Const(Constant::Float(_)) => self.type_id(Type::Float),
            Operand::Const(Constant::String(_)) => self.type_id(Type::String),
        }
    }

    /// Converts a place to its Rust text representation.
    fn place_text(&self, place: &Place) -> Result<String, EmitError> {
        match place {
            Place::Local(local) => self.local_name(*local).map(str::to_owned),
            Place::Field { base, field } => {
                let base_ty = self.local_decl(*base)?.ty;
                if let Some(Type::Dict(key, _)) = self.mir.types.get(base_ty)
                    && self.mir.types.get(*key) == Some(&Type::String)
                {
                    let field = self.symbol_name(*field)?;
                    return Ok(format!(
                        "{}.get({field:?}).cloned().expect(\"missing field\")",
                        self.local_name(*base)?
                    ));
                }
                Ok(format!(
                    "{}.{}",
                    self.local_name(*base)?,
                    sanitize_ident(self.symbol_name(*field)?)
                ))
            }
            Place::Index { base, index } => {
                let base_ty = self.local_decl(*base)?.ty;
                match self.mir.types.get(base_ty) {
                    Some(Type::List(_)) => Ok(format!(
                        "{}.get({} as usize).cloned().expect(\"index out of bounds\")",
                        self.local_name(*base)?,
                        self.operand_text(index)?
                    )),
                    Some(Type::Dict(_, _)) => Ok(format!(
                        "{}.get(&{}).cloned().expect(\"index out of bounds\")",
                        self.local_name(*base)?,
                        self.operand_text(index)?
                    )),
                    _ => Err(EmitError::new(
                        "index codegen is only implemented for lists and dicts",
                    )),
                }
            }
        }
    }

    /// Converts a place to its Rust text representation for assignment.
    fn assignment_place_text(&self, place: &Place) -> Result<String, EmitError> {
        match place {
            Place::Index { base, index } => {
                let base_ty = self.local_decl(*base)?.ty;
                match self.mir.types.get(base_ty) {
                    Some(Type::List(_)) => Ok(format!(
                        "{}[{} as usize]",
                        self.local_name(*base)?,
                        self.operand_text(index)?
                    )),
                    Some(Type::Dict(_, _)) => Ok(format!(
                        "*{}.get_mut(&{}).expect(\"index out of bounds\")",
                        self.local_name(*base)?,
                        self.operand_text(index)?
                    )),
                    _ => Err(EmitError::new(
                        "index assignment codegen is only implemented for lists and dicts",
                    )),
                }
            }
            _ => self.place_text(place),
        }
    }

    /// Gets the type of a place.
    fn place_ty(&self, place: &Place) -> Result<TypeId, EmitError> {
        match place {
            Place::Local(local) => Ok(self.local_decl(*local)?.ty),
            Place::Field { base, .. } => {
                let base_ty = self.local_decl(*base)?.ty;
                match self.mir.types.get(base_ty) {
                    Some(Type::Dict(_, value)) => Ok(*value),
                    Some(Type::Class { name, .. }) => {
                        let Place::Field { field, .. } = place else {
                            unreachable!()
                        };
                        self.mir
                            .classes
                            .iter()
                            .find(|class| class.name == *name)
                            .and_then(|class| class.fields.iter().find(|item| item.name == *field))
                            .map(|field| field.ty)
                            .ok_or_else(|| EmitError::new("class field type lookup failed"))
                    }
                    _ => Err(EmitError::new(
                        "field type lookup is only implemented for dicts",
                    )),
                }
            }
            Place::Index { base, .. } => {
                let base_ty = self.local_decl(*base)?.ty;
                match self.mir.types.get(base_ty) {
                    Some(Type::List(item)) => Ok(*item),
                    Some(Type::Dict(_, value)) => Ok(*value),
                    _ => Err(EmitError::new(
                        "index type lookup is only implemented for lists and dicts",
                    )),
                }
            }
        }
    }

    /// Finds the type ID for a given type.
    fn type_id(&self, needle: Type) -> Result<TypeId, EmitError> {
        self.mir
            .types
            .all()
            .iter()
            .position(|ty| *ty == needle)
            .map(|idx| TypeId(idx as u32))
            .ok_or_else(|| EmitError::new("type table does not contain literal operand type"))
    }

    /// Converts a type ID to its Rust text representation.
    fn type_text(&self, ty: TypeId) -> Result<String, EmitError> {
        let ty = self
            .mir
            .types
            .get(ty)
            .ok_or_else(|| EmitError::new("MIR references an unknown type"))?;
        match ty {
            Type::Bool => Ok("bool".to_owned()),
            Type::Int => Ok("i64".to_owned()),
            Type::Float => Ok("f64".to_owned()),
            Type::String => Ok("String".to_owned()),
            Type::None => Ok("()".to_owned()),
            Type::List(item) => Ok(format!("Vec<{}>", self.type_text(*item)?)),
            Type::Set(item) => Ok(format!(
                "::std::collections::HashSet<{}>",
                self.type_text(*item)?
            )),
            Type::Dict(key, value) => Ok(format!(
                "::std::collections::HashMap<{}, {}>",
                self.type_text(*key)?,
                self.type_text(*value)?
            )),
            Type::Tuple(items) => {
                let items = items
                    .iter()
                    .map(|item| self.type_text(*item))
                    .collect::<Result<Vec<_>, _>>()?
                    .join(", ");
                Ok(format!("({items})"))
            }
            Type::Optional(item) => Ok(format!("Option<{}>", self.type_text(*item)?)),
            Type::Union(_) => Err(EmitError::new("union type codegen is not implemented yet")),
            Type::Class { name, .. } => Ok(sanitize_ident(self.symbol_name(*name)?)),
            Type::Function(_) => Err(EmitError::new(
                "function type codegen is not implemented yet",
            )),
            Type::Future(item) => Ok(format!(
                "::std::pin::Pin<Box<dyn ::std::future::Future<Output = {}>>>",
                self.type_text(*item)?
            )),
        }
    }

    /// Gets the default value for a given type.
    fn default_value(&self, ty: TypeId) -> Result<String, EmitError> {
        match self
            .mir
            .types
            .get(ty)
            .ok_or_else(|| EmitError::new("MIR references an unknown type"))?
        {
            Type::Bool => Ok("false".to_owned()),
            Type::Int => Ok("0".to_owned()),
            Type::Float => Ok("0.0".to_owned()),
            Type::String => Ok("String::new()".to_owned()),
            Type::None => Ok("()".to_owned()),
            Type::List(_) => Ok("Vec::new()".to_owned()),
            Type::Dict(_, _) => Ok("::std::collections::HashMap::new()".to_owned()),
            _ => Err(EmitError::new(
                "default value codegen is not implemented for this field type",
            )),
        }
    }

    /// Gets the entry block of the function.
    fn entry_block(&self) -> Result<&BasicBlock, EmitError> {
        self.block(self.function.entry)
    }

    /// Gets a basic block by ID.
    fn block(&self, block: smelt_mir::BlockId) -> Result<&BasicBlock, EmitError> {
        self.function
            .blocks
            .get(block.0 as usize)
            .ok_or_else(|| EmitError::new("terminator references an unknown block"))
    }

    /// Gets the declaration of a local by ID.
    fn local_decl(&self, local: LocalId) -> Result<&smelt_mir::LocalDecl, EmitError> {
        self.function
            .locals
            .get(local.0 as usize)
            .ok_or_else(|| EmitError::new("MIR references an unknown local"))
    }

    /// Gets the generated variable name for a local.
    fn local_name(&self, local: LocalId) -> Result<&str, EmitError> {
        self.names
            .get(&local)
            .map(String::as_str)
            .ok_or_else(|| EmitError::new("MIR references an unnamed local"))
    }

    /// Gets the string name of a symbol.
    fn symbol_name(&self, symbol: Symbol) -> Result<&str, EmitError> {
        self.mir
            .symbols
            .get(symbol)
            .ok_or_else(|| EmitError::new("MIR references an unknown symbol"))
    }
}

/// Converts a constant to its Rust text representation.
fn constant_text(constant: &Constant) -> String {
    match constant {
        Constant::Bool(value) => value.to_string(),
        Constant::Int(value) => value.to_string(),
        Constant::Float(value) => {
            if value.fract() == 0.0 {
                format!("{value:.1}")
            } else {
                value.to_string()
            }
        }
        Constant::String(value) => format!("{value:?}.to_owned()"),
        Constant::None => "()".to_owned(),
    }
}

/// Checks if a block terminates with return or unreachable.
fn block_terminates(block: &BasicBlock) -> bool {
    matches!(
        block.terminator,
        Some(Terminator::Return(_) | Terminator::Unreachable)
    )
}

/// Computes the set of locals that are assigned after their initial declaration.
fn assigned_locals(mir: &Mir, function: &MirFunction) -> HashSet<LocalId> {
    let mut locals = HashSet::new();
    for block in &function.blocks {
        for statement in &block.statements {
            if let Statement::AssignPlace {
                place: Place::Local(local),
                ..
            } = statement
            {
                locals.insert(*local);
            }
            if let Statement::AssignPlace {
                place: Place::Field { base, .. },
                ..
            } = statement
            {
                locals.insert(*base);
            }
            if let Statement::AssignPlace {
                place: Place::Index { base, .. },
                ..
            } = statement
            {
                locals.insert(*base);
            }
        }
        if let Some(Terminator::Call {
            callee: Callee::Static(func),
            args,
            ..
        }) = &block.terminator
            && let Some(callee) = mir.functions.get(func.0 as usize)
            && method_mutates_this(callee)
            && let Some(Operand::Copy(Place::Local(local)) | Operand::Move(Place::Local(local))) =
                args.first()
        {
            locals.insert(*local);
        }
    }
    locals
}

/// Checks if a method mutates the `this` parameter (self).
fn method_mutates_this(function: &MirFunction) -> bool {
    function.blocks.iter().any(|block| {
        block.statements.iter().any(|statement| {
            matches!(
                statement,
                Statement::AssignPlace {
                    place: Place::Field {
                        base: LocalId(0),
                        ..
                    },
                    ..
                }
            )
        })
    })
}

/// Sanitizes a name to be a valid Rust identifier.
///
/// Replaces invalid characters with underscores and appends an underscore if the name
/// becomes empty or is a Rust keyword.
fn sanitize_ident(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for (idx, ch) in name.chars().enumerate() {
        if ch == '_' || ch.is_ascii_alphanumeric() && (idx > 0 || !ch.is_ascii_digit()) {
            out.push(ch);
        } else {
            out.push('_');
        }
    }

    if out.is_empty() || is_rust_keyword(&out) {
        out.push('_');
    }
    out
}

/// Generates a unique variable name by appending a counter if the base name was previously used.
fn unique_name(base: String, used: &mut HashMap<String, usize>) -> String {
    let count = used.entry(base.clone()).or_insert(0);
    let name = if *count == 0 {
        base
    } else {
        format!("{base}_{count}")
    };
    *count += 1;
    name
}

/// Checks if a name is a Rust keyword.
fn is_rust_keyword(name: &str) -> bool {
    matches!(
        name,
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "async"
            | "await"
            | "become"
            | "box"
            | "do"
            | "dyn"
            | "final"
            | "macro"
            | "override"
            | "priv"
            | "try"
            | "typeof"
            | "union"
            | "unsized"
            | "virtual"
            | "yield"
    )
}

#[cfg(test)]
/// Tests for the code generator.
mod tests {
    use super::*;
    use smelt_frontend_ts::{HirCtx, to_hir};
    use smelt_hir::FileId;

    /// Converts TypeScript source to generated Rust source.
    fn source_for(ts: &str) -> String {
        let mut ctx = HirCtx::new();
        to_hir(ts, FileId(0), &mut ctx).expect("HIR");
        let mut mir = smelt_mir::lower_hir(&ctx.krate).expect("MIR");
        smelt_mir::opt::optimize(&mut mir);
        emit_source(&mir).expect("Rust source")
    }

    #[test]
    fn emits_main_with_console_log() {
        let source = source_for("let count = 42;\nconsole.log(count);\n");

        assert!(source.contains("fn main() {"));
        assert!(source.contains("let count: f64 = 42.0;"));
        assert!(source.contains("let _smelt_tmp_1: () = { println!(\"{}\", count.clone()); };"));
    }

    #[test]
    fn emits_owned_string_literals() {
        let source = source_for("const message = \"hello smelt\";\nconsole.log(message);\n");

        assert!(source.contains("let message: String = \"hello smelt\".to_owned();"));
    }

    #[test]
    fn emits_static_function_with_params_and_return_value() {
        let source = source_for(
            "function add(a: number, b: number): number {
  return a + b;
}
const result = add(2, 3);
console.log(result);
",
        );

        assert!(source.contains("fn add(arg_0: f64, arg_1: f64) -> f64 {"));
        assert!(source.contains("arg_0.clone() + arg_1.clone()"));
        assert!(source.contains("let _smelt_tmp_1: f64 = add(2.0, 3.0);"));
    }

    #[test]
    fn emits_if_else_control_flow() {
        let source = source_for(
            "function max(a: number, b: number): number {
  if (a > b) {
    return a;
  }
  return b;
}
const result = max(2, 3);
console.log(result);
",
        );

        assert!(source.contains("if _smelt_tmp_2.clone() {"));
        assert!(source.contains("return arg_0.clone();"));
        assert!(source.contains("return arg_1.clone();"));
    }

    #[test]
    fn emits_switch_as_rust_match() {
        let source = source_for(
            "function label(status: \"pending\" | \"approved\" | \"rejected\"): string {
  switch (status) {
    case \"pending\":
      return \"Waiting\";
    case \"approved\":
      return \"Approved\";
    case \"rejected\":
      return \"Rejected\";
  }
}
const result = label(\"approved\");
console.log(result);
",
        );

        assert!(source.contains("match arg_0.as_str() {"));
        assert!(source.contains("\"pending\" => {"));
        assert!(source.contains("return \"Waiting\".to_owned();"));
        assert!(source.contains("_ => unreachable!(),"));
    }
}
