//! Code generator for emitting Rust source code from the MIR.
//!
//! This crate provides functionality to transform a MIR (Middle Intermediate Representation)
//! into valid Rust source code, including struct definitions and function implementations.

#![expect(
    clippy::doc_markdown,
    reason = "codegen docs mention generated language tokens that are not fully marked up yet"
)]
#![expect(
    clippy::missing_errors_doc,
    reason = "public codegen entrypoint docs need a focused polish pass"
)]
#![expect(
    clippy::type_complexity,
    reason = "control-flow pattern recognizers currently return structured tuples"
)]
#![expect(
    clippy::format_push_string,
    reason = "Rust code emission is still written as direct string assembly"
)]
#![expect(
    clippy::too_many_arguments,
    reason = "structured codegen emitters pass explicit control-flow context"
)]
#![expect(
    clippy::too_many_lines,
    reason = "large emitters will be split after behavior stabilizes"
)]
#![expect(
    clippy::literal_string_with_formatting_args,
    reason = "generated Rust format strings intentionally contain braces"
)]
#![expect(
    clippy::wildcard_enum_match_arm,
    reason = "operand formatting groups future constants with existing constants"
)]
#![expect(
    clippy::unused_self,
    reason = "helper methods stay on the emitter for future shared state"
)]
#![expect(
    clippy::needless_pass_by_value,
    reason = "type lookup helpers accept owned HIR type values for call-site readability"
)]
#![expect(
    clippy::missing_const_for_fn,
    reason = "utility const qualification will be handled after behavior cleanup"
)]
#![expect(
    clippy::needless_pass_by_ref_mut,
    reason = "emitter entrypoints reserve mutability for incremental generation state"
)]
#![cfg_attr(
    test,
    expect(
        clippy::manual_let_else,
        clippy::match_wild_err_arm,
        clippy::option_if_let_else,
        clippy::panic,
        reason = "codegen tests keep fixture setup compact and fail fast on invalid test inputs"
    )
)]

use std::{fs, path::Path};

use smelt_mir::{HirOrigin, Mir};

pub(crate) mod deps;
pub mod rust;
pub(crate) mod stdlib;

use deps::GeneratedDep;
mod emitter;
use emitter::FunctionEmitter;
use rust::{CodeWriter, RustIdent};

/// Options for controlling code emission behavior.
#[derive(Debug, Clone)]
pub struct EmitOptions {
    /// The name of the Rust crate to generate.
    pub crate_name: String,
}

impl Default for EmitOptions {
    /// Returns the default emission options with crate name "smelt_app".
    fn default() -> Self {
        Self {
            crate_name: "smelt_app".to_owned(),
        }
    }
}

impl EmitOptions {
    /// Creates emission options for the given Rust crate name.
    pub fn new(crate_name: impl Into<String>) -> Self {
        Self {
            crate_name: crate_name.into(),
        }
    }
}

/// An error encountered during code emission.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub struct EmitError {
    /// The error message.
    pub message: String,
}

impl std::fmt::Display for EmitError {
    /// Formats the error message for display.
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&self.message)
    }
}

impl std::error::Error for EmitError {}

impl EmitError {
    /// Creates a new emit error with the given message.
    fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}

/// Converts a compact MIR identifier into a `usize` for indexing.
fn id_index(index: u32, context: &'static str) -> Result<usize, EmitError> {
    usize::try_from(index).map_err(|_err| EmitError::new(context))
}

/// Converts a `usize` into a compact MIR identifier.
fn compact_index(index: usize, context: &'static str) -> Result<u32, EmitError> {
    u32::try_from(index).map_err(|_err| EmitError::new(context))
}

/// Emits a complete Rust crate from the given MIR.
///
/// Creates the crate structure with Cargo.toml and main.rs files.
pub fn emit_crate(
    mir: &Mir,
    output_path: impl AsRef<Path>,
    options: &EmitOptions,
) -> Result<(), Box<dyn std::error::Error>> {
    let output_dir = output_path.as_ref();
    let src_dir = output_dir.join("src");
    fs::create_dir_all(&src_dir)?;
    fs::write(
        output_dir.join("Cargo.toml"),
        deps::cargo_toml(&options.crate_name, &generated_deps(mir)),
    )?;
    fs::write(src_dir.join("main.rs"), emit_source(mir)?)?;
    Ok(())
}

/// Emits Rust source code from the given MIR.
///
/// Returns a string containing the complete source code for the MIR, including
/// struct definitions, free functions, and impl blocks for methods.
pub fn emit_source(mir: &Mir) -> Result<String, EmitError> {
    let mut writer = CodeWriter::new();
    writer.line("// @generated by smelt. Do not edit by hand.");
    writer.line("#![allow(dead_code, unused_variables)]");
    writer.blank_line();
    if stdlib::needs_unknown_type(mir) {
        writer.line("#[derive(Clone, Debug, PartialEq)]");
        writer.block("pub enum SmeltUnknown", |unknown_writer| {
            unknown_writer.line("Null,");
            unknown_writer.line("Bool(bool),");
            unknown_writer.line("Number(f64),");
            unknown_writer.line("String(String),");
            unknown_writer.line("Array(Vec<SmeltUnknown>),");
            unknown_writer.line("Object(::std::collections::HashMap<String, SmeltUnknown>),");
        });
        writer.blank_line();
    }

    for class in &mir.classes {
        let name = sanitize_ident(
            mir.symbols
                .get(class.name)
                .ok_or_else(|| EmitError::new("class has unknown symbol"))?,
        );
        writer.line("#[derive(Clone, Debug)]");
        let mut field_lines = Vec::new();
        for field in &class.fields {
            field_lines.push(format!(
                "{}: {},",
                RustIdent::new(
                    mir.symbols
                        .get(field.name)
                        .ok_or_else(|| EmitError::new("field has unknown symbol"))?
                ),
                FunctionEmitter::type_text_for(mir, field.ty)?
            ));
        }
        writer.block(format!("struct {name}"), |block_writer| {
            for field_line in field_lines {
                block_writer.line(field_line);
            }
        });
        writer.blank_line();
    }

    let mut out = writer.finish();

    for (idx, function) in mir.functions.iter().enumerate() {
        if matches!(
            function.origin,
            HirOrigin::ClassConstructor { .. } | HirOrigin::ClassMethod { .. }
        ) {
            continue;
        }
        if idx > 0 || !mir.classes.is_empty() {
            out.push('\n');
        }
        let mut emitter = FunctionEmitter::new(mir, function)?;
        emitter.emit(&mut out)?;
    }

    for class in &mir.classes {
        let name = sanitize_ident(
            mir.symbols
                .get(class.name)
                .ok_or_else(|| EmitError::new("class has unknown symbol"))?,
        );
        out.push_str(&format!("\nimpl {name} {{\n"));
        if let Some(constructor) = class.constructor
            && let Some(function) = mir.functions.get(id_index(
                constructor.0,
                "constructor index does not fit usize",
            )?)
        {
            let mut emitter = FunctionEmitter::new(mir, function)?;
            emitter.emit_method(&mut out)?;
        }
        for method in &class.methods {
            if let Some(function) = mir
                .functions
                .get(id_index(method.0, "method index does not fit usize")?)
            {
                let mut emitter = FunctionEmitter::new(mir, function)?;
                emitter.emit_method(&mut out)?;
            }
        }
        out.push_str("}\n");
    }

    Ok(out)
}

/// Collects the dependency list required by generated Rust code.
fn generated_deps(mir: &Mir) -> Vec<GeneratedDep> {
    let mut deps = Vec::new();
    if stdlib::needs_tokio(mir) {
        deps.push(GeneratedDep::Tokio);
    }
    deps.extend(
        stdlib::backend_dependencies(mir)
            .into_iter()
            .map(GeneratedDep::Stdlib),
    );
    deps
}

/// Helper struct for emitting Rust code from a MirFunction.
fn sanitize_ident(name: &str) -> String {
    RustIdent::new(name).into_string()
}

#[cfg(test)]
/// Tests for the code generator.
#[cfg(test)]
mod tests;
