use std::{collections::HashMap, fs, path::Path};

use smelt_hir::{Symbol, Type, TypeId};
use smelt_mir::{
    BasicBlock, BuiltinFn, Callee, Constant, LocalId, LocalKind, Mir, MirFunction, Operand, Place,
    Rvalue, Statement, Terminator,
};

#[derive(Debug, Clone)]
pub struct EmitOptions {
    pub crate_name: String,
}

impl Default for EmitOptions {
    fn default() -> Self {
        Self {
            crate_name: "smelt_app".to_owned(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EmitError {
    pub message: String,
}

impl std::fmt::Display for EmitError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&self.message)
    }
}

impl std::error::Error for EmitError {}

impl EmitError {
    fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}

pub fn emit_crate(
    mir: &Mir,
    output_dir: impl AsRef<Path>,
    options: &EmitOptions,
) -> Result<(), Box<dyn std::error::Error>> {
    let output_dir = output_dir.as_ref();
    let src_dir = output_dir.join("src");
    fs::create_dir_all(&src_dir)?;
    fs::write(output_dir.join("Cargo.toml"), cargo_toml(options))?;
    fs::write(src_dir.join("main.rs"), emit_source(mir)?)?;
    Ok(())
}

pub fn emit_source(mir: &Mir) -> Result<String, EmitError> {
    let mut out = String::new();
    out.push_str("// @generated by smelt. Do not edit by hand.\n\n");

    for (idx, function) in mir.functions.iter().enumerate() {
        if idx > 0 {
            out.push('\n');
        }
        let mut emitter = FunctionEmitter::new(mir, function)?;
        emitter.emit(&mut out)?;
    }

    Ok(out)
}

fn cargo_toml(options: &EmitOptions) -> String {
    format!(
        "[package]\nname = \"{}\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[dependencies]\n",
        options.crate_name
    )
}

struct FunctionEmitter<'mir> {
    mir: &'mir Mir,
    function: &'mir MirFunction,
    names: HashMap<LocalId, String>,
    none_ty: TypeId,
}

impl<'mir> FunctionEmitter<'mir> {
    fn new(mir: &'mir Mir, function: &'mir MirFunction) -> Result<Self, EmitError> {
        let mut used = HashMap::<String, usize>::new();
        let mut names = HashMap::new();
        let none_ty = mir
            .types
            .all()
            .iter()
            .position(|ty| *ty == Type::None)
            .map(|idx| TypeId(idx as u32))
            .ok_or_else(|| EmitError::new("type table does not contain None"))?;

        for (idx, local) in function.locals.iter().enumerate() {
            let local_id = LocalId(idx as u32);
            let base = match local.kind {
                LocalKind::Param => format!("arg_{}", local_id.0),
                LocalKind::Temp => format!("_smelt_tmp_{}", local_id.0),
                LocalKind::UserBinding(symbol) => sanitize_ident(
                    mir.symbols
                        .get(symbol)
                        .ok_or_else(|| EmitError::new("local has an unknown symbol"))?,
                ),
            };
            names.insert(local_id, unique_name(base, &mut used));
        }

        Ok(Self {
            mir,
            function,
            names,
            none_ty,
        })
    }

    fn emit(&mut self, out: &mut String) -> Result<(), EmitError> {
        let name = self.symbol_name(self.function.name)?;
        if name == "main" && self.function.return_ty == self.none_ty {
            out.push_str("fn main() {\n");
        } else {
            out.push_str(&format!(
                "fn {}() -> {} {{\n",
                sanitize_ident(name),
                self.type_text(self.function.return_ty)?
            ));
        }

        self.emit_block(self.entry_block()?, out)?;
        out.push_str("}\n");
        Ok(())
    }

    fn emit_block(&self, block: &BasicBlock, out: &mut String) -> Result<(), EmitError> {
        for statement in &block.statements {
            self.emit_statement(statement, out)?;
        }

        let Some(terminator) = &block.terminator else {
            return Err(EmitError::new("basic block has no terminator"));
        };
        self.emit_terminator(terminator, out)
    }

    fn emit_statement(&self, statement: &Statement, out: &mut String) -> Result<(), EmitError> {
        match statement {
            Statement::Assign { dest, value } => {
                let local = self.local_decl(*dest)?;
                let name = self.local_name(*dest)?;
                let value = self.rvalue_text(value)?;
                out.push_str(&format!(
                    "    let {name}: {} = {value};\n",
                    self.type_text(local.ty)?
                ));
                Ok(())
            }
            Statement::StorageLive(_) | Statement::StorageDead(_) => Ok(()),
        }
    }

    fn emit_terminator(&self, terminator: &Terminator, out: &mut String) -> Result<(), EmitError> {
        match terminator {
            Terminator::Goto(_) => Err(EmitError::new(
                "goto codegen is not implemented yet; CFG must be structured before Rust emission",
            )),
            Terminator::Call {
                callee,
                args,
                dest,
                target,
            } => {
                let value = self.call_text(callee, args)?;
                let local = self.local_decl(*dest)?;
                let name = self.local_name(*dest)?;
                out.push_str(&format!(
                    "    let {name}: {} = {value};\n",
                    self.type_text(local.ty)?
                ));
                self.emit_block(self.block(*target)?, out)
            }
            Terminator::Return(operand) => {
                if self.function.return_ty == self.none_ty {
                    if !matches!(operand, Operand::Const(Constant::None)) {
                        out.push_str(&format!("    {};\n", self.operand_text(operand)?));
                    }
                } else {
                    out.push_str(&format!("    return {};\n", self.operand_text(operand)?));
                }
                Ok(())
            }
            Terminator::Unreachable => {
                out.push_str("    unreachable!();\n");
                Ok(())
            }
        }
    }

    fn rvalue_text(&self, value: &Rvalue) -> Result<String, EmitError> {
        match value {
            Rvalue::Use(operand) => self.operand_text(operand),
        }
    }

    fn call_text(&self, callee: &Callee, args: &[Operand]) -> Result<String, EmitError> {
        match callee {
            Callee::Builtin(BuiltinFn::ConsoleLog) => {
                let rendered_args = args
                    .iter()
                    .map(|arg| self.console_operand_text(arg))
                    .collect::<Result<Vec<_>, _>>()?;
                if rendered_args.is_empty() {
                    Ok("{ println!(); }".to_owned())
                } else {
                    let format = vec!["{}"; rendered_args.len()].join(" ");
                    Ok(format!(
                        "{{ println!(\"{format}\", {}); }}",
                        rendered_args.join(", ")
                    ))
                }
            }
            Callee::Static(func) => {
                let function = self
                    .mir
                    .functions
                    .get(func.0 as usize)
                    .ok_or_else(|| EmitError::new("call references an unknown function"))?;
                let name = self.symbol_name(function.name)?;
                let args = args
                    .iter()
                    .map(|arg| self.operand_text(arg))
                    .collect::<Result<Vec<_>, _>>()?
                    .join(", ");
                Ok(format!("{}({args})", sanitize_ident(name)))
            }
            Callee::Indirect(_) => Err(EmitError::new("indirect calls are not implemented yet")),
        }
    }

    fn operand_text(&self, operand: &Operand) -> Result<String, EmitError> {
        match operand {
            Operand::Copy(place) => Ok(format!("{}.clone()", self.place_text(place)?)),
            Operand::Move(place) => self.place_text(place),
            Operand::Const(constant) => Ok(constant_text(constant)),
        }
    }

    fn console_operand_text(&self, operand: &Operand) -> Result<String, EmitError> {
        if self.operand_ty(operand)? == self.none_ty {
            Ok("\"null\"".to_owned())
        } else {
            self.operand_text(operand)
        }
    }

fn operand_ty(&self, operand: &Operand) -> Result<TypeId, EmitError> {
        match operand {
            Operand::Copy(place) | Operand::Move(place) => self.place_ty(place),
            Operand::Const(Constant::None) => Ok(self.none_ty),
            Operand::Const(Constant::Bool(_)) => self.type_id(Type::Bool),
            Operand::Const(Constant::Int(_)) => self.type_id(Type::Int),
            Operand::Const(Constant::Float(_)) => self.type_id(Type::Float),
            Operand::Const(Constant::String(_)) => self.type_id(Type::String),
        }
    }

    fn place_text(&self, place: &Place) -> Result<String, EmitError> {
        match place {
            Place::Local(local) => self.local_name(*local).map(str::to_owned),
        }
    }

    fn place_ty(&self, place: &Place) -> Result<TypeId, EmitError> {
        match place {
            Place::Local(local) => Ok(self.local_decl(*local)?.ty),
        }
    }

    fn type_id(&self, needle: Type) -> Result<TypeId, EmitError> {
        self.mir
            .types
            .all()
            .iter()
            .position(|ty| *ty == needle)
            .map(|idx| TypeId(idx as u32))
            .ok_or_else(|| EmitError::new("type table does not contain literal operand type"))
    }

    fn type_text(&self, ty: TypeId) -> Result<String, EmitError> {
        let ty = self
            .mir
            .types
            .get(ty)
            .ok_or_else(|| EmitError::new("MIR references an unknown type"))?;
        match ty {
            Type::Bool => Ok("bool".to_owned()),
            Type::Int => Ok("i64".to_owned()),
            Type::Float => Ok("f64".to_owned()),
            Type::String => Ok("String".to_owned()),
            Type::None => Ok("()".to_owned()),
            Type::List(item) => Ok(format!("Vec<{}>", self.type_text(*item)?)),
            Type::Set(item) => Ok(format!(
                "::std::collections::HashSet<{}>",
                self.type_text(*item)?
            )),
            Type::Dict(key, value) => Ok(format!(
                "::std::collections::HashMap<{}, {}>",
                self.type_text(*key)?,
                self.type_text(*value)?
            )),
            Type::Tuple(items) => {
                let items = items
                    .iter()
                    .map(|item| self.type_text(*item))
                    .collect::<Result<Vec<_>, _>>()?
                    .join(", ");
                Ok(format!("({items})"))
            }
            Type::Optional(item) => Ok(format!("Option<{}>", self.type_text(*item)?)),
            Type::Union(_) => Err(EmitError::new("union type codegen is not implemented yet")),
            Type::Class { name, .. } => Ok(sanitize_ident(self.symbol_name(*name)?)),
            Type::Function(_) => Err(EmitError::new(
                "function type codegen is not implemented yet",
            )),
            Type::Future(item) => Ok(format!(
                "::std::pin::Pin<Box<dyn ::std::future::Future<Output = {}>>>",
                self.type_text(*item)?
            )),
        }
    }

    fn entry_block(&self) -> Result<&BasicBlock, EmitError> {
        self.block(self.function.entry)
    }

    fn block(&self, block: smelt_mir::BlockId) -> Result<&BasicBlock, EmitError> {
        self.function
            .blocks
            .get(block.0 as usize)
            .ok_or_else(|| EmitError::new("terminator references an unknown block"))
    }

    fn local_decl(&self, local: LocalId) -> Result<&smelt_mir::LocalDecl, EmitError> {
        self.function
            .locals
            .get(local.0 as usize)
            .ok_or_else(|| EmitError::new("MIR references an unknown local"))
    }

    fn local_name(&self, local: LocalId) -> Result<&str, EmitError> {
        self.names
            .get(&local)
            .map(String::as_str)
            .ok_or_else(|| EmitError::new("MIR references an unnamed local"))
    }

    fn symbol_name(&self, symbol: Symbol) -> Result<&str, EmitError> {
        self.mir
            .symbols
            .get(symbol)
            .ok_or_else(|| EmitError::new("MIR references an unknown symbol"))
    }
}

fn constant_text(constant: &Constant) -> String {
    match constant {
        Constant::Bool(value) => value.to_string(),
        Constant::Int(value) => value.to_string(),
        Constant::Float(value) => {
            if value.fract() == 0.0 {
                format!("{value:.1}")
            } else {
                value.to_string()
            }
        }
        Constant::String(value) => format!("{value:?}.to_owned()"),
        Constant::None => "()".to_owned(),
    }
}

fn sanitize_ident(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for (idx, ch) in name.chars().enumerate() {
        if ch == '_' || ch.is_ascii_alphanumeric() && (idx > 0 || !ch.is_ascii_digit()) {
            out.push(ch);
        } else {
            out.push('_');
        }
    }

    if out.is_empty() || is_rust_keyword(&out) {
        out.push('_');
    }
    out
}

fn unique_name(base: String, used: &mut HashMap<String, usize>) -> String {
    let count = used.entry(base.clone()).or_insert(0);
    let name = if *count == 0 {
        base
    } else {
        format!("{base}_{count}")
    };
    *count += 1;
    name
}

fn is_rust_keyword(name: &str) -> bool {
    matches!(
        name,
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use smelt_frontend_ts::{HirCtx, to_hir};
    use smelt_hir::FileId;

    fn source_for(ts: &str) -> String {
        let mut ctx = HirCtx::new();
        to_hir(ts, FileId(0), &mut ctx).expect("HIR");
        let mut mir = smelt_mir::lower_hir(&ctx.krate).expect("MIR");
        smelt_mir::opt::optimize(&mut mir);
        emit_source(&mir).expect("Rust source")
    }

    #[test]
    fn emits_main_with_console_log() {
        let source = source_for("let count = 42;\nconsole.log(count);\n");

        assert!(source.contains("fn main() {"));
        assert!(source.contains("let count: f64 = 42.0;"));
        assert!(source.contains("let _smelt_tmp_1: () = { println!(\"{}\", count.clone()); };"));
    }

    #[test]
    fn emits_owned_string_literals() {
        let source = source_for("const message = \"hello smelt\";\nconsole.log(message);\n");

        assert!(source.contains("let message: String = \"hello smelt\".to_owned();"));
    }
}
