// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

#[path = "source_main.rs"]
mod __smelt_module_source_main;
pub(crate) use __smelt_module_source_main::*;


thread_local! {
    static SMELT_NEXT_OBJECT_ID: ::std::cell::Cell<usize> = const { ::std::cell::Cell::new(1) };
}

#[allow(dead_code)]
fn smelt_next_object_id() -> usize {
    SMELT_NEXT_OBJECT_ID.with(|next| { let id = next.get(); next.set(id.saturating_add(1)); id })
}

/// A JavaScript array: a reference identity plus a shared backing buffer.
pub struct SmeltList<T> {
    id: usize,
    values: ::std::rc::Rc<::std::cell::RefCell<Vec<T>>>,
}
impl<T: ::std::fmt::Debug> ::std::fmt::Debug for SmeltList<T> { fn fmt(&self, formatter: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result { self.values.borrow().fmt(formatter) } }
impl<T> Clone for SmeltList<T> { fn clone(&self) -> Self { Self { id: self.id, values: ::std::rc::Rc::clone(&self.values) } } }
#[allow(dead_code)]
impl<T> SmeltList<T> {
    /// Create an identity-bearing typed list with a fresh JS reference identity.
    fn new(values: Vec<T>) -> Self { Self { id: smelt_next_object_id(), values: ::std::rc::Rc::new(::std::cell::RefCell::new(values)) } }
    /// Reuse a caller-supplied identity so an erase/extract round-trip stays `===` equal.
    fn with_id(id: usize, values: Vec<T>) -> Self { Self { id, values: ::std::rc::Rc::new(::std::cell::RefCell::new(values)) } }
    /// Reuse an existing shared buffer, so a re-wrap keeps aliasing the same array.
    fn with_storage(id: usize, values: ::std::rc::Rc<::std::cell::RefCell<Vec<T>>>) -> Self { Self { id, values } }
    /// Another handle on this array's shared buffer.
    fn storage(&self) -> ::std::rc::Rc<::std::cell::RefCell<Vec<T>>> { ::std::rc::Rc::clone(&self.values) }
    /// JS reference identity of this list.
    fn id(&self) -> usize { self.id }
    /// Borrow the backing storage for reading. The guard lives to the end of the
    /// enclosing statement; never pair it with `borrow_mut` in one expression.
    fn borrow(&self) -> ::std::cell::Ref<'_, Vec<T>> { self.values.borrow() }
    /// Borrow the backing storage for writing, through the shared cell — so this
    /// takes `&self`, and every other handle on the array observes the write.
    fn borrow_mut(&self) -> ::std::cell::RefMut<'_, Vec<T>> { self.values.borrow_mut() }
    /// Element count, taking its own short-lived borrow.
    fn len(&self) -> usize { self.values.borrow().len() }
    /// Whether the array holds no elements.
    fn is_empty(&self) -> bool { self.values.borrow().is_empty() }
    /// Replace every element in place, so aliases observe the new contents.
    fn replace_all(&self, values: Vec<T>) { *self.values.borrow_mut() = values; }
}
#[allow(dead_code)]
impl<T: Clone> SmeltList<T> {
    /// A JS array copy (`[...a]`, `slice`): same contents, a NEW identity AND a
    /// new buffer. This is the operation that keeps sharing from over-sharing.
    fn fresh_copy(&self) -> Self { Self::new(self.values.borrow().clone()) }
    /// Snapshot the elements. This COPIES unless this is the last handle, so
    /// mutating the result does not write back.
    fn into_vec(self) -> Vec<T> { match ::std::rc::Rc::try_unwrap(self.values) { Ok(cell) => cell.into_inner(), Err(shared) => shared.borrow().clone() } }
    /// Snapshot the elements without consuming the handle.
    fn to_vec(&self) -> Vec<T> { self.values.borrow().clone() }
    /// Read one element by index, cloned out of the shared buffer (JS `arr[i]`).
    fn get_index(&self, index: usize) -> Option<T> { self.values.borrow().get(index).cloned() }
    /// Set the element at a numeric index, extending with `fill` holes to match JS `arr[i] = v`.
    fn set_index(&self, index: usize, value: T, fill: T) { let mut values = self.values.borrow_mut(); if index >= values.len() { values.resize(index.saturating_add(1), fill); } values[index] = value; }
    /// Iterate a snapshot of the elements, so the buffer is not borrowed across the loop body.
    fn iter(&self) -> ::std::vec::IntoIter<T> { self.values.borrow().clone().into_iter() }
}
impl<T> From<Vec<T>> for SmeltList<T> { fn from(values: Vec<T>) -> Self { Self::new(values) } }
impl<T> ::std::iter::FromIterator<T> for SmeltList<T> { fn from_iter<I: IntoIterator<Item = T>>(iter: I) -> Self { Self::new(iter.into_iter().collect()) } }
impl<T: Clone> IntoIterator for SmeltList<T> { type Item = T; type IntoIter = ::std::vec::IntoIter<T>; fn into_iter(self) -> Self::IntoIter { self.into_vec().into_iter() } }
impl<T: Clone> IntoIterator for &SmeltList<T> { type Item = T; type IntoIter = ::std::vec::IntoIter<T>; fn into_iter(self) -> Self::IntoIter { self.values.borrow().clone().into_iter() } }
impl<T: PartialEq> PartialEq for SmeltList<T> { fn eq(&self, other: &Self) -> bool { *self.values.borrow() == *other.values.borrow() } }
impl<T: PartialEq> Eq for SmeltList<T> {}
impl<T: ::std::hash::Hash> ::std::hash::Hash for SmeltList<T> { fn hash<H: ::std::hash::Hasher>(&self, state: &mut H) { self.values.borrow().hash(state); } }
impl<T> Default for SmeltList<T> { fn default() -> Self { Self::new(Vec::new()) } }
impl<T: Clone> From<SmeltList<T>> for Vec<T> { fn from(list: SmeltList<T>) -> Self { list.into_vec() } }

#[derive(Clone, Debug, Default, PartialEq)]
struct Sink {
}

// @smelt:prelude-end — generated program below

thread_local! {
    static SMELT_GLOBAL_EVALUATIONS_0: ::std::cell::Cell<f64> = const { ::std::cell::Cell::new(0.0) };
}

fn main() {
    let mut __smelt_spread: (String, String, f64);
    let mut tail: (String, f64);
    let mut __smelt_spread_1: (String, f64);
    let mut __smelt_spread_2: (String, String, f64);
    let mut sink: Sink;
    let mut __smelt_spread_3: (String, String, f64);
    let mut __smelt_spread_4: (String, String, f64);
    let mut one_route: SmeltList<(String, String, f64)>;
    let mut __smelt_spread_5: (String, String, f64);
    let mut _smelt_tmp_15: f64;
    let mut _smelt_tmp_16: bool;
    let mut _smelt_tmp_19: f64;
    let mut _smelt_tmp_20: (String, f64);
    let mut _smelt_tmp_23: ::std::rc::Rc<dyn Fn(String, String, f64) -> String> = { let smelt_default_callback: ::std::rc::Rc<dyn Fn(String, String, f64) -> String> = ::std::rc::Rc::new(move |arg0: String, arg1: String, arg2: f64| -> String { String::new() }); smelt_default_callback };
    let mut _smelt_tmp_24: String;
    let mut _smelt_tmp_32: f64;
    let mut _smelt_tmp_33: String;
    let mut _smelt_tmp_35: (String, String, f64);
    let mut _smelt_tmp_36: SmeltList<(String, String, f64)>;
    let _smelt_tmp_12: (String, String, f64) = ("GET".to_owned(), "/a".to_owned(), 1.0);
    let _smelt_tmp_13: (String, String, f64) = ("POST".to_owned(), "/b".to_owned(), 2.0);
    let _smelt_tmp_14: SmeltList<(String, String, f64)> = Into::<SmeltList<_>>::into(SmeltList::from({ let smelt_list_items: Vec<(String, String, f64)> = vec![_smelt_tmp_12.clone(), _smelt_tmp_13.clone()]; smelt_list_items }));
    let routes: SmeltList<(String, String, f64)> = Into::<SmeltList<_>>::into(_smelt_tmp_14);
    let mut i: f64 = 0.0;
    loop {
    _smelt_tmp_15 = routes.len() as f64;
    _smelt_tmp_16 = i < _smelt_tmp_15;
    if !(_smelt_tmp_16) { break; }
    __smelt_spread = routes.borrow().get({ let normalized = i as i64; usize::try_from(normalized).unwrap_or(usize::MAX) }).cloned().unwrap_or_else(|| (String::new(), String::new(), 0.0));
    let _smelt_tmp_17: String = record(__smelt_spread.0.clone(), __smelt_spread.1.clone(), __smelt_spread.2);
    let _ = { println!("{}", _smelt_tmp_17); };
    _smelt_tmp_19 = i + 1.0;
    i = _smelt_tmp_19;
    }
    _smelt_tmp_20 = ("/c".to_owned(), 7.0);
    tail = _smelt_tmp_20;
    __smelt_spread_1 = tail;
    let _smelt_tmp_21: String = record("DELETE".to_owned(), __smelt_spread_1.0.clone(), __smelt_spread_1.1);
    let _ = { println!("{}", _smelt_tmp_21); };
    __smelt_spread_2 = routes.borrow().get({ let normalized = 0.0 as i64; usize::try_from(normalized).unwrap_or(usize::MAX) }).cloned().unwrap_or_else(|| (String::new(), String::new(), 0.0));
    _smelt_tmp_23 = ::std::rc::Rc::new(|closure_arg_0: String, closure_arg_1: String, closure_arg_2: f64| {
    let _smelt_tmp_3 = ::std::rc::Rc::new(|closure_arg_0: String, closure_arg_1: String, closure_arg_2: f64| {
    let _smelt_tmp_3: String = record(closure_arg_0.clone(), closure_arg_1.clone(), closure_arg_2);
    _smelt_tmp_3.clone()
    });
    let _smelt_tmp_4: String = (_smelt_tmp_3)(closure_arg_0.clone(), closure_arg_1.clone(), closure_arg_2);
    let _smelt_tmp_5: String = "closure ".to_owned() + &_smelt_tmp_4.clone();
    _smelt_tmp_5.clone()
    });
    _smelt_tmp_24 = (_smelt_tmp_23)(__smelt_spread_2.0.clone(), __smelt_spread_2.1.clone(), __smelt_spread_2.2);
    let _ = { println!("{}", _smelt_tmp_24); };
    let _smelt_tmp_26: Sink = Sink::new();
    sink = _smelt_tmp_26;
    __smelt_spread_3 = routes.borrow().get({ let normalized = 1.0 as i64; usize::try_from(normalized).unwrap_or(usize::MAX) }).cloned().unwrap_or_else(|| (String::new(), String::new(), 0.0));
    let _smelt_tmp_27: String = sink.take(__smelt_spread_3.0.clone(), __smelt_spread_3.1.clone(), __smelt_spread_3.2);
    let _ = { println!("{}", _smelt_tmp_27); };
    let _smelt_tmp_29: (String, String, f64) = make_route();
    __smelt_spread_4 = _smelt_tmp_29;
    let _smelt_tmp_30: String = record(__smelt_spread_4.0.clone(), __smelt_spread_4.1.clone(), __smelt_spread_4.2);
    let _ = { println!("{}", _smelt_tmp_30); };
    _smelt_tmp_32 = SMELT_GLOBAL_EVALUATIONS_0.with(::std::cell::Cell::get);
    _smelt_tmp_33 = "evaluations: ".to_owned() + &_smelt_tmp_32.to_string();
    let _ = { println!("{}", _smelt_tmp_33); };
    _smelt_tmp_35 = ("PATCH".to_owned(), "/maybe".to_owned(), 4.0);
    _smelt_tmp_36 = Into::<SmeltList<_>>::into(SmeltList::from({ let smelt_list_items: Vec<(String, String, f64)> = vec![_smelt_tmp_35.clone()]; smelt_list_items }));
    one_route = Into::<SmeltList<_>>::into(_smelt_tmp_36);
    __smelt_spread_5 = one_route.borrow().get({ let normalized = 0.0 as i64; usize::try_from(normalized).unwrap_or(usize::MAX) }).cloned().unwrap_or_else(|| (String::new(), String::new(), 0.0));
    let _smelt_tmp_37: String = record(__smelt_spread_5.0.clone(), __smelt_spread_5.1.clone(), __smelt_spread_5.2);
    let _ = { println!("{}", _smelt_tmp_37); };
    return;
}

impl Sink {
    fn new() -> Self {
    let this: Self = Sink {  };
    return this;
    }
    fn take(&self, method: String, path: String, weight: f64) -> String {
    let _smelt_tmp_5: String;
    let _smelt_tmp_4: String = record(method.clone(), path.clone(), weight);
    _smelt_tmp_5 = "method ".to_owned() + &_smelt_tmp_4;
    return _smelt_tmp_5;
    }
}
