// @generated by smelt. Do not edit by hand.
#![allow(dead_code, non_snake_case, unused_imports, unused_variables)]

/// `Number::toString(value, 10)`: JavaScript's number formatting.
///
/// Exponential notation at `n > 21` and `n <= -6`, where `n` is the
/// decimal exponent of the shortest round-trip digit string — which is
/// what Rust's `{:e}` already produces.
fn smelt_number_to_string<N: ::std::borrow::Borrow<f64>>(value: N) -> String {
    let value = *value.borrow();
    if value.is_nan() { return "NaN".to_owned(); }
    if value == 0.0 { return "0".to_owned(); }
    if value < 0.0 { return format!("-{}", smelt_number_to_string(-value)); }
    if value.is_infinite() { return "Infinity".to_owned(); }
    let exponential = format!("{value:e}");
    let (mantissa, exponent) = exponential.split_once('e').unwrap_or((exponential.as_str(), "0"));
    let digits: String = mantissa.chars().filter(char::is_ascii_digit).collect();
    let k = i32::try_from(digits.len()).unwrap_or(i32::MAX);
    let n = exponent.parse::<i32>().unwrap_or(0) + 1;
    if k <= n && n <= 21 {
        let zeros = usize::try_from(n - k).unwrap_or(0);
        return digits + &"0".repeat(zeros);
    }
    if 0 < n && n <= 21 {
        let split = usize::try_from(n).unwrap_or(0);
        return format!("{}.{}", &digits[..split], &digits[split..]);
    }
    if -6 < n && n <= 0 {
        let zeros = usize::try_from(-n).unwrap_or(0);
        return format!("0.{}{}", "0".repeat(zeros), digits);
    }
    let sign = if n - 1 < 0 { '-' } else { '+' };
    let magnitude = (n - 1).abs();
    if k == 1 { return format!("{digits}e{sign}{magnitude}"); }
    format!("{}.{}e{sign}{magnitude}", &digits[..1], &digits[1..])
}

/// `console.log`'s number formatting: the spec's rule, but `-0` prints `-0`.
fn smelt_console_number<N: ::std::borrow::Borrow<f64>>(value: N) -> String { let value = *value.borrow(); if value == 0.0 && value.is_sign_negative() { return "-0".to_owned(); } smelt_number_to_string(value) }

#[derive(Clone, Debug, Default, PartialEq)]
struct Base {
    label: String,
}

#[derive(Clone, Debug, Default, PartialEq)]
struct Derived {
    label: String,
    extra: f64,
}

#[derive(Clone, Debug, Default, PartialEq)]
struct Point {
    x: f64,
    y: f64,
}

#[derive(Clone, Debug, Default, PartialEq)]
struct Point3 {
    x: f64,
    y: f64,
    z: f64,
}

#[derive(Clone, Debug, Default, PartialEq)]
struct Tagged {
    tag: String,
}

#[derive(Clone, Debug, Default, PartialEq)]
struct Labelled {
    tag: String,
    seen: bool,
}

#[derive(Clone, Debug, Default, PartialEq)]
struct Deeper {
    x: f64,
    y: f64,
    z: f64,
    w: f64,
}

// @smelt:prelude-end — generated program below

fn main() {
    let derived: Derived;
    let point: Point3;
    let deeper: Deeper;
    let _smelt_tmp_3: Derived = Derived::new();
    derived = _smelt_tmp_3;
    let _smelt_tmp_4: String = derived.describe();
    let _ = { println!("{} {} {}", _smelt_tmp_4, derived.label.clone(), smelt_console_number(derived.extra)); };
    let _smelt_tmp_6: Point3 = Point3::new(1.0, 2.0);
    point = _smelt_tmp_6;
    let _smelt_tmp_7: f64 = point.sum();
    let _ = { println!("{} {} {} {}", smelt_console_number(_smelt_tmp_7), smelt_console_number(point.x), smelt_console_number(point.y), smelt_console_number(point.z)); };
    let _smelt_tmp_9: Labelled = Labelled::new(None::<String>);
    let _smelt_tmp_10: Labelled = Labelled::new(Some("here".to_owned()));
    let _smelt_tmp_11: Labelled = Labelled::new(None::<String>);
    let _ = { println!("{} {} {}", _smelt_tmp_9.tag.clone(), _smelt_tmp_10.tag.clone(), _smelt_tmp_11.seen); };
    let _smelt_tmp_13: Deeper = Deeper::new(5.0, 6.0);
    deeper = _smelt_tmp_13;
    let _smelt_tmp_14: f64 = deeper.sum();
    let _ = { println!("{} {} {} {} {}", smelt_console_number(deeper.x), smelt_console_number(deeper.y), smelt_console_number(deeper.z), smelt_console_number(deeper.w), smelt_console_number(_smelt_tmp_14)); };
    return;
}

impl Base {
    fn new() -> Self {
    let mut this: Self = Base { label: String::new() };
    this.label = "base".to_owned();
    return this;
    }
    fn describe(&self) -> String {
    let _smelt_tmp_1: String = "Base(".to_owned() + &self.label.clone();
    let _smelt_tmp_2: String = _smelt_tmp_1 + &")".to_owned();
    return _smelt_tmp_2;
    }
}

impl Derived {
    fn new() -> Self {
    let __smelt_super: Base;
    let mut this: Self = Derived { label: String::new(), extra: 0.0 };
    let _smelt_tmp_2: Base = Base::new();
    __smelt_super = _smelt_tmp_2;
    this.label = __smelt_super.label.clone();
    this.extra = 7.0;
    return this;
    }
    fn describe(&self) -> String {
    let _smelt_tmp_1: String = "Base(".to_owned() + &self.label.clone();
    let _smelt_tmp_2: String = _smelt_tmp_1 + &")".to_owned();
    return _smelt_tmp_2;
    }
}

impl Point {
    fn new(x: f64, y: f64) -> Self {
    let mut this: Self = Point { x: 0.0, y: 0.0 };
    this.x = x;
    this.y = y;
    return this;
    }
    fn sum(&self) -> f64 {
    let _smelt_tmp_1: f64 = self.x + self.y;
    return _smelt_tmp_1;
    }
}

impl Point3 {
    fn new(x: f64, y: f64) -> Self {
    let __smelt_super: Point;
    let mut this: Self = Point3 { x: 0.0, y: 0.0, z: 0.0 };
    let _smelt_tmp_4: Point = Point::new(x, y);
    __smelt_super = _smelt_tmp_4;
    this.x = __smelt_super.x;
    this.y = __smelt_super.y;
    this.z = 3.0;
    return this;
    }
    fn sum(&self) -> f64 {
    let _smelt_tmp_1: f64 = self.x + self.y;
    return _smelt_tmp_1;
    }
}

impl Tagged {
    fn new(tag: Option<String>) -> Self {
    let mut this: Self = Tagged { tag: String::new() };
    let _smelt_tmp_3: String = tag.clone().clone().unwrap_or("none".to_owned());
    let tag_1: String = _smelt_tmp_3;
    this.tag = tag_1;
    return this;
    }
}

impl Labelled {
    fn new(tag: Option<String>) -> Self {
    let __smelt_super: Tagged;
    let mut this: Self = Labelled { tag: String::new(), seen: false };
    let _smelt_tmp_3: Tagged = Tagged::new(tag.clone());
    __smelt_super = _smelt_tmp_3;
    this.tag = __smelt_super.tag.clone();
    this.seen = true;
    return this;
    }
}

impl Deeper {
    fn new(x: f64, y: f64) -> Self {
    let __smelt_super: Point3;
    let mut this: Self = Deeper { x: 0.0, y: 0.0, z: 0.0, w: 0.0 };
    let _smelt_tmp_4: Point3 = Point3::new(x, y);
    __smelt_super = _smelt_tmp_4;
    this.x = __smelt_super.x;
    this.y = __smelt_super.y;
    this.z = __smelt_super.z;
    this.w = 4.0;
    return this;
    }
    fn sum(&self) -> f64 {
    let _smelt_tmp_1: f64 = self.x + self.y;
    return _smelt_tmp_1;
    }
}
